### ISSUE TITLE
A la question : petit déjeuner

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1001]
Avez-vous pensé que nombreux sont ceux, qui, comme moi, sommes diabétiques et prennent un petit déjeuner plutôt salé.
Le mien se compose en général d'un petit toast avec du fromage ou jambon et café noir.

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Super merci pour votre retour, c'est intégré dans #453  :)
