### ISSUE TITLE
Le sujet est tabou mais vous n'incluez pas le nombre d'enfants

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1002]
Le bilan carbone d'un enfant est largement supérieur à un vol en avion, ou manger un steak. Le souci est la surpopulation, le nombre d'humains sur terre. maintenant que nous sommes trop nombreux, croire que de réduire ses voyages va suffire, alors que la plus grosse empreinte carbone est l'homme. Le bétonnage des villes, la surconsommation de produits bas de gamme (souvent en plastique) Quand  les mentalités changeront, votre discours deviendra cohérent. Pour l'instant, on bricole avec des chiffres, mais il faut interdire le plastique (pas en 2025, c'est maintenant qu'il faut agir, réduire l'empreinte humaine). L'écologie urbaine. Les mairies favorisent la surpopulation, construisent des immeubles afin que plus de gens habitent en ville. Pour Nantes, on interdit les voitures mais on bétonne autant que l'on peu. bref, il faut se réveiller les amis

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Pour les enfants, voir  #984 
Pour le reste, n'hésitez pas à faire des messages plus détaillés sur des points **que nous pouvons améliorer dans le simulateur** :)

**Comment by laem** [comment]
Au sujet de la population, voir https://bonpote.com/la-demographie-sujet-tabou-de-lecologie notamment.
