### ISSUE TITLE
impossible de modifier  les réponses 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1007]
Il serait intéressant également de mémoriser  nos réponses  pour mesurer nos progrès. ..

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Voir https://github.com/datagir/nosgestesclimat-site/issues/236
