### ISSUE TITLE
Ergonomie

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1008]
Le bouton "suivant" après chaque question fait perdre du temps, il serait plus logique de valider automatique et d'offrir la possibilité de revenir sur la question précédente en cas d'erreur

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, le bouton suivant permet de comparer des réponses entre elles avant de valider. 
Par exemple, cliquer sur "voiture électrique", puis sur "voiture thermique", et constater la différence de résultat. Nous estimons pour l'instant que cela apporte un côté conseil et exploration au simulateur qui vaut autant que le clic sur chaque bouton suivant.
Aussi, supprimer le bouton suivant introduirai un traitement différent des questions numériques (par exemple les litres au 100km de la voiture) qui doivent de toutes façons avoir un bouton de validation de la saisie.  

Sachez cependant qu'une fois votre choix fait, vous pouvez taper "Entrer" sur votre clavier. Et pour valider directement une option, vous pouvez même double cliquer dessus :)
