### ISSUE TITLE
voiture ou pas voiture

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1009]
Dans la rubriqrubrique transport. Il m'est demandé si je possède une voiture, la réponse est non. La question suivantsuivante est quel type de voiture.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
La réponse est dans la FAQ ;) 

https://nosgestesclimat.fr/contribuer
