### ISSUE TITLE
Milieu rural

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1010]
Vos questions concernant le transport ne sont pas pertinentes pour le milieu rural, moyenne montagne. Aucun transport en commun n'existe et le train, quand la ligne est ouverte c'est 2 fois par jour. En Lozère, c'est compliqué.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, il suffit de répondre 0 ou non aux questions non pertinentes. Ce simulateur ne modifiera jamais l'empreinte climat en fonction du lieu d'habitation, ce n'est pas son rôle.
