### ISSUE TITLE
aliments dates courtes / anti-gaspillage

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1012]
Bonjour, je ne sais pas si vous avez beaucoup eu cette demande, mais il me semble que favoriser des aliments en date courtes aura un impact significatif sur notre empreinte. (un peu comme les produits d'occasion par rapport au neuf)

Dans mon cas l'alimentation est le deuxième impact (1T) derrière les services publics (1.1T), alors que en valeur original ~3/4 de mes aliments sont en date courte.

Au moins il pourrait être intéressant de poser cette question dans le simulateur pour montrer que c'est une possibilité de réduire ses impactes.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, que signifie date courte pour vous ? Privilégier l'achat d'aliments qui sont proches de leur date de péremption ?

**Comment by Clemog** [comment]
J'ouvre la question dans #1443 mais à priori pas évident et sujet peu prioritaire vu l'impact à priori faible (niveau carbone)
