### ISSUE TITLE
Je n'ai pas de télé mais on me demande son âge 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1013]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, c'est que vous avez laissé cochée "télévision" dans le questionnaire à choix multiple ici nosgestesclimat.fr/simulateur/numérique.
