### ISSUE TITLE
Question petit dej

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1015]
Bonjour, pour le petit petit-déjeuner il n'y a pas la traditionnelle baguette. A moins qu'il faille considérer "baguette + vienoiserie"?

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/petit-déjeuner-annuel`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci, noté dans #453
