### ISSUE TITLE
que faites vous de nos données?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1017]
Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Tout est là : https://nosgestesclimat.fr/vie-privée
N'hésitez pas si vous avez des questions plus précises.
