### ISSUE TITLE
Transport à pied

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1020]
J'habite en centre ville et me déplace principalement à pied. J'indique donc ne pas utiliser les transports en commun or le simulateur semble pénaliser le fait de ne pas utiliser les transports en commun.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, pouvez-vous préciser ce qu'il se passe ? "pénaliser", vous voyez une hausse de l'empreinte CO2e en répondant *moins* de transport en commun ?
