### ISSUE TITLE
Impact repas

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1021]
L’impact du repas végétarien est plus grand que celui du repas viande 1, est-ce normal ?

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/plats`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
La page que vous visualisiez présente l'empreinte du *régime*, donc le plat x le nombre de consommations par semaine :) 

Vous avez sélectionné 2x plus de plats végé par semaine que de viande 1, d'où votre impression. 

Dites-nous si l'erreur est ailleurs :)
