### ISSUE TITLE
Bouton "retour" 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1022]
Bonjour, je remplis le test sur mobile et je ne trouve pas de bouton retour si on s'est trompé à la réponse précédente

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, 
merci pour le retour (😏), nous avons en effet enlevé le bouton retour car il n'était pas correctement implémenté. Le bouton "mes réponses" sert à cela. L'avez-vous vu ? 

Peut-être que nous pourrions mettre la dernière question en haut de l'écran "mes réponses" ?
