### ISSUE TITLE
Moteur essence/diesel = thermique

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1026]
Certaines personnes de mon entourage ne savent pas que leur voiture à essence ou diesel/gasoil correspond à la catégorie "thermique" dans la question "Quel type de voiture utilisez-vous ?". Il suffirait d'ajouter le détail entre parenthèses ("Thermique (essence, diesel)") afin d'éviter la confusion.
Hadrien

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Super, merci pour la bonne suggestion :)
