### ISSUE TITLE
Questions voiture alors que pas de voiture individuelle

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1027]
Bonjour, Les paramètres transports ne sont pas complets. Je n’ai pas de véhicule et n’ai pas pu refuser ce choix dans les paramètres. Je n’ai même pas le permis et circule majoritairement à pieds et en vélo. En tout cas c’est très intéressant, merci beaucoup. Poursuivez 

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Il faut qu'on affiche un message sympa du type "vous n'avez pas de véhicule, mais vous avez quand même spécifié que vous faites des km en voiture, d'où les questions sur la voiture utilisée".

**Comment by laem** [comment]
C'est fait :heavy_check_mark:
