### ISSUE TITLE
Coupe.

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1031]
Je ne sais si le bilan a été complet car il s'est arrêté brusquement sans "logique" apparente.

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, pouvez-vous nous dire à quel moment cela s'est passé ? Etait-ce une page blanche ?
