### ISSUE TITLE
TV

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1034]
il n'y a pas de case pour mettre qu'on n'en possède pas ! j'ai mis 0  année, je suppose qu'une tv neuve a été prise en compte.

Depuis la page : `https://nosgestesclimat.fr/documentation/numérique/TV/présent`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, vous pouvez simplement décocher la case "TV" dans la liste de matériel numérique. 

![Capture d’écran du 2021-06-07 15-48-31](https://user-images.githubusercontent.com/1177762/121028109-d1e76200-c7a7-11eb-8fe5-54dcd7624b21.png)
