### ISSUE TITLE
Compensation

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1036]
Bonjour. Ma maison comporte 2 modes de chauffage: bois + électrique.. Je compense pratiquement toute ma consommation électrique (Maison 8000 et voiture 3000) annuelle, avec ma production photovoltaïque (10800 kWh/an) : ça n apparaît nulle part dans votre simulateur. D autre part j' ai un chauffe eau solaire, pas de trace non plus, quoique a priori vous devez en tenir compte puisque vous demandez la conso annuelle

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, en effet nous n'avons pour l'instant pas intégré la possibilité de déclarer une production électrique au foyer.
Voir #624
