### ISSUE TITLE
Il me semble que le nb de km/h parcourus dépend du lieu de résidence ville ou campagne, le questionnaire n’en fait pas état donc la réponse est forcément biaisée.

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1037]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, NGC n'a pas pour but d'adapter le calcul en fonction du lieu de résidence. C'est un calcul brut, pas politique.
