### ISSUE TITLE
Consommation 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1039]
Bonjour,

Voici mon problème, j'essaie de faire attention au produit que j'achète tout en essayant de convaincre mon entourage qui lui a du mal à comprendre l'impact du cycle de vie d'un objet dans son ensemble. 
Actuellement j'essaie de faire comprendre l'impact des vêtements sur l'environnement.

J'ai remarqué que le prix est corrélé à la pollution dans le simulateur. Mais cela ne correspond pas forcément d'après les recherches faites. En effet pour une paire de chaussures plus respectueuse, mon entourage peut en acheter 3 paires qui on été fait à l'autre bout du monde en optimisant les coûts mais pas les émissions de co2. Idem pour les t-shirt, jean, etc.
Avec se calcul difficile de les faire changer d'avis 😐

Ne serait-il pas possible d'affiner en plus du prix le nombre approximatif de vêtement acheté par type? 
Par exemple en laissant la possibilité à l'utilisateur de saisir le nombre de pantalon, t-shirt, pull, chaussures, autres, etc.
Sûrement plus précis à mon avis de la pollution générée pour une personne addicte au shoping dans un magasin de fast fashion. 
J'ai vue que l'ademe à publié des pdf s'intitulant carnet de vie de jean, tshirt qui donne des chiffres sur le parcours des vêtements.

Merci, pour le travail que vous faites

Depuis la page : `https://nosgestesclimat.fr/documentation/divers/électroménager/robot-cuisine/présent`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, vous avez complètement raison ! Le modèle actuellement en ligne n'était qu'une grosse approximation en attendant mieux.

Voir #44. 

On s'y met au plus vite, après les autres urgences :) 

La difficulté, c'est que nous n'avons pas encore de module de saisie qui permet de faire +1 ou -1 sur un jeu de textiles. Mais ça viendra.
