### ISSUE TITLE
Quand ont réside dans un ehpad et qu’on fait sa part en éteignant derrière soi ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1040]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je ferme cette demande, trop peu explicite.
