### ISSUE TITLE
déplacements en bateau / ferry

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1041]
Bonjour,
Je réside en Corse, donc il m'arrive régulièrement de prendre le bateau pour me rendre sur le continent. J'imagine que les émissions de GES liées à ce mode de déplacement sont conséquentes, mais j'aurais bien aimé pouvoir comparer avec l'avion par exemple. Dommage que les kilomètres effectués en ferry ne soient pas comptabilisés !
Cordialement.

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, vous avez bien raison ! Nous en parlons souvent, mais il n'existe à notre connaissance pas encore de facteur d'émission pour le ferry. 

Pourquoi ? Notamment parce que c'est un calcul un peu compliqué vu qu'il y a à la fois du fret, des piétons, des voitures, et des services à bord. 

Nous y travaillons !
