### ISSUE TITLE
Scooter électrique 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1046]
Bonjour,
Je possède un scooter électrique et non thermique et le simulateur ne pose pas la question et par défaut estime que mon scooter est thermique

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour la remarque, très pertinente ! Il faut que nous intégrions cette variation dans les calculs.

**Comment by laem** [comment]
Voilà comment nous pouvons faire pour une 1ère version, en attendant une valeur dans la base carbone / une étude. 

Prendre le facteur d'émission de la voiture électrique, compact. https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=électique

Diviser par le poids d'une Zoé, a priori l'incarnation de la compact électrique. Multiplier par le poids d'un scooter électrique, en fonction du barème déjà établi pour le scooter (les appellations 150cc semblent rester). 

Choisir des scooters / motos représentatives : https://leblogduscooter.fr/scooter-electrique-meilleures-ventes. https://www.capital.fr/entreprises-marches/les-5-motos-electriques-les-plus-vendues-en-france-1366015. 

- [ ] trouver le poids des 2RM élec représentatifs
- [ ] implémenter une 1ère version du calcul

**Comment by laem** [comment]
Déplacé ici #966
