### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1049]
typo "consultez" au lieu de "consulter" sur cette page.
https://nosgestesclimat.fr/documentation/alimentation/viande-faible-empreinte

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/viande-faible-empreinte`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci :)
