### ISSUE TITLE
Reamarque

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1050]
Je n'ai pas vu la possibilité d'indiquer que je n'avais pas de voiture. J'ai cocher voiture électrique avec avec 0 km.

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, Si vous avez indiqué 0 km, vous n'auriez pas du voir les autres questions sur la voiture. Est-ce le cas ?

**Comment by laem** [comment]
La dernière PR inclut une notification qui explique le sujet :)
