### ISSUE TITLE
Petit déj

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1051]
Pour mon petit dej je fais des plats chauds avec des restes ou avec des lactofermentations, des soupes, des écrasés de haricots....aucune rubrique en ce sens dans votre calculateur

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/petit-déjeuner-annuel`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci, voir #453
