### ISSUE TITLE
Version entreprise 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1053]
Bonjour,

Serait-il possible de mettre en place un questionnaire spécifique sur les trajets domicile/travail? En tant qu'entreprise sur le calcul de l'empreinte carbone cela pourrait être pertinent.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by avenirclimatique** [comment]
Je ne pense pas qu'un questionnaire entreprise soit prévu. Pour information, les bilan carbone entreprise sont réalisés par des professionnels agréés, voir : https://www.associationbilancarbone.fr/tribune-non-un-bilan-carbone-realise-en-quelques-clics-nexiste-pas/
