### ISSUE TITLE
trajet maison  / école en voiture incontournable

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1055]
je ne vois pas comment éviter les trajets en voiture de mon domicile à l'école quand on habite une maison éloignée du bourg .Vélo impossible en raison d'une route dangereuse , vitesse excessive des véhicules et météo souvent peu clémente.

Depuis la page : `https://nosgestesclimat.fr/documentation/transport`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, oui c'est souvent compliqué. Mais nosgestesclimat n'est là que pour mesurer et proposer des solutions, qui sont certes peu accommodantes aujourd'hui des spécificités de chaque situation personnelle.
