### ISSUE TITLE
Test kilometrage

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1056]
Je demeure en campagne (15 km de la première ville) et fais moins de 9000 km par an. Je pense que le bilan carbone transport ne correspond pas...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, qu'est-ce qui cloche précisément, selon vous ?
