### ISSUE TITLE
Pouvoir corriger ou compléter ses réponses

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1060]
Bonjour,

Quand on commence le test, on ne sait pas du tout à quel type de question s'attendre, et donc quel renseignements ou documents avoir sous la main. Du coup il serait pratique de pouvoir revenir sur ses réponses et les corriger après coup (par exemple remplacer la consommation d'énergie par défaut par la réelle).

En tout cas, merci pour cet outil bien pratique ! 

Depuis la page : `https://nosgestesclimat.fr/documentation/logement/électricité/consommation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, c'est tout à fait possible ! Les réponses et l'avancement sont stockées dans le navigateur. Il faut simplement réutiliser le même navigateur (nous avons conscience que c'est une contrainte).

Je ferme au profit de #1075
