### ISSUE TITLE
Je roule en moto électrique

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1061]
Bonjour.
Comme de plus en plus d adeptes, je roule pour près de 50% de mes trajets en moto électrique afin de réduire le bilan carbone de mes trajets les plus habituels.
Diminution du poids et modifications du type de motorisation etant un facteur significatif il me semble surtout en France où le mix énergétique est peu carboné.
Dommage que ce ne soit pas pris en compte.

Cordialement.

Depuis la page : `https://nosgestesclimat.fr/documentation/transport`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Voir #966. Merci pour le retour :)
