### ISSUE TITLE
Modèles de petit déjeuner

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1062]
Bonjour,
En ce qui me concerne, je ne prends pas de petit déjeuner classique de type viennoiserie ou laitage/céréales, mais un petit déjeuner salé (ressemblant au déjeuner), avec insistance sur les fruits et les oléagineux.

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre retour ! (#453)
