### ISSUE TITLE
Question sur l'argent dépensé en vêtement 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1063]
Je ne comprends pas comment cette question peut être posée car l'argent dépensé dans l'achat de vêtements n'indique en aucun cas le nombre de vêtements, les tissus utilisés, le mode de fabrication ou les engagements écologiques des marques...

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
C'est tout à fait juste ! Voir #44
