### ISSUE TITLE
Zéro voyage en train

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1064]
Bonjour, plusieurs fois je n'ai pas pu cocher la case correspondante. Par exemple, je n'utilise AUCUN moyen de transport, je ne voyage pas, même inter-régions. J'ai dû choisir le moins pire à chaque fois, mais cela fausse mon bilan.
Concernant le nombre de repas quotidiens, pourquoi la norme est-elle fixée à 2 ? Ainsi que ce qui se trouve dans les assiettes ? Pour ma part, j'en prends 3 ou 4, comme beaucoup de personnes, notamment véganes, comme moi. Pour autant, je ne prends aucun des petits-déjeuners proposés...

Bref, j'arrive à 3 tonnes, mais je pense faire encore moins.

Je vous remercie pour votre travail, mais de mon point de vue cela reste encore trop normatif et fausse les résultats. :)

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
> Bonjour, plusieurs fois je n'ai pas pu cocher la case correspondante. Par exemple, je n'utilise AUCUN moyen de transport, je ne voyage pas, même inter-régions. J'ai dû choisir le moins pire à chaque fois, mais cela fausse mon bilan.

Il vous est possible de répondre 0 à toutes les questions, non ? 

Merci pour vos retours. Clairement, vous êtes en avance du point de vue de la métrique climat, notre interface n'est pas à la hauteur de votre cas d'utilisation :sweat_smile:
