### ISSUE TITLE
petit déjeuner très incomplet

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1067]
Je déjeune tous les matins : tartines de pain complet certaines beurrées, d'autres  à la purée d'amande. Rien ne correspond pourtant... Je ne bois pas de lait.

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci, c'est pris en compte dans #453
