### ISSUE TITLE
Petit déjeuner pas de case pour le salé 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1072]
De plus en plus de personnes mangent salé le matin au petit déjeuner. Je mange ce qui reste dans le frigo ou je me fais des œufs... 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci, c'est pris en compte dans #453
