### ISSUE TITLE
Que fait-il écrire dans les cases ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1074]
Je ne comprends ce qu’il faut ecrire dans les champs de texte. Je suis sur téléphone. Il n’y a pas en choix.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, sur quelle case en particulier ? Quelle est la question ?

**Comment by laem** [comment]
Je ferme en attendant un retour précis, n'hésitez pas à répondre quand même pour relancer la discussion :)
