### ISSUE TITLE
gpl

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1076]
Bonjour,
vous n'incluez pas la possibilité de rouler au GPL. Cela contribue pourtant à réduire notre empreinte, certes moins que le vélo, mais tout de même...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, en effet, merci pour le retour. Nous avons considéré que c'était / ce serait dans le futur une part mineure du parc automobile, peut-être à tort ?

**Comment by laem** [comment]
Merci, voir #445
