### ISSUE TITLE
Sur l'age des appareils electroniques

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1081]
Dans la partie habillement on prend en compte le fait que ce soit de la récupération. Y a-t'il un moyen de faire entrer cela dans la partie des appareils et des objets manufacturés. Personnellement je ne peux pas dire quel est l'age d'un pc portable récupérè ni d'ailleurs donner un age à un pc fixe où des pièces telles que la carte graphique a été changée ou s'il y a des pièces de récup dedans.

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour le retour. En effet, nous allons enlever les questions d'âge des appareils, au profit d'un âge moyen national + une quantification globale de l'effort pour faire durer le matériel :)

**Comment by laem** [comment]
Voir #934
