### ISSUE TITLE
je souhaite faire mon bilan carbone

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1082]
je souhaite faire mon bilan carbone mais je ne trouve pas où mettre mes réponses personnelles : âge, appartement, consommation etc...
Ceci, même en cliquant sur tout ce que je trouve...
Merci de me répondre de manière précise.

Depuis la page : `https://nosgestesclimat.fr/documentation/logement/électricité/consommation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by martinregner** [comment]
Pour ce faire, il faut débuter le test directement sur https://nosgestesclimat.fr
