### ISSUE TITLE
Biogaz

### ISSUE THREAD

**Issue by Radack08** [datagir/nosgestesclimat#1090]
Bonjour, voilà j'ai remarqué que lors du choix du type de chauffage utilisé, quand on choisi gaz on n'a pas la possibilité d'indiqué si il est ou non BIO, je suis chez ILEK avec un gaz produit tout prêt de chez moi et pour le calcul ça n'a aucune incidence sur le résultat final de mon bilan, c'est je trouve dommage, avez-vous prévu d'intégrer cette différence ? Merci et bravo pour le boulot que vous faites !

**Comment by sfoutrier** [comment]
J'ai fait pareil pour mais chez Ekwateur.
Je n'arrive pas à trouver de sources non-marketing pour valider ou non ce choix. Si quelqu'un avait des informations quand à la différence d'impact sur l'ACV du gaz naturel vs biométane (peut-être en pointant les bons et mauvais élèves), ce serait extrèmement utile !

**Comment by laem** [comment]
Merci pour le retour ! 

Ce n'est actuellement pas possible :/ Nous n'avons pas encore les facteurs d'émission de ces offres. 

Voir #4
