### ISSUE TITLE
questionnaire impossible à remplir pour le numérique

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1093]
je n'ai pas pu terminer le questionnaire, dans la partie numérique, plein de cases étaient précochées (?) et du coup, on ne sait plus quoi faire. trop casse-pied de tout refaire depuis le début. dommage ! 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci, c'est noté dans #934
