### ISSUE TITLE
Viande vs végétarien ? 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1097]
Bonjour,
Dans les actions qui sont proposées pour agir, je note que manger de la viande seulement le we =-33kg CO2
Mais devenir végétarien =-7.5 kg CO2
Cela m'interroge ? Devrais je alors revoir mon alimentation ? 
Où bien y aurait il une erreur ? 
Merci pour votre réponse. 

Depuis la page : `https://ngc.time-planet.com/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, nous avons corrigé dernièrement certains bugs sur les actions alimentation, êtes-vous toujours confronté à ce problème ? 
Je ferme l'issue pour le moment.
