### ISSUE TITLE
vous utilisez de fausses données pour l'alimentation boeuf egal veau ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1101]
bonjour

j'ai fait le test, merci pour cette initiative.

Je passe le faite que le bois émet plus de CO2 que l'électricité pour le chauffage!!

Mais dire que le boeuf émet 35 kg de CO2 par kg comme le veau je trouve que vous voulez minimiser l'impacts du logement et de la voiture... J'ai arrêté de manger du veau quand j'ai découvert son impact en CO2 et je mange occasionnellement du boeuf et plus du tout de laitage. Mais avec vos approximations j'ai l'impression (fausse bien sûr) que j'émet autant de CO2 au repas  qu'en voiture et qu'en chauffant.

Merci de corriger et de faire un repas veau agneau .... et sortir le boeuf de cette case

Belle journée

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/plats/viande-2`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Nous utilisons les données agribalyse. 

Les émissions du boeuf sont très élevées. On pourrait en effet faire une séparation plus fine des viandes, mais ce n'est pas l'objectif actuel, qui est justement de garder une certaine simplicité dans la saisie. 

cc @jeremiecook
