### ISSUE TITLE
Connection is not secure

### ISSUE THREAD

**Issue by nirgal** [datagir/nosgestesclimat#1102]
Quand on se connecte sur https://nosgestesclimat.fr/ on a un logo de danger à gauche de l'url (tor browser).
Quand on clique le point d'excalamation, on a un message "Connection is not secure"

J'ai tracé le problème sur le télécharment de l'image
http://www.ademe.fr/sites/all/themes/custom/ademe/logo.png

Actuellement, firefox donne l'avertissement:

> Connection to this site is not private. Information you submit could be viewed by others (like passwords, messages, credit cards, etc.). Your connection is not private and information you share with this site could be views by other.

Merci de passer à https.

**Comment by laem** [comment]
Ça me semble être résolu :) 

https://github.com/datagir/nosgestesclimat-site/blob/e495bd78f2b68c22115b71da2ed26936b16d5ba8/source/sites/publicodes/Landing.js#L65

**Comment by Clemog** [comment]
Fixed : PR https://github.com/datagir/nosgestesclimat-site/pull/390
