### ISSUE TITLE
Carburant auto

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1105]
Je ne vois pas le GNV dans les choix de carburants. Je roule au BioGNV qui est le carburant le moins polluant et le moins émetteur de CO2 fossile. 

Depuis la page : `https://ngc.time-planet.com/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour ! On en parle ici : #445 :)
