### ISSUE TITLE
Empreinte carbone de déchets erronée ? 

### ISSUE THREAD

**Issue by tuppi-ovh** [datagir/nosgestesclimat#1108]
La simulation montre ceci : 

![image](https://user-images.githubusercontent.com/59368736/127913886-e7479f28-36d9-4eb7-856f-16c17c127b66.png)

On voit l'utilisation du nombre `193`. Ce même nombre est référencé sur le site [jancovici.com](https://jancovici.com/changement-climatique/les-ges-et-nous/combien-de-gaz-a-effet-de-serre-dans-notre-poubelle/) comme `kg equivalent carbone par personne` :

![image](https://user-images.githubusercontent.com/59368736/127914187-410aeea4-0008-4112-9b33-bddf48d301f1.png)

Est-ce qu'il y a une erreur dans le calcul ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Voir PR #1110 pour la mise à jour des quantités de déchets avec l'étude MODECOM 2017

**Comment by tuppi-ovh** [comment]
ok, équivalent carbone est converti en équivalent CO2 avec le facteur `44/12`. L'issue à rejeter. Désolé :)
