### ISSUE TITLE
Logement : demander l'âge

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#111]
Je me rends compte que sur mon logement l'impact à 90% est constitué par sa construction. Habitant un immeuble de 1800, je trouve ça trop car amorti depuis longtemps par rapport à des maisons pavillonaires qui ont une durée de vie de 50 ans max.

**Comment by laem** [comment]
Oui, très bonne remarque, c'est un problème évident du calcul, à améliorer en demandant l'âge du logement et en estimant une empreinte d'entretien (ravalement, changement des ardoises du toit, etc.).
