### ISSUE TITLE
objectif

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1114]
Bonjour, 

Par curiosité, j'ai calculé mon empreinte carbone et devant mon résultat, je me demande "et alors?". Je m'explique: dans mon cas j''étais entre 6 et 7 t CO2, donc je sais que je suis sous la moyenne des français. Le problème est que je n'en sais pas plus. Est que c'est une bonne empreinte carbone? Quelle serait une empreinte carbone idéale? Non idéale mais atteignable? Je sais que ce test n'est qu'une estimation à but informatif, mais donner un objectif, même vague ou sous forme de conseil, pourrait motiver quelques personnes à tenter d'atteindre cet objectif. Parce qu'une information seule, sans suggestion de quoi en faire, n'apporte pas grand chose.

Donner un objectif, cela pourrait être fait tout simplement en suggérant à la personne qui a fait le test de le passer à nouveau en répondant cette fois non pas en fonction de son comportement actuel mais en fonction des comportements qu'elle souhaiterait adopter. On obtiendrait donc un score à atteindre. Sans suggestion de votre part, peu de gens vont spontanément penser à le faire.

Pourquoi est important?
 
En psychologie, la théorie des buts, notamment celle de Locke et Latham (https://en.wikipedia.org/wiki/Goal_setting) nous dit qu'une performance est meilleure si l'objectif est mesurable (votre test), précis (d'où l'importance du retest) et atteignable.
Si on me disait: "Bravo, maintenant l'an prochain essaie d'avoir une empreinte carbone de 4 t CO2" (un exemple au hasard), je ne saurais pas par où commencer et si l'objectif n'est pas atteignable, je laisserais vite tomber. En revanche, grâce au retest: 1) on s'assurerait que l'objectif est atteignable car individualisé et choisi, 2) on aurait mentionné dans les réponses les choses à faire pour atteindre cet objectif, donc on saurait concrètement quoi faire (exemple: 2 repas végétariens en plus par semaine et réduire de moitié les trajets en avion). Un petit récapitulatif des objectifs à la fin du retest (par rapport au test original) peut aider à résumé tout cela pour rendre l'information saillante pour la personne ayant fait ce 2nd test.

Enfin, sur la base du volontariat, vous pourriez proposer aux personnes qui ont fait le 2e test de laisser leur adresse email pour qu'un an plus tard, elles reçoivent un courriel leur suggérant de repasser le test pour voir si elles ont atteint leur objectif, et le cas échéant, d'en fixer un nouveau plus atteignable.

Je sais que peu de gens vont aller au bout du 2e test, adopter des changements de comportement en vu d'atteindre leur objectif, et repasser le test un an après pour faire le bilan de leurs résolutions. Mais peu de gens c'est mieux que quasiment personne, et cela donnerait une utilité à l'information que vous nous donnez.

En espérant que vous avez trouvé l'idée intéressante et en vous remerciant pour toutes les informations apportées sur le site.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour,

> Le problème est que je n'en sais pas plus. Est que c'est une bonne empreinte carbone? Quelle serait une empreinte carbone idéale? Non idéale mais atteignable?

Nous avons mis en retrait la valeur moyenne française, car elle est moins pertinente que les objectifs carbone, largement mis en avant dans la nouvelle version de l'écran de fin :) 

![image](https://user-images.githubusercontent.com/1177762/195036655-cb52b08e-5d13-4f3f-a741-b4dfc94d0a56.png)

> mais donner un objectif, même vague ou sous forme de conseil, pourrait motiver quelques personnes à tenter d'atteindre cet objectif. Parce qu'une information seule, sans suggestion de quoi en faire, n'apporte pas grand chose.

L'écran action est là pour ça :) Faire repasser le test, nous y avons pensé, mais c'est très long. Nous avons préféré le parcours nosgestesclimat.fr/actions. 

> Enfin, sur la base du volontariat, vous pourriez proposer aux personnes qui ont fait le 2e test de laisser leur adresse email pour qu'un an plus tard, elles reçoivent un courriel leur suggérant de repasser le test pour voir si elles ont atteint leur objectif, et le cas échéant, d'en fixer un nouveau plus atteignable.

Oui c'est une suggestion très intéressante. Voir les discussions sur https://github.com/datagir/nosgestesclimat-site/issues/400. 

Merci en tout cas pour vos suggestions, et désolé pour notre réponse tardive.
