### ISSUE TITLE
Prise en compte de la gestion des déchets alimentaires

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1116]
Bonjour, il n'y a aucune question sur notre gestion personnelle des déchets alimentaires. Poubelle, compost ou alimentation animale par exemple. Chez nous rien d'alimentaire n'est jeté à la poubelle, si les animaux ne s'en chargent pas le compost est là. Dommage car vous comptez ces déchets d'office quand certains n'en ont aucun.

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/déchets`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Traité dans #1415 :)
