### ISSUE TITLE
Campagne ou ville

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1118]
Pourquoi n'est il pas demandé le lieu de vie ? En montagne, la voiture individuelle reste le seul moyen de transport : pas de car, bus, ou autres... 

Depuis la page : `https://nosgestesclimat.fr/documentation/transport`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je ferme au profit de #1309
