### ISSUE TITLE
Conseils de gestes pour réduire son empreinte

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1119]
Bonjour, à la fin de la simulation, parmi les gestes qui me sont proposés, j'en applique quelques uns, mais il m'est impossible de les ajouter à ma simulation (rénovation du logement, utilisation de Led, réduire le chauffage par exemple). C'est dommage, car ma simulation n'est donc pas précise...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Plus d'actualité à priori, je ferme
