### ISSUE TITLE
La viande (élevage), les déchets ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#112]
Bonjour étonnée de voir la question si rapidement éludée: en plus de consommer peu de viande rouge (< 1 fois par semaine), j'ai diminué considérablement les quantités. J'achète bio les oeufs et la viande ou au moins local, autant que possible.  
Les déchets : à force de changements, je n'envoie dans la poubelles des ordures ménagères que 50 litres par mois.  (Composteur, achats en vrac...).  Je rejette tout ce qui est suremballé.  Ca compte sûrement?
Mais bon, je vais chercher encore pour arriver au 2 tonnes puisque je suis quand même à 7.  Merci à vous.

**Comment by laem** [comment]
Voir pour le compost #140 
Voir pour les autres questions sur l'alimentation le travail en cours #71

**Comment by Clemog** [comment]
Traité à priori :)
