### ISSUE TITLE
Pas clair

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1121]
On n'arrive pas en fin de parcours à savoir si on fait bien ou pas.

Depuis la page : `https://nosgestesclimat.fr/documentation/numérique/téléphone/présent`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je ferme, commentaire trop vague, et travail déjà entamé pour revoir l'écran de fin.
