### ISSUE TITLE
Carburant GPL

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1124]
Bonjour,
Je ne comprends pas pourquoi le type de carburant ne rentre pas en ligne de compte, j'utilise du gpl en permanence et celui-ci est fabriqué à partir de déchet recyclé, j'ai donc un bilan plus favorable que du SP-98 énergie fossile.

Depuis la page : `https://nosgestesclimat.fr/documentation/transport`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci, voir #445
