### ISSUE TITLE
Prb partage résultats

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1127]
Bonjour,
Le bouton "Partager mes résultats ne fonctionne pas".
Merci 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci pour le retour.

**Comment by laem** [comment]
Je n'arrive pas à reproduire le problème, sur Firefox/Chrome bureau comme Firefox/Chrome Android.

**Comment by laem** [comment]
Testé aussi sur iphone SE avec Safari, et sur Mac High Sierra Safari.

Je suspecte un problème d'UX, à creuser. Je suspecte que l'utilisateur pense que l'icone bleu ci-dessous est un bouton

![Capture d’écran du 2021-08-23 18-01-53](https://user-images.githubusercontent.com/1177762/130479682-a45f90b4-2992-45b8-82b2-c02ece8d9678.png)

**Comment by laem** [comment]
Trouvé :)  https://github.com/datagir/nosgestesclimat-site/issues/321
