### ISSUE TITLE
Données ponctuelles

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1133]
Il est difficile de calculer certaines données sur une durée précise et récurrente lorsque celles-ci sont ponctuelles. Par ex: je ne prends presque jamais l'avion, mais je l'ai pris à deux reprises sur des vols longs courriers (>18 heures de vol). Une évaluation de nos consommations ponctuelles mis en lien avec notre âge me semble plus précis pour analyser notre impact écologique.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci, nous avons ajouté une instruction pour l'avion :)
