### ISSUE TITLE
Modification des réponses des vols moyens et longs courrier imppossible

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1137]
Il n'est pas possible de modifier le nombre de kilomètres parcourus en avion pour les moyens et longs courriers une fois que l'on a répondu à la question. Ces catégories ne sont pas disponibles dans la liste de questions déjà répondues. 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je n'arrive pas à reproduire le problème. J'ai bien le choix de modifier ces saisies. 

![Capture d’écran du 2021-08-23 16-04-06](https://user-images.githubusercontent.com/1177762/130461052-d39c2fb2-377a-4795-b7d9-e458c2696298.png)

Je ferme en attendant de nouvelles informations sur ce qu'il s'est passé.
