### ISSUE TITLE
Saisie de 2 sources d'énergies de chauffage pas facile ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1138]
Il n'y a pas la possibilité d'entrer 2 types de chauffage, mon exemple : bois et en appoint, clim réversible.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Si c'est possible. Il suffit de répondre "oui" à bois, tout en renseignant des kWh d'électricité. La clim ne consomme que de l'électricité.

Nous pourrions peut-être proposer une mosaïque de sélection des modes de chauffage en amont des questions sur l'énergie de la maison ?

**Comment by laem** [comment]
C'est fait :)
