### ISSUE TITLE
Repas

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1141]
Preconiser un seul repas de viande par jour quand on en a indiqué 4 par semaine ...

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/petit-déjeuner-annuel`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Résolu normalement !
