### ISSUE TITLE
Question concernant l'impact du nombre d'occupants d'un logement

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1143]
Bonjour,
J'ai une question concernant l'impact du logement, et plus particulièrement sur l'impact du nombre d'occupants d'un logement sur l'empreinte individuelle.
J'ai constaté les résultats suivants, pour un logement des années 70 non éco-construit chauffé au gaz et toutes choses égales par ailleurs:
- Logement de 23m2, occupé par 1 personne = 3,9t CO2
- Logement de 70m2, occupé par 3 personnes = 1,5t CO2 par personne
- Logement de 70m2, occupé par 1 personne = 4,4t CO2
Comment expliquer de telles disparités? 
Notamment que le rapport m2/personne soit si défavorable au logement individuel, et que le nombre de m2 en absolu ait si peu d'impact.
Merci

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JeanPaulGrange** [comment]
En effet, J'ai aussi créé le ticket #1300 (sans avoir vu celui-ci) : Comment faire le calcul pour une famille ou un couple ?

**Comment by laem** [comment]
Oups, je vois cette issue bien trop tard. Pour comprendre comment le calcul du logement est fait, il suffit d'aller sur la documentation, ici précisément : https://nosgestesclimat.fr/documentation/logement

Si vous avez fait votre simulation, la documentation sera personnalisée avec vos chiffres ;) 

@JeanPaulGrange je ferme cette issue, en gardant la votre, la #1300
