### ISSUE TITLE
Achat de seconde main

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1144]
Bonjour,
Dans le volet vêtements, on ne peut pas préciser si on achète neuf ou d'occasion ce qui a mon sens pourrait impacter le résultat.
Bonne journée 

Depuis la page : `https://nosgestesclimat.fr/documentation/divers/textile`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by realwalkerslife** [comment]
C'est une question compliquée. Il est à mon sens trop simpliste de penser que la seconde main n'a aucun impact. Ce qui compte c'est la durée totale d'utilisation de l'objet. Exemple : un utilisateur 1 achète neuf un téléphone et le fait tenir 5 ans ou un utilisateur 2 achète un téléphone d'occasion (de 2, 5 ans) et le fait tenir 2,5 ans.
Comment affirmer que l'utilisateur 2 n'a pas d'impact alors qu'il devrait avoir la moitié de ce qu'à eu l'utilisateur 1? En gros il faudrait appliquer un prorata, mais ça demande pas mal de suppositions.
Ceci devrait s'appliquer à tout les objets avec la complication qu'on ne sait pas combien de temps l'objet est utilisé.

**Comment by Clemog** [comment]
Merci pour vos retours. Nous travaillons activement sur ce sujet mais la quantification et l'attribution des émissions d'un achat de seconde n'est pas évidente. Pour le moment nous conseillons de ne pas compter vos achats de seconde main dans la composition de votre dressing. Voir PR #1004 et #1005.
