### ISSUE TITLE
Scooter électrique 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1147]
Bjr. Je fais 20000 km par an en scooter électrique.  Impossible de le faire prendre en compte dans le calcul. Obligé de tricher avec voiture mais compte faussé avec le nombre de passagers. 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci ! Voir #1046
