### ISSUE TITLE
Mode conférence

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1150]
Bonjour,
Je viens d'essayer le mode conférence avec des amis car je souhaiterais lancer un défit par service dans mon entreprise pour challenger nos collaborateurs sur leurs déplcaments domicile-travail ainsi que sur l'écoresponsabilité en général.
Petit problème : la mise à jour du bilan carbone du groupe ne se fait pas... et je ne vois qu'une personne connectée (moi) alors que d'autres le sont sur la même conférence...
D'avance merci pour votre aide
J'espère pouvoir utiliser rapidement cet outil en entreprise :)
Bonne journée
Cdlt,

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, est-ce que votre entreprise interdit certains noms de domaine / certains protocoles internet comme le pair-à-pair (P2P) ? 

Pour le savoir, réessayez hors du réseau de l'entreprise ou plus simplement via vos téléphones en 4G. 

Nous allons bientôt sortir une version qui fonctionne en entreprise.
