### ISSUE TITLE
Séparer la question zéro déchets en plusieurs

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1152]
C'est difficile d'estimer soi-même sans lire de critères de cette note "oui" / "en partie" / "non".

On pourrait demander : 
- composte donc presque plus de poubelle non tri ? 
- évitez le plastique ? 
- etc.

Voir notamment #1110 (qui ne résout pas mais améliore le calcul)

**Comment by Clemog** [comment]
Traité dans #1415, pistes d'améliorations dans #1443
