### ISSUE TITLE
Lien mort vers publicode "Mutualiser son logement "

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1153]
Le lien vers le publicode pour "Mutualiser son logement " est mort sur /documentation/logement/mutualiser

Depuis la page : `https://nosgestesclimat.fr/documentation/logement/mutualiser`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je ne suis pas sûr de comprendre le problème. Je ferme en attendant plus d'informations.
