### ISSUE TITLE
Biogaz

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1155]
Je me chauffe au gaz que j’achète auprès d'un fournisseur qui propose une offre 100% bio méthane. comment prendre en compte cela dans le calcul de mon bilan carbone ? 

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/avion/long-courrier/heures-de-vol`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Ce n'est actuellement pas possible :/ 

Voir #4
