### ISSUE TITLE
Pourquoi les officiels ne réduise pas leur voyage et ne pas taxer les gros  bateaux 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1157]
Depuis la page : `https://nosgestesclimat.fr/documentation/services-publics`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Ce genre de question déplacée pourrait être résolu par #3
