### ISSUE TITLE
Lieu de vie

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1158]
Pourquoi le lieu où je vie (la campagne) n'est elle pas pris en compte ? 

Depuis la page : `https://nosgestesclimat.fr/documentation/logement`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Parce que ça n'a aucun impact sur le calcul. 

Nous pourrions faire varier l'estimation de l'empreinte des services publics en fonction du lieu d'habitation, mais il n'est pas dit que ce soit en faveur du milieu rural, qui dispose certes de moins de services publics, mais d'une mise en commun bien moindre de ces services.
