### ISSUE TITLE
Deux roues électriques

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1163]
Il est proposer dans le choix des véhicules les voitures électriques mais je n'ai pas vu ce choix pour les 2 roues alors que je possède un deux roues électriques

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/deux-roues-thermique/usager`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre remarque, nous travaillons sur le sujet (voir #966 )
