### ISSUE TITLE
Formulation question achat vêtement

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1165]
Bravo pour ce simulateur. 
Peut-être indiquer directement dans la nouvelle question sur les vêtements le caractère "neuf" du vêtements?
C'est expliqué dans le "i" mais peut-être pas clair à la première lecture.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour. Nous travaillons sur la différence entre vêtements neufs et occasion ici, ce qui rejoint votre proposition concernant la formulation de cette question :) (ici : #1004 )
