### ISSUE TITLE
Contrat de gaz vert non pris en compte?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1166]
J'utilise un contrat de gaz vert (= soutien de biométhane produit en France), cette possibilité peut-elle être prise en compte dans le modèle ? (J'ai vu l'explication pour l'électricité verte d'ores et déjà)

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre retour ! (Voir #1297)
