### ISSUE TITLE
réponses précochées 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1168]
bonjour,
vous avez précoché certaines réponses que l'on ne peut pas décocher par ex dans numérique que possédez-vous.. : "tv", "téléphone", "ordi"... sont forcément cochés / de même pour les trajets en trains : on ne peut pas non plus mettre "zéro km" ... 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, normalement, vous pouvez bien décocher ces réponses : il suffit de cliquer sur la croix :)

**Comment by Clemog** [comment]
Je ferme au profit de https://github.com/datagir/nosgestesclimat-site/issues/574
