### ISSUE TITLE
petit déjeuner végétalien 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1170]
Bonjour il n’existe pas de version végétalienne du petit déjeuner 

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/petit-déjeuner`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci, remarque prise en compte ici : https://github.com/datagir/nosgestesclimat/issues/453.
