### ISSUE TITLE
proposition petit déjeuner

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1171]
Je ne trouve pas mon petit déjeuner dans vos propositions. Moi je suis plutôt oeuf (protéines) et fruits + féculents
Merci

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci, c'est pris en compte ici : https://github.com/datagir/nosgestesclimat/issues/453
