### ISSUE TITLE
Consommation alimentaire 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1172]
Je suis déçue par le questionnaire, car il n’y a pas assez de détails, par exemple sur le repas. Le questionnaire se limite à demander le type de repas, mais pour la viande précisément ne demande pas le poids consommé. Or, je ne retrouve pas dans la consommation moyenne des français, je consomme à peine 80 gr quand je mange  de la viande. Rien à voir avec une part de 150 ou 200 gr. Donc mon profil est faux. Par contre je consomme le plus local et bio possible, et là, rien sur l’impact des transports amoindri. Rien non plus sur la consommation de médicaments, qui peuvent venir de loin et sont 100% chimiques, donc qu’on retrouve par élimination, dans l’eau. Etc....

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Quelques éléments de réponse ici : https://github.com/datagir/nosgestesclimat/issues/961 :)
