### ISSUE TITLE
Carburation biomethane 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1174]
Vous proposez les véhicules hybrides et électriques mais il existe aussi les véhicules gaz, qui, avitaillés en biomethane, ont l'impact environnemental le plus faible.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre remarque, voir #445
