### ISSUE TITLE
Comment reprendre et affiner lasaisie svp merci

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1175]
Depuis la page : `https://nosgestesclimat.fr/documentation/logement/électricité/consommation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Je n'ai pas bien compris la remarque. Aujourd'hui, il est possible de revenir sur une question directement via la page Profil.
