### ISSUE TITLE
Forfaits mobiles / internet

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1176]
Pourquoi ne pas tenir compte des forfaits mobiles en utilisant la base carbone de l'ADEME : 

Achats de service -> Ratios monétaires -> Services : télécomunications :
0.170kgCO2e/euro. 

Cela permettrait de tenir compte de l'utilisation des télécoms. 

Cordialement. 

PS : A faire aussi pour le Wifi

Depuis la page : `https://nosgestesclimat.fr/documentation/logement/électricité`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
C'est pris en compte dans les services sociétaux :)
