### ISSUE TITLE
BOISSON alcool

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1177]
bonjour pour quelle raison on préconise de boire de la bière locale plutôt que du vin local par exemple, en quoi cela est-il plus émetteur de Co2 ?

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/boisson/alcool/litres`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, ce n'est qu'un exemple ;)
