### ISSUE TITLE
Ecran blanc à la fin de la simulation

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1178]
Hello, 
je viens de faire une simulation sous Firefox 92 / MSWindows 10
et sous Google Chrome 93 / MSWindows 10
A chaque fois, j'ai un écran blanc à la fin de la simulation, aucun résultat n'est visible, même en rafraîchissant la page du navigateur.
Donc très déçu ...
Bonne journée quand même.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Squix** [comment]
Même problème ici

**Comment by laem** [comment]
Désolé pour ce gros bug, je le corrige.
