### ISSUE TITLE
Je n'ai pas bien compris comment on change les chiffres proposés 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1183]
Je crois ne pas avoir compris le mode d'emploi du questionnaire, surtout à l'endroit où il semble Qu'on peut changer les chiffres.

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/plats/végétalien/nombre`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Idem à cette issue visiblement https://github.com/datagir/nosgestesclimat/issues/1268.
