### ISSUE TITLE
Energie électrique renouvelable et biogaz

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1187]
Bonjour. merci pour votre calculateur qui est top !
Une remarque sur les énergies électriques vertes et bio-gaz : je comprends votre réponse. Néanmoins, si tous les français souscrivaient un contrat énergie verte, cela pousserait les producteurs à augmenter leurs offres. Et c'est dommage que l'on ne soit pas "récompensé" sur ce poste par le simulateur. Je vais resouscrire du gaz fossile ... ;-). 

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre retour ! Vous pouvez consulter la [FAQ](https://nosgestesclimat.fr/contribuer) pour la question de l'énergie verte. Pour le biogaz, nous travaillons sur le sujet : #1297
