### ISSUE TITLE
Empreinte au km électrique

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1189]
Bonjour,

Je n'arrive pas à comprendre d'où vient la valeur de 0,02 kgCO2e / km pour l'empreinte au km d'un véhicule électrique. 
Selon la source : https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=voiture
On trouve entre 0,09 et 0,139 kgCO2e / km mais rien qui se rapproche de 0,02 kgCO2e / km. Est-ce une erreur ou est-ce que j'ai "raté" quelque chose ?

Bien cordialement,
-- 
Nicolas

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/voiture/électrique/empreinte-au-kilomètre`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour. Vos recherches sont les bonnes ; seulement nous considérons la phase amont de ce facteur d'émission pour ne pas compter 2 fois la fabrication du véhicule (que nous calculons par ailleurs à partir d'autres questions posées).
Exemple: 
![image](https://user-images.githubusercontent.com/55186402/147114150-57ab7f2b-43fa-4ba7-b7ff-794addca0dce.png)
