### ISSUE TITLE
Trainés de condensation

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1190]
Bonjour, 

Les valeurs d'émissions concernant l'avion semblent indiquer que les trainées de condensation sont considérées (0,23kgCO2e/km pour un court courrier là où la valeur ADEME sur ce même type de vol avec trainées est de 258gCO2e/km et "seulement" 141gCO2e/km sans les trainées. 

Or, cet impact est souvent négligé, à tord je trouve mais pour autant, il n'y a pas de consensus sur la méthod de calcul et donc la valeur considérée. Ce choix d'inclure l'impact des trainées est-il bien assumé et comment justifier que cette valeur est la plus représentative? 

Aussi, pourquoi ne pas avoir pris la valeur de la base carbone ADEME?

Merci

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/avion/court-courrier/empreinte-par-km`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour le retour. En effet, nous utilisons les valeurs de la base carbone / monimpacttransport (qui sont plus ou moins les mêmes) avec trainées.

Les sources sont précisément citées ici : https://github.com/datagir/nosgestesclimat/blob/master/data/transport/transport.yaml#L432

Pour le sujet avec / sans traînées, le document de référence semble être celui-ci, paru cette année : https://librairie.ademe.fr/mobilite-et-transport/4617-etat-de-l-art-de-la-recherche-scientifique-sur-l-impact-climatique-des-trainees-de-condensation-des-avions.html

Il montre la complexité de la chose, et le potentiel de sous-estimation.
