### ISSUE TITLE
J’ai une voiture perso qui fonctionne au biocarburants ( kit bioéthanol ) zéro rejet de co2 que de la vapeur d’eau 😜

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1191]
Prix moyen du E85 0,65 Cts ,a quand des voitures propres ?car le problème de l’électrique ? Le recyclage ♻️ pas top  

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, nous en parlons ici : https://github.com/datagir/nosgestesclimat/pull/1396
