### ISSUE TITLE
Transport en bateau

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1192]
Bonjour,
Le simulateur ne permet pas de prendre en compte des trajets en bateau (notamment les car ferry entre la Corse et les ports méditerranéens). Existe-t-il une équivalence permettant de convertir ces trajets en bateau en trajets en avions ?
Merci.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, vous avez bien raison ! Nous en parlons souvent, mais il n'existe à notre connaissance pas encore de facteur d'émission pour le ferry.

Pourquoi ? Notamment parce que c'est un calcul un peu compliqué vu qu'il y a à la fois du fret, des piétons, des voitures, et des services à bord.

Nous y travaillons !

Je ferme au profit de #612
