### ISSUE TITLE
Remarque - correction / ajustement difficile

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1193]
Bonjour, il est très difficile de corriger ou d'ajuster les informations rentrées pour chaque catégorie. Exemple, la consommation de gaz ne correspond pas au montant mis en fonction de la facture mais je ne parviens pas à le changer. 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour le retour, il me semble que le bug n'existe plus. Vous pouvez rentrer directement la consommation ou bien passer par l'aide à la saisie en rentrant le montant de votre facture mensuel (qui permet d'estimer la consommation à partir d'un facteur par défaut). Au final c'est bien la consommation qui est prise en compte et non la facture.
