### ISSUE TITLE
Type de petit-déjeuner

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1194]
Aucun petit-déjeuner ne correspond au mien. Vous pourriez peut-être inclure un petit-déjeuner type salé : pain beurre, fromage, œufs, jambon ou type healthy ?
Bonne journée !

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Pris en compte ici : https://github.com/datagir/nosgestesclimat/issues/453
