### ISSUE TITLE
gnv et biogaz

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1200]
bonjour 
j'ai 2 voitures partagées avec ma femme une familiale suv diesel et une fiat punto bicarburation gnc/essence 
j'aurais voulu pouvoir préciser le kilométrage pour chaque et indiquer que je peux rouler au biogaz (biomethane, bilan CO2 faible) accessible dans certaines stations. 

Merci.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour !
Pour les biocarburants, on en parle ici : https://github.com/datagir/nosgestesclimat/issues/445.
Concernant le partage de la voiture, une discussion autour d'un mode "foyer" est en cours ici :https://github.com/datagir/nosgestesclimat/issues/113 et là https://github.com/datagir/nosgestesclimat-site/issues/348.
