### ISSUE TITLE
Vacances : caravane et camping car

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1206]
À ne pas confondre avec #857, ou le véhicule *remplace* le logement. 

Ici on parle d'équipement qui complètent un logement. Un peu plus comme une maison secondaire finalement. 

L'empreinte d'une caravane est double : la construction de l'objet toujours plus sophistiqué + la consommation supplémentaire sur la route. 

Idem avec le camping car, qui pourrait s'apparenter à une deuxième très grosse voiture.

**Comment by Benjamin-Boisserie-ABC** [comment]
Je propose qu'entre la question sur la consommation du véhicule et celle sur le scooter on pose la question suivante : 
- Avez-vous une caravane ou un camping car ? (avec une mosaïque à cocher avec ces deux options) - la location de van pour 2 semaines de road-trip est mise de coté pour l'instant. 

Si caravane = oui 
- on rajoute l'impact de sa construction. _Quelle valeur ? Quid amortissement ?_
- on considère une valeur en % des km parcourus (choisi arbitrairement) fait avec la caravane et on augmente la consommation du véhicule sur ces X % ? Quelle surconsommation appliquée ?

Si camping-car = oui 
- on rajoute l'impact de sa construction. _Quelle valeur ? Quid amortissement ?_
- la question de la motorisation est inutile selon moi car les camping-car électriques n'existent pas et les vans électriques sont encore à l'état de [prototypes](https://www.autoplus.fr/camping-car/camping-cars-electriques-avenir-lointain-536025.html#item)
- on pose la question sur le nombre de voyageurs
- on pose la question sur la consommation du véhicule
- on pose la question des km roulés car la 1ère question précise "la distance parcourue **en voiture**"

Remarques générale : 
- Considère-t'on les vans dans cet rubrique. Je pense qu'il faut--> à expliquer dans la bulle info

**Comment by Clemog** [comment]
Travail réalisé dans #1317
