### ISSUE TITLE
Nous prduisons aussi 13000KWH d'électricité photovoltaïque et disposons d'un potager

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1237]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Nous travaillons à la prise en compte d'actions concernant le potager (https://github.com/datagir/nosgestesclimat/issues/695).
Concernant, l'électricité photovoltaïque, c'est un cas particulier que nous ne prenons pas en compte. Il est possible dans le simulateur de ne pas renseigner de consommation électrique afin de traduire l'autosuffisance mais l'impact de la construction et de l'installation des panneaux ne sera pas pris en compte ce qui sous-estimera légèrement l'empreinte carbone finale.

**Comment by Marc-marc-marc** [comment]
ne serrait-il pas utile d'inclure la différence "énergie grise du PV - énergie grise du mix énergétique" ?
sachant qu'il y a un gros soucis de temporalité (produire 1000 kWh les 2/3 en été et utiliser 1000 kWh pendant le pic hiver n'a pas du tout le même contenu carbone)

**Comment by laem** [comment]
Oui, ce serait pertinent. Quand à se lancer dans ces calculs... :D
