### ISSUE TITLE
Loisirs culturels

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1243]
Bonjour. Je ne vois pas de loisirs / culture dans les questions. Le déplacement est probablement comptabilisé dans les heures de metro/tram mais quid du loisir en lui même ? Cinéma, théâtre, musée, concert, sports; aucun impact sur son empreinte ?

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre retour ! Effectivement, les loisirs ne sont pas comptabilisés spécifiquement ici. Une part des émissions liées au loisirs est comprise dans les services publics.
Si vous êtes intéressées, n'hésitez pas à jeter un oeil au simulateur ["Mon Match Carbone"](https://www.monmatchcarbone.fr/) qui permet de calculer votre empreinte carbone sportive !
