### ISSUE TITLE
Occasion

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1244]
Dans vos questions impossible de répondre qu'on achète d'occasion surtout pour les vêtements. 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre retour. Nous travaillons activement sur ce sujet mais la quantification et l'attribution des émissions d'un achat de seconde n'est pas évidente. Voir PR #1004 et #1005.
