### ISSUE TITLE
surprenant de voir "Manger de la viande uniquement le midi"

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1246]
Bonjour
L'outil est très intéressant, mais certaines suggestions sont surprenantes. Par exemple 5 repas avec viande (les 5 midis à la cantine) + 9 repas végétariens (soir + week end) aboutissent à la suggestion "Manger de la viande uniquement le midi (ou le soir)". Il me semble qu'un seuil à 7 repas/semaine avec viande (vs 0 actuellement) serait plus pertinent.

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/nombre-de-plats-viande`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre retour. Il serait peut-être pertinent de modifier l'intitulé de l'action. Nous avons choisi, en remplaçant la moitié des repas carné par des repas végétariens, d'approximer une consommation de viande uniquement le midi avec l'hypothèse que lorsque l'utilisateur renseigne ses repas, ils sont répartis "en moyenne" sur la semaine (on ne fait pas la différence entre repas du midi et du soir).

**Comment by Clemog** [comment]
Voir #1197
