### ISSUE TITLE
Calculateur empreinte avion

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1247]
Bonsoir,

Je me permet de vous contacter car je voudrais savoir comment est calculé le Kg/Co2 par heure dans un avion sur votre simulateur.

En effet, suite à divers recherches et plusieurs avis d'ingénieur sur le sujet, un aller retour Paris / New-York serait de 1T environ, et non pas 1,5T, résultat donné sur votre calculateur. 

Je vous remercie d'avance pour votre réponse et vous souhaite une bonne soirée ! 

Bien cordialement,

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/avion/moyen-courrier/heures-de-vol`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
N'hésitez pas à visiter notre documentation pour en savoir plus ! https://nosgestesclimat.fr/documentation/transport/avion
