### ISSUE TITLE
Problème de navigation entre les questions

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1248]
Lorsque nous souhaitons faire « précèdent », nous accédons à la question d’avant. En revanche quand on valide et on fait « suivant » pour reprendre notre navigation, on tombe sur une question qui n’est pas du tout cohérente. Type « consommation de fioul » alors qu’on avait coché non. 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Problème à investiguer...
