### ISSUE TITLE
gaz biomethane

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1249]
Bonjour, 
j'ai souscrit à une offre de gaz biométhane, et je n'ai pas la sensation que le simulateur en tienne compte.
de même, je produis de l’électricité photovoltaïque
je produis aussi de l'eau chaude (solaire thermique): finalement, ce qui compte, c'est les kWh de gaz consommés.

merci

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Voir #982
