### ISSUE TITLE
Nombre de voitures

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1251]
Bonjour, malheureusement nous ne pouvons pas renseigner le nombre de voitures que nous avons (j'ai un véhicule thermique et 1 électrique) ni si nous avons un vélo électrique. Ni le nb de smartphones dans le foyer. Merci

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
En effet, un gros trou dans la raquette. 
https://github.com/datagir/nosgestesclimat-site/issues/348

**Comment by laem** [comment]
Je ferme au  profit de #646
