### ISSUE TITLE
Ou sont les autres paramètres ? 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1252]
Le transport, la nourriture... Mais où sont les autres paramètres bien plus producteur de co2 ?? 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Lesquels ?
