### ISSUE TITLE
Panneau solaire 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1254]
J'ai mon toit couvert de panneaux solaires dont je réinjecter le surplus pourquoi n'est ce pas pris en compte ? 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Cette remarque révèle probablement que l'utilisateur n'a pas consulté la bulle d'aide, trop peu visible. 
Cela dit, on pourrait aussi proposer plusieurs bulles d'aides, déclenchées par des clics sur des mots clefs bien écrits. 

Exemple avec gov.uk, merci @jeremiecook, 

![image](https://user-images.githubusercontent.com/1177762/140388494-adfce611-6c9d-4af4-bee4-a649b061d874.png)

Ici le bouton d'aide n'est pas juste une icône :bulb: mais un texte qui déclenche l'envie de cliquer.
