### ISSUE TITLE
Erreur ou bug ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1256]
Je ne mange qu'une fois par jour, et 5 fois sur 7 sans viande. Soit 7 repas, sans (petit) déjeuner, 1,3 tonne ? 
(ou votre calculateur à pris en compte 14 repas ?)

Et vous pensez que ça donne le même volume de déchets ? J'ai 1 sac de 50 litres tous les mois.

Quid de l'hygiénisme américain qui a ravagé le cerveau des français ? sacré rayon "ménager", l'oréal ? crèmes et ongles ?

Vous êtes des comiques...votre calculateur autant.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour. 

Il ne vous échappera pas qu'il y a de fortes chances que vous mangiez moins fréquemment... mais davantage à chaque repas. 

Voir #207
