### ISSUE TITLE
La consommation de viande autoproduite ne peut pas être renseignée. 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1257]
Il me semble que manger la viande que l'on chasse et que l'on produit soi-même ne peut pas être autant consommatrice que des viandes d'élevages intensifs de l'autre bout du monde...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, malheureusement c'est un détail que nous ne pouvons intégrer encore, nous avons bien d'autres priorités. 
Je note cependant dans #185
