### ISSUE TITLE
Motorisation hybride rechargeable

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1258]
Vous ne proposez pas l’option hybride rechargeable qui pour les petits trajets équivaut à une électrique mais pour les longs trajets est hybride. Évidemment il y a une part de charge de batterie qui va se refléter dans la consommation domestique sauf si nombre de recharges sont faites sur bornes publiques. Étant donné le nombre de voitures de ce type sur le marché, je pense que ce serait bien d’avoir cette option.

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/voiture/motorisation/hybride`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci pour le retour ! Voir #646
