### ISSUE TITLE
pas assez de détail

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1260]
Sur l'alimentation je cherche les produits de ma région faible déplacement cela compte dans l'empreinte carbonne

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, l'alimentation locale viendra bientôt ;) #1066
