### ISSUE TITLE
J'habite en campagne. Il n'y a pas de transport en commun surtout a 5 heures du matin

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1263]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, le simulateur calcule votre empreinte, sans distinction géographique.
