### ISSUE TITLE
Voiture hybride versus voiture électrique 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1264]
Dans votre simulateur, la voiture hybride émet d’avantage de CO2 que la voiture électrique. Est-ce normal en France ?

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Oui bien sûr, pourquoi ?
