### ISSUE TITLE
Retour en arrière et coche des cases de la mosaïque

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1265]
on ne peut pas retourner en arrière quand on s'apercoit que j'ai décoché les cases au lieu de les cocher car vous les aviez déjà cochées... et impossible de reprendre le test au départ donc tant pis... encore un test arnaque...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Pour les cases précochées, c'est résolu ici : https://github.com/datagir/nosgestesclimat-site/issues/372.
Le bug concernant le retour arrière est pris en compre ici : https://github.com/datagir/nosgestesclimat-site/issues/426.
