### ISSUE TITLE
Conseils d'actions caducs

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1267]
Bonjour, 

En conseil d'actions le simulateur propose :

-de remplacer les ampoules par des led, sauf que c'est déjà le cas, en plus des petits gestes d'économies d'énergie, mais cela n'est pas demandé dans le questionnaire de base, l'action est donc proposée pour rien ;
-de baisser d'un degré le chauffage (passer de 20 à 19°C), qui n'est pourtant activé que de mi-novembre à mi-avril, d'ailleurs cette précision n'est pas demandée dans le questionnaire encore une fois, pour baisser le résultat de quelques dizaines de kg de CO2, cela est exagéré, étant donné qu'une température à 20°C est déjà raisonnable, nous n'allons pas finir en manteau chez nous ; 
-d'avoir une conduite écologique, mais c'est déjà la cas, pourtant la question n'est posée nulle part en amont encore une fois ; 
-d'éliminer les 1000 tonnes restantes et atteindre les 2000/an en misant sur la rénovation, etc. mais cela ne peut être que du fait du propriétaire, et ce serait mal connaître les proprios et agences que de croire qu'ils et elles mettront la main à la poche s'il n'y a pas de contraintes légales. 

Tous ces conseils d'actions sont donc caducs, ce fut une perte de temps et... d'énergie.
Beaucoup trop d'éléments ne sont pas pris en compte, bien que certains points soient "justifiés/expliqués" dans la FAQ, c'est dommage.
 
Bonne journée et bon courage pour la suite ! 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour vos retours. Effectivement, certaines actions apparaissent avec des questions supplémentaires, qui ne sont pas posées dans le test. Nous proposons désormais la possibilité d'écarter certaines actions qui ne vous correspondent pas ce qui peut facilité votre lecture et sélection.
