### ISSUE TITLE
Atteindre 2 tonnes de co2

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1269]
Si les services publics continuent à consommer autant, impossible d’atteindre l’objectif  sauf à devenir végétalien et à arrêter tout chauffage … comment le français moyen peut descendre à 2 tonnes ….

Depuis la page : `https://nosgestesclimat.fr/documentation/services-publics/voter`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Atteindre 2 tonnes n'est pas impossible, même si c'est compliqué, et ceci est un fait sur lequel nous n'avons pas de prise ici. 

Voir la FAQ https://nosgestesclimat.fr/contribuer et le persona "2 tonnes" quand on arrive dans l'onglet "Agir" avec une simulation vide.
