### ISSUE TITLE
pourquoi ne peux t on pas répondre par 0 si on n'a pas d'ordinateur fixe, de télévision, 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1270]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Encore le problème du précochage 

Fixed by datagir/nosgestesclimat-site/issues/372
