### ISSUE TITLE
ordinateur portable

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1272]
nous n'en possédons pas, pas possible de le signaler !

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Voir https://github.com/datagir/nosgestesclimat-site/issues/372
