### ISSUE TITLE
Mosaïque précochée + retour mosaïque buggué

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1273]
Impossible de reprendre une rubrique où je n'ai pas effectué un remplissage correct. Inversion entre les carrés et le symbole de validation pré rempli dans la rubrique logement. Je m'en suis rendue compte avec la rubrique numérique mais je n'arrive pas à revenir en arrière. Les flèches en bas ne fonctionnent pas. Dommage...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Ah, je crois que c'est un problème avec le bouton retour sur les mosaïques. 

Pour le reste, voir https://github.com/datagir/nosgestesclimat-site/issues/372

**Comment by Clemog** [comment]
Bug concernant le bouton retour des mosaïques remonté ici : https://github.com/datagir/nosgestesclimat-site/issues/426
