### ISSUE TITLE
arrêter l'avion

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1276]
Comment faire quand on a de la famille qui habite hors d'europe pour aller la voir?

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/arrêter-l'avion`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
C'est un cas compliqué... Mais ces actions ne sont pas obligatoires ! Elles sont un moyen de réduire son empreinte. 

Dans le futur, si un système de quota de voyages est mis en place, il sera probablement voté démocratiquement des jetons supplémentaires pour les raisons familiales :)
