### ISSUE TITLE
La première question ne s'affiche pas

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1279]
Tout est dans le titre. Les questions suivantes s'affichent correctement

Depuis la page : `https://ngc.time-planet.com/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Un retour de  Time for planet 😥
Il faut leur demander de fermer leur site.

**Comment by Clemog** [comment]
Tu as pu les contacter ? 😕

**Comment by laem** [comment]
Je leur envoie un mail

**Comment by Clemog** [comment]
Résolu il me semble ;)
