### ISSUE TITLE
Actions proposées 

### ISSUE THREAD

**Issue by Alizy49** [datagir/nosgestesclimat#1282]
# Proposer une amélioration 
Bonjour, dans les gestes proposés dans Passer à l'action, il y'en a certaines que je fais déjà et qui n'ont pas été comptabilisées dans le simulateur car il n'y a pas de question à ce sujet.
Exemple: j'ai répondu à la question sur l'âge de mon logement (vieux dans mon cas) mais il n'y avait pas de question sur son isolation alors qu'il a totalement été reisolé. Ça apparait du coup dans les actions à faire mais je n'ai pas besoin de le faire 

De même pour les ampoules led et d'autres.

Pour ne pas ajouter encore plus de questions, il interessant d'ajouter une option au delà de Refuser ou Accepter l'action comm un Déjà fait.

Autre question: est-ce que l'empreinte des animaux de compagnie peut être importante? (On voit l'importance de l'alimentation humaine, peut-être que c'est aggravé par le fait d'avoir des animaux à nourrir?) 

Merci en tout cas, super initiative!

**Comment by laem** [comment]
Bonjour @Alizy49, merci pour le retour de qualité :) 

> Pour ne pas ajouter encore plus de questions, il interessant d'ajouter une option au delà de Refuser ou Accepter l'action comm un Déjà fait.

L'isolation réduit (normalement) le nombre de kWh consommés, donc l'empreinte calculée lors du test. 

Quel intérêt vois-tu donc au bouton "déjà fait" par rapport à "Refuser" ? 


> Autre question: est-ce que l'empreinte des animaux de compagnie peut être importante? (On voit l'importance de l'alimentation humaine, peut-être que c'est aggravé par le fait d'avoir des animaux à nourrir?)

Oui, très bonne question déjà soulevée. Voir #35. 

Merci pour les encouragement !

**Comment by Marc-marc-marc** [comment]
> Quel intérêt vois-tu donc au bouton "déjà fait" par rapport à "Refuser" ?

déjà fait devrait faire disparaître la suggestion
refuser devrait lister la suggestion dans une section refusé où on pourrait la repêcher plus-tard si on change d'avis
