### ISSUE TITLE
Calcul familial

### ISSUE THREAD

**Issue by Clotildeca** [datagir/nosgestesclimat#1283]
Dommage que l'on ne puisse pas établir un "calcul familial", en effet le calcul transport serait différent et c'est bien ce poste qui a le plus d'impact sur notre empreinte carbone

**Comment by laem** [comment]
Merci pour le retour ! Voir la longue discussion [ici](https://github.com/datagir/nosgestesclimat-site/issues/348#issuecomment-967156390) si ça vous intéresse. Une première version devrait voir le jour en fin d'année :)
