### ISSUE TITLE
Le calcul du nombre des repas me met 48 repas de trop alors que j’en ai inscrit 14

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1284]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour,

Merci pour votre message. 

Le bug est peut-être du à un problème qui apparait sur téléphone (voir vidéo). Nous allons corriger cette erreur. (@laem)

https://user-images.githubusercontent.com/55186402/141949581-9a0b5a95-b4fb-400a-8951-8c5dd873d859.mov

**Comment by laem** [comment]
@Clemog bien vu ! C'est la largeur de l'input pas suffisante pour afficher n >= 10 ? 
Étrange, je n'arrive pas à le reproduire, c'est quel navigateur ? Safari iPhone ?

**Comment by laem** [comment]
OK, safari iPhone 7 ça plante.

**Comment by laem** [comment]
@Clemog je te laisse tester cette PR sur ton navigateur où t'as capturé le bug, normalement c'est corrigé :) 

https://github.com/datagir/nosgestesclimat-site/pull/392

**Comment by Clemog** [comment]
Yes top, j'ai mergé ! :)
