### ISSUE TITLE
le "test à plusieurs" ne semble pas fonctionner (Firefox 2016, Windows XP)

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1286]
l'association dans laquelle je milite souhaite utiliser ce quizz pour animer des soirées "carbone", avec une petite expo de 12 panneaux explicatifs "énergie-climat". Ce serait vraiment bien que la version "conférence" fonctionne ! Merci pour vos efforts dans ce sens.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, Windows XP n'est plus supporté depuis 2014, et est à ce titre plutôt dangereux à utiliser. Nous ne supporterons pas ce système. Idem pour Firefox 2016. 

Sachez que vous pouvez installer des distributions linux sur la plupart des vieux ordinateurs. 

Par exemple, Ubuntu : https://www.ubuntu-fr.org.
