### ISSUE TITLE
résultat manifestement faux

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1287]
J'aimerais comprendre pourquoi le simulateur affiche 7T de CO2 en transport alors que je n'utilise aucun moyen de transport (uniquement marche à pied et vieux vélo)

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, c'est très étrange. Peut-être avez-vous pris l'avion ? Jeferme en attendant d'autres infos mais n'hésitez pas à contribuer.
