### ISSUE TITLE
Emprunte nombre d'enfants manque

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1289]
Nous nous sommes limités à avoir un seul enfant car c'est sûrement un des geste les plus écolo que l'on puisse faire. Pourquoi est ce que cet aspect très important n'apparait pas dans le questionnaire?

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, voir https://github.com/datagir/nosgestesclimat/issues/984.
