### ISSUE TITLE
📈 MAJ prix du gaz

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1292]
Suite aux récentes augmentations. 

Attention, il faut prendre un prix réel, incluant abonnement et taxes, pas un kWh marginal seulement.

**Comment by Benjamin-Boisserie-ABC** [comment]
Il est très difficile de trouver des données à jour en TTC **et** incluant le prix de l'abonnement

La donnée que l'on utilisait jusque là était reprise d'Avenir Climatique reprise elle même de [Elyotherm](https://elyotherm.fr/comparatif-cout-energies-kwh). Cette donnée n'est plus à jour (la page pointe sur des tarifs 2018.

Un autre comparateur [Selectra] (https://tarifgaz.com/tarifs) renseigne un prix de 0.0880€/kWh TTC pour un tarif B1 (chauffage gaz) en zone 2 (zone la plus répandue en France). 
Ce prix semble cohérent avec le prix réglementé depuis octobre 2021 par la [Commission de régulation de l'énergie](file:///C:/Users/conta/AppData/Local/Temp/211215_Baremes_TRVG_Janvier2022-3.pdf) de 6,49 €/kWh **HT** qui une fois majoré des taxes me donne 0,087972 €/kWh
**Attention** : je ne considère ici que les [taxes](https://www.energie-info.fr/fiche_pratique/cspe-ticgn-cta-tva-toutes-les-taxes-sur-ma-facture/) sur la consommation (TICGN, TVA de 20% sur la TICGN et TVA de 20% sur la conso). Il manque donc la CTA, la TVA de 5,5% sur la CTA et la TVA de 5,5% sur le montant de l'abonnement ainsi que le montant de l'abonnement en lui même (d'ailleurs pas sûre que la donnée utilisée jusqu'à présent prenait en compte l'abonnement).

Si j'essaie de rajouter l'abonnement fixé par ce même régulateur à 202,68 €/an en le majorant d'une TVA 5,5% et pour une consommation moyenne de 15000 kWh j'obtiens un prix de 0,102 €/kWh (mais il manque encore la CTA et la TVA à 5% sur la CTA).

Je joins un fichier Excel pour essayer de faire comprendre mon raisonnement
[maj_prix_gaz.xlsx](https://github.com/datagir/nosgestesclimat/files/7897836/maj_prix_gaz.xlsx)

**Comment by laem** [comment]
Je ferme, c'est en ligne :)
