### ISSUE TITLE
Modifier un test

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1294]
je ne peux modifier que le numérique sur le test fait hier, mais pas les autres postes. Pourquoi?
Merci

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Page profil non trouvé, j'imagine. Je ferme, problème déjà connu.
