### ISSUE TITLE
Résultats consolidé Bilan en groupe

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1296]
Bonjour,
Nous essayons d'effectuer un bilan de groupe mais nous ne voyons chacun que des résultats individuels.
Est-il possible de faire le bilan à plusieurs et d'avoir un résultat consolidé ?
Merci

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, avez-vous testé la fonctionnalité conférence ? C'est ici : https://nosgestesclimat.fr/conférence

Êtes-vous sur le réseau d'une entreprise qui bloque le trafic ? Dans ce cas le mieux est de passer par vos téléphones personnels.
