### ISSUE TITLE
Le logiciel devrait prendre en compte le recyclage. Pour me chauffer j'utilise principalement des vieilles palettes en bois et je n'achète que des vêtements déjà portés (vide-greniers, le Bon Coin...)

### ISSUE THREAD

**Issue by Patrickdu31** [datagir/nosgestesclimat#1298]
## Poser une question 

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by laem** [comment]
Bonjour, au sujet du bois : merci pour la suggestion, mais c'est un comportement de consommation probablement trop niche pour l'instant par rapport à nos autres chantiers. 

Pour les vêtements, comme spécifié dans l'aide de la question, ne renseignez que le neuf ;)
