### ISSUE TITLE
Comment faire le calcul pour une famille ou un couple ?

### ISSUE THREAD

**Issue by JeanPaulGrange** [datagir/nosgestesclimat#1300]
Bonjour,

Lorsque je lance le test je n'ai pas compris si je peux le faire en tant que famille ou couple. Il serait intéressant de le préciser dès le départ du test.

Cordialement,
Jean-Paul Grange

**Comment by JeanPaulGrange** [comment]
en scrollant les autres issues j'ai vu que la première fois que cette question a été posée est dans l'issue #113 par contre quand on lance l'application je n'ai pas vu d'information indiquant qu'il faut remplir pour le foyer et qu'ensuite on demande le nombre de personnes. Les propositions de certaines autres personnes sont aussi intéressantes.

**Comment by laem** [comment]
Bonjour Jean-Paul, merci pour la remarque ! 

> Il serait intéressant de le préciser dès le départ du test.

C'est prévu ici, bientôt en ligne :) https://github.com/datagir/nosgestesclimat-site/pull/382

Nous travaillons sur ce tutoriel d'introduction qui expliquera "pour qui répondre".

**Comment by Clemog** [comment]
L'information est bien dans le tuto ! J'ouvre cette issue qui peut alimenter des discussion pour mieux afficher l'information :) https://github.com/datagir/nosgestesclimat-site/issues/617
