### ISSUE TITLE
The test doesn't keep going after the first question

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1305]
Chrome version 95

When I click on the answer, it goes to a blank page and never finish loading (and it is not the connection)

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Hi, could you tell us what is your browser, and its version ? 

Could you also try with the private mode ?

Closing until further info.
