### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1306]
Hi,
Just for let you know, the platform won't work when I click to next question. 
I'm using Chrome 95.
It has been days like this.

Thanks

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Hi, have you tried to take the test in a private window ?
