### ISSUE TITLE
je ne sais pas comment modifier les chiffres avec Firefox / windows

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1308]
Depuis la page : `https://nosgestesclimat.fr/documentation/logement/électricité/consommation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je ferme, l'utilisateur aurait bien profité d'une édition en place des réponses, plutôt que sur la page profil. 

Voir #333.
