### ISSUE TITLE
Simulateur déjà rempli

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1319]
J'ai dû déjà avoir réalisé le test dans le passé et maintenant il est rempli par défaut et je n'arrive pas à le remplir de nouveau...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, cliquez sur "Mon profil" puis "recommencer". Ou lancez une fenêtre de navigation privée :)
