### ISSUE TITLE
Réécrire le tuto codescape en stackblitz

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1322]
Je n'avais pas compris que j'avais la chance d'avoir accepté la beta codespace, mais que c'est maintenant payant...

https://stackblitz.com permet de faire pareil et peut-être en mieux.

**Comment by Clemog** [comment]
J'ai tenté de mettre en place l'environnement dans Stackblitz mais point bloquant : je n'arrive pas à créer un espace de travail incluant un file system.

Suggestion de Maël : installer nosgestesclimat-site comme une dépendance NPM sur nosgestesclimat qui serait donc dans les node_modules

**Comment by laem** [comment]
À noter : le lancement prochain de codesandbox projects. En beta, faut s'inscire. 
https://projects.codesandbox.io

**Comment by Clemog** [comment]
Une première solution ici : #1398
