### ISSUE TITLE
Inversion raccourci date maison 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1323]
L'étiquette "année  70" a la question sur l'année de construction du logement pré-rempli le champ avec 45 vs 70, et "apres-guerre" fait l'inverse. 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, merci pour votre message ! C'est normal, si la maison a été construite autour de 1945, elle a environ 70 ans, si elle a été construite dans les années 70, elle a environ 45 ans ;)
