### ISSUE TITLE
Blocage fin d'alimentation

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1326]
Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je me demande si c'est un problème avec la mosaïque qui s'afficherait mal sur certains mobiles / **iframes**.

**Comment by laem** [comment]
Je redirige vers https://github.com/datagir/nosgestesclimat/issues/1326
