### ISSUE TITLE
Impacte combiné de la diminution de consommation de viande

### ISSUE THREAD

**Issue by mart-e** [datagir/nosgestesclimat#1331]
Lors du calcul de l'impact, cocher "manger de la viande uniquement le we" et "privilégier la volaille" à plus d'impact que de devenir végétarien. Je suppose que l'on cumule les 2 diminutions de 10 et 9% (19% vs 14%).
Si l'on ne mange de la viande que 2 jours sur 7, l'impact de privilégier la volaille devrait être réduit de 2/7ième.

![Passer à l'action 1](https://user-images.githubusercontent.com/564822/154804346-1f68091e-0d6c-4525-8c05-5c01d46894b3.png)
![Passer à l'action 2](https://user-images.githubusercontent.com/564822/154804347-64383008-d461-4ca5-a78c-eff82ee4bd71.png)

**Comment by Clemog** [comment]
Bonjour, merci beaucoup pour le retour ! Il semble que ce problème est lié au fait que l'on ne vient pas modifier intrinsèquement la simulation lorsque l'on choisi une action (https://github.com/datagir/nosgestesclimat-site/issues/347), ce qui impose que les actions soient indépendantes.
Une manière de contourner le problème pour le moment a été de hiérarchiser les actions (ie, désactiver les actions incompatible avec l'action sélectionnée, par exemple, manger de la viande le week end disparait si on coche devenir végétarien) 
Est ce que ça répond à votre remarque ? 
Peut etre que l'idée serait de désactiver l'autre action lorsque l'une est sélectionnée ? L'utilisateur ne pourrait pas choisir "manger de la viande uniquement le we en privilégiant volaille ou porc)

**Comment by mart-e** [comment]
> Peut etre que l'idée serait de désactiver l'autre action lorsque l'une est sélectionnée ?

Je suis d'accord, en attendant une résolution de datagir/nosgestesclimat-site#347, rendre les actions incompatibles et désactiver la 2eme option quand la 1ere est sélectionnée me semble une solution acceptable :+1:
