### ISSUE TITLE
Limite d'utilisateurs de la version "à plusieurs"

### ISSUE THREAD

**Issue by DavidLBI** [datagir/nosgestesclimat#1338]
Bonjour, 
Je voulais savoir si une utilisation de la version "à plusieurs" avec 1600 participants en simultané est possible ? 
Merci.

**Comment by Clemog** [comment]
Bonjour David ! Merci pour votre message ! Normalement, il n'y aura pas de problème, un risque peut-être au niveau de l'interface qui pourrait présenter un bug d'affichage !
N'hésitez pas à nous faire un retour après l'atelier, des suggestions ! Bravo pour cette initiative, à bientôt !

**Comment by DavidLBI** [comment]
Ok merci mais quel pourrait être ce bug d'affichage ? Constaté ponctuellement ou durant toute une session ?

**Comment by Clemog** [comment]
Il a été remonté que parfois des participants se trompent et valident une valeur extrême ce qui peut écraser les résultats des participants sur le dahsboard de fin.

**Comment by laem** [comment]
Nous avons mis en ligne une version avec filtrage des résultats extrêmes :) 

Autre point : il se peut que les navigateurs les plus anciens commencent à ramer avec 1600 personnes. Avez-vous pu tester finalement @DavidLBI ?

**Comment by Clemog** [comment]
Pas de retour de @DavidLBI, je ferme. N'hésitez pas à l'ouvrir à nouveau si besoin
