### ISSUE TITLE
Quelques retours catégorie Transport

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat#1340]
Messages issus de #1332 et #1333 

> a la fin du test, quand on clique sur les catégories, on a normalement accès au détail du calcul de la catérorie.
par exemple dans divers, on a les valeurs pour "textile, électroménager, autre".
depuis quelque temps on n'a plus accès au détail des calculs pour la catégorie "transport"

>dans un foyer il est fréquent d'avoir 2 voitures (parfois plus). Il pourrait être pertinent de demander le nombre de voiture et le type. exemple classique : petite voiture pour les déplacements du quotidient (utilisé par une personne du couple), grosse voiture pour les longs déplacements. (mais peut-être que l'impact serait faible).
Je m'en suis rendue compte car nous venons de vendre la "petite voiture" (que je renseignais jusque là). Maintenant en indiquant dans l'outil mon impact a augmenté : du à la grosse voiture qui est plus récente et donc moins amortie (en tout cas c'est ce que je suppose)

**Comment by Clemog** [comment]
Bonjour, merci pour vos remarques !

Pour le bug de la documentation, nous allons le corriger.

Pour la question du nombre de voiture dans un foyer, la question est largement traitée ici : #646, n'hésitez pas à contribuer !

**Comment by laem** [comment]
Je me permets de fermer l'issue, maintenant que le 1er point est corrigé et l'autre déjà noté. Merci pour la contribution :)
