### ISSUE TITLE
E85/Bioethanol

### ISSUE THREAD

**Issue by XoddX** [datagir/nosgestesclimat#1346]
## Ajout du bio éthanol (e85) ?

*est il envisagé d’ajouter le bio éthanol à la liste des carburants ? *

**Comment by laem** [comment]
Bonjour, merci pour la suggestion ! Nous avons considéré de l'ajouter, mais finalement décidé pour l'instant que les chiffres disponibles à son sujet ne sont pas encore assez fiables. Voir [ici](https://github.com/datagir/nosgestesclimat/pull/1324) pour la discussion :)

**Comment by Clemog** [comment]
Résolu https://github.com/datagir/nosgestesclimat/pull/1396
