### ISSUE TITLE
lien cassé 

### ISSUE THREAD

**Issue by estellecomment** [datagir/nosgestesclimat#1350]
## Proposer une amélioration 

Lien cassé sur la page https://nosgestesclimat.fr/documentation/transport/arr%C3%AAter-l'avion

Le lien : https://publi.codes/studio/transport/arr%C3%AAter-l'avion?code=%0A%23%20Ci-dessous%20la%20r%C3%A8gle%20d%27origine%2C%20%C3%A9crite%20en%20publicodes.%0A%0A%23%20Publicodes%20est%20un%20langage%20d%C3%A9claratif%20d%C3%A9velopp%C3%A9%20par%20l%27Urssaf%0A%23%20en%20partenariat%20avec%20beta.gouv.fr%20pour%20encoder%20les%20algorithmes%20d%27int%C3%A9r%C3%AAt%20public.%0A%0A%23%20Vous%20pouvez%20modifier%20les%20valeurs%20directement%20dans%20l%27%C3%A9diteur%20pour%20voir%20les%20calculs%0A%23%20s%27actualiser%20en%20temps%20r%C3%A9el%0A%0Atransport%20.%20arr%C3%AAter%20l%27avion%3A%0A%20%20ic%C3%B4nes%3A%20%F0%9F%9B%AC%F0%9F%A7%B3%0A%20%20action%3A%0A%20%20%20%20d%C3%A9passe%3A%0A%20%20%20%20%20%20-%20transport%20.%20arr%C3%AAter%20l%27avion%20court%0A%20%20effort%3A%20cons%C3%A9quent%0A%20%20formule%3A%20transport%20.%20avion%0A%20%20description%3A%20%3E%0A%20%20%20%20L%27avion%20a%20une%20empreinte%20importante%20sur%20le%20climat.%20%0A%0A%0A%20%20%20%20Elle%20ne%20se%20limite%20pas%20aux%20seules%20%C3%A9missions%20de%20CO%E2%82%82%2C%20qui%20n%27est%20qu%27un%20gaz%20%C3%A0%20effet%20de%20serre%20parmi%20d%27autres.%20%0A%0A%0A%20%20%20%20L%27empreinte%20totale%20de%20l%27avion%20est%20estim%C3%A9e%20%C3%A0%20environ%202x%20celle%20du%20CO%E2%82%82.%20%0A%0A%0A%20%20%20%20Voir%20le%20%5Bcalculateur%20transport%5D(https%3A%2F%2Fmonimpacttransport.fr)%20pour%20visualiser%20cette%20empreinte%20et%20la%20comparer%20aux%20autres%20moyens%20de%20transport.%0A%20%20aller%20plus%20loin%3A%20%3E%0A%20%20%20%20%23%23%20For%C3%A7age%20radiatif%20total%0A%0A%0A%20%20%20%20L%27avion%20a%20un%20impact%20important%20sur%20le%20climat%20%C3%A0%20la%20fois%20%C3%A0%20cause%20de%20ses%20%C3%A9missions%20de%20CO%E2%82%82%20et%20d%27autres%20effets%20(dit%20for%C3%A7age%20radiatif%20additionnel).%0A%0A%0A%20%20%20%20Du%20fait%20que%20les%20avions%20volent%20en%20haute%20altitude%2C%20la%20combustion%20du%20k%C3%A9ros%C3%A8ne%20cr%C3%A9e%20des%20tra%C3%AEn%C3%A9es%20et%20perturbe%20les%20cycles%20d%E2%80%99autres%20gaz%20%C3%A0%20effet%20de%20serre%20que%20le%20CO%E2%82%82%20(vapeur%20d%27eau%2C%20eau%20condens%C3%A9e%20sous%20diverses%20formes%2C%20NOx%20et%20m%C3%A9thane%20qui%2C%20ensemble%2C%20produisent%20de%20l%27ozone%2C%20etc.).%0A%0A%0A%20%20%20%20Ce%20graphique%20montre%20la%20complexit%C3%A9%20des%20effects%20en%20jeu%20(et%20encore%2C%20tout%20n%27y%20est%20pas).%0A%0A%0A%20%20%20%20!%5B%5D(https%3A%2F%2Fwww.uecna.eu%2Fwp-content%2Fuploads%2F2017%2F12%2Filusion-diagram1.jpg)%0A%0A%0A%20%20%20%20%23%23%20Avion%20vs%20voiture%0A%0A%0A%20%20%20%20On%20entend%20souvent%20que%20ramen%C3%A9e%20au%20passager%2C%20elle%20est%20du%20m%C3%AAme%20ordre%20que%20celle%20d%27une%20voiture.%20C%27est%20vrai%2C%20mais%20ce%20n%27est%20qu%27une%20partie%20de%20l%27histoire.%20%0A%0A%0A%20%20%20%20Premi%C3%A8rement%2C%20l%27empreinte%20de%20la%20voiture%20elle-m%C3%AAme%20est%20%C3%A9lev%C3%A9e.%20Comparer%20l%27avion%20%C3%A0%20la%20voiture%2C%20ne%20rend%20pas%20ce%20premier%20vertueux.%0A%0A%0A%20%20%20%20Deuxi%C3%A8mement%2C%20on%20ne%20peut%20comparer%20la%20voiture%20et%20l%27avion%20simplement%20parce%20qu%27un%20trajet%20en%20avion%20est%20en%20g%C3%A9n%C3%A9ral%20bien%20plus%20long.%20Quand%20il%20s%27agit%20de%20choisir%20la%20destination%20des%20vacances%20par%20exemple%2C%20un%20trajet%20en%20voiture%20a%20donc%20toutes%20les%20chances%20d%27%C3%AAtre%20beaucoup%20moins%20polluant.%20Cela%20dit%2C%20notons%20aussi%20que%20nos%20kilom%C3%A9trages%20en%20voiture%20sont%20tels%20que%20le%20match%20est%20relanc%C3%A9%20quand%20on%20regarde%20l%27empreinte%20%C3%A0%20l%27ann%C3%A9e.%0A%20%20plus%3A%20%3E%2B%0A%20%20%20%20%23%20Utiliser%20une%20alternative%20bas%20carbone%20pour%20partir%20en%20vacances%2Fweek-end%0A%0A%0A%20%20%20%20%23%23%20Contexte%20de%20l%E2%80%99action%0A%0A%20%20%20%20Nos%20vacances%20et%20nos%20weekends%20s%E2%80%99articulent%20tr%C3%A8s%20souvent%20autour%20de%20la%20voiture%20et%20de%20l%E2%80%99aviation%20et%20il%20n%E2%80%99est%20pas%20rare%2C%20pour%20un%20grand%20nombre%20de%20fran%C3%A7ais%20de%20traverser%20la%20France%20(en%20voiture)%20et%2Fou%20le%20monde%20(en%20avion).%20Malheureusement%2C%20ces%20modes%20de%20d%C3%A9placements%20caract%C3%A9ristiques%20du%20toujours%20plus%20vite%20toujours%20plus%20loin%20contribuent%20tr%C3%A8s%20fortement%20%C3%A0%20augmenter%20les%20%C3%A9missions%20GES.%20Adapter%20nos%20week-ends%20et%20nos%20vacances%20en%20nous%20tournant%20vers%20des%20offres%20de%20mobilit%C3%A9s%20bas%20carbone%20et%2Fou%20en%20repensant%20notre%20mani%C3%A8re%20de%20voyager%20est%20donc%20essentiel%20si%20l%E2%80%99on%20souhaite%20r%C3%A9duire%20notre%20empreinte%20carbone%20individuelle%20et%20permettre%20d%E2%80%99atteindre%20la%20neutralit%C3%A9%20carbone%20%C3%A0%20%0A%0A%20%20%20%20l%E2%80%99%C3%A9chelle%20de%20la%20soci%C3%A9t%C3%A9.%0A%0A%0A%20%20%20%20!%5B%5D(https%3A%2F%2Fecolab-data.netlify.app%2Fimages%2FChiffres-clefs_alternatives_bas_carbones_vacances_week-end_v2.png)%0A%0A%0A%20%20%20%20%23%23%20Impact%20GES%20de%20l%E2%80%99action%20%3A%0A%0A%20%20%20%20-%20Privil%C3%A9gier%20le%20train%20plut%C3%B4t%20que%20l%E2%80%99avion%20pour%20un%20week-end%20%C3%A0%20Marseille%20(depuis%20Paris%2C%20soit%20environ%20800%20km)%20%3A%20-%20410%20kgCO2eq%0A%0A%20%20%20%20-%20Faire%20du%20covoiturage%20(avec%202%20autres%20personnes)%20pour%20passer%20un%20week-end%20%C3%A0%202%20heures%20de%20chez%20soi%20(500%20km%20aller-retour)%20%3A%20-%2068%20kgCO2eq%0A%0A%20%20%20%20-%20Se%20rendre%2C%20pour%20les%20vacances%2C%20en%20train%20%C3%A0%20Barcelone%20plut%C3%B4t%20qu%E2%80%99en%20avion%20%C3%A0%20Marrakech%20(depuis%20Paris)%20%3A%20-%20781%20kgCO2eq%0A%0A%0A%20%20%20%20%23%23%20Ordre%20de%20grandeur%20GES%0A%0A%0A%20%20%20%20!%5B%5D(https%3A%2F%2Fwww.associationbilancarbone.fr%2Fwp-content%2Fuploads%2F2020%2F12%2Falternative-bas-carbone-fig1.jpg)%0A%0A%0A%20%20%20%20%60%60%60Figure%201%20%3A%20%20Impact%20GES%20pour%20diff%C3%A9rents%20types%20de%20trajets%2C%20de%20modes%20de%20transports%20et%20en%20fonction%20du%20nombre%20de%20passage%20(pour%20l%E2%80%99avion%20et%20le%20train)%60%60%60%0A%0A%0A%0A%0A%20%20%20%20%23%23%20Budget%20%3A%0A%0A%20%20%20%20Le%20cout%20financier%20des%20actions%20propos%C3%A9es%20peut%20varier%20tr%C3%A8s%20fortement%20%C3%A0%20la%20hausse%20comme%20%C3%A0%20la%20baisse.%20Ainsi%2C%20le%20covoiturage%20permettra%20des%20%C3%A9conomies%20de%20plusieurs%20dizaines%20d%E2%80%99euros%20par%20trajet%20tandis%20que%20remplacer%20l%E2%80%99avion%20par%20le%20train%20peut%20s%E2%80%99av%C3%A9rer%20souvent%20plus%20couteux%20au%20vu%20des%20prix%20d%E2%80%99appel%20des%20compagnies%20a%C3%A9riennes%20low-cost.%0A%0A%0A%20%20%20%20%23%23%20Chiffres%20cl%C3%A9s%20%C3%A0%20retenir%0A%0A%20%20%20%20-%20En%201950%2C%20on%20comptabilisait%2025%20000%20touristes%20internationaux%20contre%20674%20millions%20en%202000%20et%201.186%20milliard%20en%202015.%20Les%20estimations%20de%20l%E2%80%99ONU%20mettent%20en%20avant%20le%20chiffre%20de%201.8%20milliard%20de%20touristes%20internationaux%20en%202030%2C%20soit%20une%20augmentation%20de%2052%20%25%20en%2010%20ans%20%5B%5E1%5D.%20%0A%0A%20%20%20%20-%20Un%20aller-retour%20Paris%20New-York%20%C3%A9met%201.8%20tonnes%20de%20CO2eq1%2C%20soit%20la%20totalit%C3%A9%20des%20%C3%A9missions%20que%20l%E2%80%99on%20%E2%80%9Cdevrait%E2%80%9D%20%C3%A9mettre%20pour%20atteindre%20la%20neutralit%C3%A9%20carbone%20en%202050.%0A%0A%20%20%20%20-%20Un%20aller-retour%20Paris-Marseille%20%C3%A9met%20environ%20250%20kgCO2eq%20par%20passager%20en%20avion%20contre%20seulement%203%20kgCO2eq%20en%20train.%0A%0A%20%20%20%20-%2015%20kg%20de%20bagages%20en%20avion%2C%20c%E2%80%99est%20l%E2%80%99%C3%A9quivalent%20de%20200%20kgCO2eq%20%C3%A9mis%20en%20plus%20%5B%5E2%5D.%0A%0A%20%20%20%20-%20En%202018%2C%20presque%20300%20000%20tonnes%20de%20CO2%20ont%20%C3%A9t%C3%A9%20%C3%A9vit%C3%A9es%20en%20France%20gr%C3%A2ce%20%C3%A0%20la%20pratique%20du%20covoiturage%20pour%20une%20distance%20moyenne%20de%20239%20km%20par%20trajet%20et%20un%20taux%20de%20remplissage%20moyen%20de%203%2C5%20personnes%20par%20v%C3%A9hicule%20%5B%5E3%5D.%0A%0A%0A%20%20%20%20%23%23%20Explication%0A%0A%20%20%20%20La%20voiture%20et%20plus%20particuli%C3%A8rement%20l%E2%80%99avion%20nous%20permettent%20de%20raccourcir%20les%20dur%C3%A9es%20de%20voyage%20tout%20en%20allongeant%20les%20distances%20parcourues.%20Qui%20plus%20est%2C%20l%E2%80%99essor%20de%20ces%20modes%20de%20transports%20ont%20favoris%C3%A9%20le%20d%C3%A9veloppement%20du%20tourisme%20de%20masse%20qui%20lui-m%C3%AAme%20favorisa%2C%20en%20retour%2C%20le%20d%C3%A9veloppement%20de%20ces%20m%C3%AAmes%20modes%20de%20transports.%20Malheureusement%2C%20ces%20formes%20de%20mobilit%C3%A9s%20ne%20sont%20pas%20sans%20cons%C3%A9quence%20pour%20le%20climat.%0A%0A%0A%20%20%20%20Afin%20de%20s%E2%80%99engager%20sur%20la%20voix%20de%20la%20neutralit%C3%A9%20carbone%2C%20il%20est%20donc%20n%C3%A9cessaire%20d%E2%80%99essayer%20d%E2%80%99articuler%20nos%20week-ends%20et%20nos%20vacances%20autour%20d%E2%80%99offres%20de%20transports%20moins%20carbon%C3%A9es%20comme%20le%20covoiturage%2C%20voir%20vers%20des%20offres%20dites%20%C2%AB%20bas%20carbone%20%C2%BB%20comme%20le%20train.%20%20En%20effet%2C%20il%20existe%20un%20rapport%20de%20100%20entre%20les%20facteurs%20d%E2%80%99%C3%A9missions%20(quantit%C3%A9%20de%20CO2eq%20%C3%A9mise%20par%20km%20parcouru)%20d%E2%80%99un%20avion%20gros%20porteur%20et%20celui%20du%20TGV.%20Ainsi%2C%20un%20trajet%20Paris%2FMarseille%20aller-retour%20%C3%A9mettra%20environ%20413%20kgCO2eq%2Fpassager%20en%20avion%20contre%20seulement%203%20kg%20en%20train.%20Repenser%20sa%20destination%20de%20vacances%20peut%20aussi%20permettre%20de%20r%C3%A9duire%20encore%20plus%20fortement%20ses%20%C3%A9missions%20de%20GES.%20Par%20exemple%2C%20choisir%20de%20se%20rendre%20depuis%20Paris%20%C3%A0%20Barcelone%20(en%20train)%20plut%C3%B4t%20qu%E2%80%99%C3%A0%20Marrakech%20(en%20avion)%20permettra%20d%E2%80%99%C3%A9viter%20d%E2%80%99%C3%A9mettre%20781%20kg%20de%20CO2eq.%0A%0A%0A%20%20%20%20Cependant%2C%20ces%20offres%20de%20transports%20alternatives%20dites%20%C2%AB%20bas%20carbone%20%C2%BB%20ne%20sont%20pas%20toujours%20existantes%20et%20%C3%A9conomiquement%20rentables.%20Leur%20(re)d%C3%A9veloppement%20dans%20les%20ann%C3%A9es%20%C3%A0%20venir%20est%20donc%20essentiel%20pour%20s%E2%80%99assurer%20du%20respect%2C%20%C3%A0%20plus%20large%20%C3%A9chelle%2C%20des%20objectifs%20de%20neutralit%C3%A9%20carbone%20%C3%A0%20l%E2%80%99horizon%202050%2C%20qui%20plus%20est%2C%20quand%20on%20sait%20que%20la%20plus%20embl%C3%A9matique%20d%E2%80%99entre%20elle%2C%20le%20train%2C%20souffre%20de%20sous-investissements%20depuis%20des%20ann%C3%A9es%20r%C3%A9sultant%20en%20la%20fermeture%20de%20nombreuses%20lignes%20(lignes%20r%C3%A9gionales%2C%20train%20de%20nuit%2C%20etc.)%20%5B%5E4%5D.%20A%20titre%20d%E2%80%99exemple%2C%20il%20reste%20actuellement%20en%20France%202%20trains%20de%20nuits%20contre%20un%20peu%20plus%20d%E2%80%99une%20quinzaine%20rien%20qu%E2%80%99au%20d%C3%A9but%20des%20ann%C3%A9es%202000.%0A%0A%0A%20%20%20%20Toutefois%2C%20m%C3%AAme%20si%20ces%20alternatives%20bas%20carbone%20n%E2%80%99existent%20pas%20toujours%2C%20voyager%20de%20mani%C3%A8re%20durable%20nous%20impose%20de%20revoir%20notre%20rapport%20au%20temps%20comme%20peuvent%20le%20faire%20les%20%C2%AB%20slow%20mouvements%20%C2%BB%20qui%2C%20dans%20le%20cadre%20du%20voyage%2C%20mettent%20en%20avant%20l%E2%80%99id%C3%A9e%20d%E2%80%99un%20voyage%20plus%20doux%20et%20moins%20intensif%20en%20%C3%A9nergie%20en%20opposition%20au%20tourisme%20de%20masse.%20L%E2%80%99id%C3%A9e%20d%E2%80%99un%20voyage%20%C3%A0%20l%E2%80%99autre%20bout%20du%20monde%20ne%20disparait%20pas%20forc%C3%A9ment%20mais%20s%E2%80%99envisagera%20peut-%C3%AAtre%2C%20%C3%A0%20l%E2%80%99avenir%2C%20de%20mani%C3%A8re%20tr%C3%A8s%20diff%C3%A9rente.%20Comme%20le%20montre%20l%E2%80%99exemple%20du%20choix%20des%20vacances%20entre%20Barcelone%20et%20Marrakech%2C%20l%E2%80%99id%C3%A9e%20du%20toujours%20plus%20vite%20toujours%20plus%20loin%20n%E2%80%99est%20pas%20soutenable%20dans%20un%20objectif%20commun%20de%20neutralit%C3%A9%20carbone.%0A%0A%0A%20%20%20%20%23%23%20Sources%0A%0A%20%20%20%20%5B%5E1%5D%3A%20%5BInfographie%20Vacances%2C%20Ademe%20MultiMedia%5D(https%3A%2F%2Fmultimedia.ademe.fr%2Finfographies%2Fvacances-au-kilometre%2F)%0A%0A%20%20%20%20%5B%5E2%5D%3A%20%5BComment%20partir%20en%20vacances%20sans%20trop%20polluer%2C%20Infographie%2C%20Ademe%5D(https%3A%2F%2Flibrairie.ademe.fr%2Fconsommer-autrement%2F821-comment-partir-en-vacances-sans-trop-polluer-.html)%0A%0A%20%20%20%20%5B%5E3%5D%3A%20%5BZero%20Empty%20Seats%2C%20Blablacar%2C%202019%5D(https%3A%2F%2Fblog.blablacar.fr%2Fblablalife%2Flp%2Fzeroemptyseats)%0A%0A%20%20%20%20%5B%5E4%5D%3A%20%5BL%E2%80%99avenir%20du%20transport%20ferroviaire%2C%20Rapport%20au%20premier%20ministre%2C%20f%C3%A9vrier%202018%2C%20Jean-Cyril%20Spinetta%5D(https%3A%2F%2Fwww.ecologie.gouv.fr%2Fsites%2Fdefault%2Ffiles%2F2018.02.15_Rapport-Avenir-du-transport-ferroviaire.pdf)%0A%0A%0A%0A%23%20Situation%20%3A%0A%0Atransport%20.%20avion%3A%201006.58%C2%A0kgco2e%2Fan%0Atransport%3A%20non

(Je crois qu'il est trop long et que mon browser le tronque)

![Screenshot_20220319-161829_Firefox](https://user-images.githubusercontent.com/911434/159127026-1c8e0fb3-94b0-4cdb-a0e3-2c1e1bdf972d.jpg)

**Comment by laem** [comment]
Ah oui merci ! On a vraiment un problème avec ces liens à rallonge. Il faudrait qu'on mette en place une petite base de données, ou au moins un système de raccourcisseur de lien :/ 

Cela dit, peut-être que MAJ publicodes (on est bien derrière la dernière version) corrigerait le problème ? Je note. 

 https://github.com/datagir/nosgestesclimat-site/pull/302

**Comment by Clemog** [comment]
C'est bien résolu ! Je ferme :)
