### ISSUE TITLE
Sur la consommation de fruits de saison

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1361]
Ajouter granularité "souvent" 
Et le jamais pourrait être remplacé par "je ne fais pas attention". Probablement que peu de gens sont assez machiavéliques pour ne consommer délibérément QUE des fruits hors saison 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre message, une PR est en cours pour prendre en compte cette remarque : #1358
