### ISSUE TITLE
Impossible de valider

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1362]
A la question "Quels appareils électroménagers de moins de 10 ans possédez-vous ?" il m'est impossible de valider. Le bas de la question semble coupé et je ne peux pas mettre suivant

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, merci pour votre message ! Je n'arrive pas à reproduire le bug, pouvez-vous me donner plus de précisions ? 

Vous ne pouvez pas accéder au bouton "suivant" comme dans le gif ?

![electroménager](https://user-images.githubusercontent.com/55186402/162733001-c62c3692-1968-49ce-b9c6-806954975611.gif)

**Comment by Clemog** [comment]
Lié à #1363
