### ISSUE TITLE
Plantage de la page électroménager

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1369]
En mode conférence, « plantage » de la page « électroménager » (celle où on doit renseigner les équipements qu’on possède) pour plusieurs utilisateurs, avec impossibilité de faire une sélection ; nécessité de la réactualiser pour que ça fonctionne.

Précisions : nous étions 5, utilisions Firefox et étions tous dans la même salle, connectés en filaire sur le réseau de la Ville.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Normalement, c'est résolu : il s'agit d'iFrames qui empêche le scroll... la balle n'est pas dans notre camps.
