### ISSUE TITLE
Propositions dans «Agir» qui semblent pas du tout adaptées

### ISSUE THREAD

**Issue by Philetjosie** [datagir/nosgestesclimat#1382]
## Proposer une amélioration 

J'ai fait mon bilan, et je suis en particulier un très petit rouleur (moins de 2000 km/an en voiture), mais 90 km/semaine en vélo. De plus, ma voiture est récente (5 ans) et petite, toutes choses que j'ai indiquées.
Néanmoins, une action qui est proposée est d'acheter une voiture électrique !!! Cela n'a aucun sens d'un point de vue environnemental (sans parler du point de vue économique) de proposer de remplacer une petite voiture thermique récente qui ne roule que 2000 km/an par une électrique. L'ademe a publié assez de documents sur le cycle de vie des véhicules. Il faut adapter votre algorithme pour ne pas qu'il propose de l'électrique dans ce cas.

Pour ma part, avec 3 tonnes d'empreinte carbone, plus du tiers vient de la rubrique service public, sur laquelle je n'ai aucune influence, et toutes les autres actions proposée sont inapplicable ou presque. Pour avoir une telle empreinte, vous imaginez que je fais déjà beaucoup. Je trouve dommage que je résultat de l'évaluation ne soit pas remis en perspective par rapport à la moyenne (vous être dans les XX% les plus économes) et qu'il n'y ai pas un message de «félicitation» pour les bilans qui sont en-dessous de la moyenne.

Avec mes meilleures salutations.

**Comment by laem** [comment]
Bonjour, merci pour le retour :) 

- au sujet de la voiture électrique, normalement sauf bug, la proposition d'action qui vous a été faite vous faisait gagner 55kg **si l'achat est d'occasion**, et -900 kg sinon ;)

![image](https://user-images.githubusercontent.com/1177762/167632532-1a29fcf3-93b3-4568-8fc0-a87b93e7eb44.png)

À vous de juger si les 55kg sont intéressants. Bien sûr, notre algorithme peut être questionné, mais toujours est-il que **2000 km par an en voiture thermique**, c'est tout simplement loin d'être négligeable. 

> toutes les autres actions proposée sont inapplicable ou presque.

Normalement, vous avez du voir un message qui vous dit "Désolé, nous n'avons plus d'actions *chiffrées* très pertinentes pour vous". Est-ce le cas ? 


>  Je trouve dommage que je résultat de l'évaluation ne soit pas remis en perspective par rapport à la moyenne (vous être dans les XX% les plus économes) et qu'il n'y ai pas un message de «félicitation» pour les bilans qui sont en-dessous de la moyenne.

Oui, nous avons bien noté qu'il fallait envoyer un message dès la page de fin de test du style "Vous êtes nettement en-dessous de la moyenne : notez bien qu'il y a de grandes chances que votre temps passé à convaincre et aider les autres soit plus efficace que de chercher à récupérer les 2 tonnes en trop (même s'il faudra le faire un jour)". :)

**Comment by Benjamin-Boisserie-ABC** [comment]
Sur l'achat d'un véhicule élec on est bon justement vu qu'on montre que ca rajouterai quasiment une tonne de CO2e.

Concernant le message `toutes les autres actions proposée sont inapplicable ou presque` c'est plutôt normal quand on a une empreinte de 3 tCO2e. Ça me questionne d'arriver à une empreinte carbone si faible sans comprendre (il me semble) qu'on a fait la quasi totalité du chemin de réduction et que donc le passage à 2t viendra donc d'une transition bas carbone à l'échelle collective (qui réduira par conséquent l'impact du poste service publics). Il faudrait donc que : 
- pour ce genre d'empreinte faible ( <4 tCO2e ?) on mette directement en avant l'action (i.e. au plus haut de la page) "faire changer les autres" et "faire pression localement". On pourrait avoir une petite bulle info à côté qui explique notre choix de mettre ces actions comme les plus significatifs pour ce genre de profil
- est ce que pour la voiture électrique on ne devrait pas mettre un " ? " pour faire comprendre qu'il s'agit d'une réflexion sur l'usage de la voiture élec qui peut s'avérer défavorable (comme dans ce cas là) mais bon ca romprait avec notre formalisme
- qu'on récompense (visuellement ?) les gens en dessous de la moyenne mais surtout de la médiane (en cours de sourcing)

**Comment by Philetjosie** [comment]
Bonjour, merci pour vos réponses à mes questions / suggestions. Vous avez répondu ou pris en compte celles-ci. Sur la voiture électrique, je pense toujours que ce n'est pas pertinent, et que le gain de CO2 indiqué ne prends pas en compte le cycle de vie, avec 2000 km/an, il n'y a aucune chance.
Une autre suggestion à laquelle j'ai pensé, c'est soit de demander dans les questions si on achète de l'électricité renouvelable (maintenant que le marché est ouvert c'est une possibilité), et si ce n'est pas le cas, dans les suggestions, mettre celle-ci ("opter pour de l'électricité 100 % renouvelable auprès de votre fournisseur»). 
Bravo pour votre travail et aussi pour prendre en compte les remarques des utilisateurs (c'est assez rare pour être souligné), et meilleures salutations.

**Comment by Clemog** [comment]
Je ne comprends pas votre remarque concernant la prise en compte de l'ACV complète pour la voiture électrique ?

Pour cette action, l'empreinte associée à l'achat d'une voiture électrique correspond à un recalcul de l'empreinte de vos déplacements en voiture en modifiant la motorisation (vers l'électrique) et l'âge de la voiture (neuf ou occasion). Plus d'informations ici : #1329 et #1351 

Pour l'électricité verte, je vous laisse jeter un oeil a notre FAQ (https://nosgestesclimat.fr/contribuer), qui mériterait d'être un peu plus mis en valeur sur le site !

**Comment by laem** [comment]
Je me permets de fermer, mais n'hésitez pas à continuer de commenter, on rouvrira si d'autres questions émergent :)
