### ISSUE TITLE
Compostage / recuperateur eau

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#140]
Poubelle quasi vide sortie une fois par mois

**Comment by laem** [comment]
Oui, à intégrer à côté de la question sur le zéro déchets. On pourrait la séparer en plusieurs sous-questions plus précises et faciles à répondre : 
- Vos déchets végétaux vont au compost ?
- Achetez-vous la plupart des choses en vrac / étalage légumes et fruit ? 
- Idem pour cosmétiques et produits ménagers, qu'on trouve aujourd'hui en vrac (vinaigre, produits WC, produit vaisselle, sol, ...)

**Comment by Clemog** [comment]
Sujet traité dans #1415, améliorations dans #1443
