### ISSUE TITLE
Quel type de voiture utilisez-vous ?

### ISSUE THREAD

**Issue by Koalid** [datagir/nosgestesclimat#1401]
## Poser une question 

A "Quel type de voiture utilisez-vous ?" :

la voiture électrique est montrée comme très peux émettrice de CO2,  ce qui est de toute évidence VRAI (grâce au nucléaire, uniquement en France. 

Comme vous le savez, le coût du CO2 gris de l'electricité est très important dans le calcul des énergies dites renouvelables).

## Proposer une amélioration 

Je propose que le calcul de la consommation de CO2 à LA FABRICATION DE LA VOITURE soit prix en compte.

Quel est le cout environnemental de chaque type de voiture ? Notamment des voitures électriques ? Avec tous ses composants de matières rares, etc. 

Il serait bien de préciser si le coût de fabrication (en CO2 bien sûr) est correctement prit en compte dans le calcul.

Le coût de fabrication en CO2 gris est un facteur très important à prendre en compte pour tout calcul.

**Comment by laem** [comment]
Bonjour, c'est le cas, nous prenons en compte la construction. 
https://nosgestesclimat.fr/documentation/transport/voiture/empreinte/construction-amortie
