### ISSUE TITLE
Pas de choix E85 en motorisation

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1402]
Bonjour, il n'y a pas de choix E85 en motorisation alors qu'il me semble se situer entre l'élec et le thermique, au vue de la proximité de sa production et transformation (betterave-francaise), et aussi du CO2 capté par la plante durant sa croissance. Merci !

Depuis la page : `https://nosgestesclimat.fr/documentation/transport/voiture/motorisation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, nous en parlons ici : https://github.com/datagir/nosgestesclimat/pull/1396
