### ISSUE TITLE
J'ai fait une erreur

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1403]
Je voudrais modifier des réponses car erreur sur la quantité d'essence par an, et je suis bloquée sur le numérique, je ne peux pas réinitialiser le test.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, vous pouvez le faire via la page profil, qui est accessible via le menu en bas (sur mobile) ou à gauche (sur bureau) :)

**Comment by laem** [comment]
Je ferme en attendant d'autres éléments.
