### ISSUE TITLE
modifier des réponses

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1410]
Bonjour, j'ai répondu pour  moi sauf pour la partie vêtements où j'ai comptabilisé la totalité des achats annuels familiaux. Comment puis-je y retourner pour modifier SVP ?

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Vous pouvez visiter la page profil via le menu :)
