### ISSUE TITLE
Amélioration question électroménagers

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#142]
Je suis surpris d'apprendre que beaucoup de maisons sont équipées d'un, voir de deux, congélateurs *en plus* du compartiment congélo du frigo. Idem pour lave vaisselle, machine, sèche linge, etc.

Il va falloir faire une grille de choix, comme pour le numérique #12

**Comment by laem** [comment]
La grille de choix est faite dans #975 :) 

Par contre, on peut ici lister les éléments courants qui manquent à l'appel. 

- congélateur indépendant
- [appareil à raclette](https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=raclette)
- perceuse

[PDF pour quelques durées de vie](https://www.ademe.fr/sites/default/files/assets/documents/evaluation-environnementale-biens-equipement-2019-rapport.pdf).

Nécessite peut-être de diminuer la taille des vignettes.

**Comment by lbranaa** [comment]
Retours/suggestions de nos partenaires suisses : 
- [ ] Mettre un nombre au lieu d'une coche (on peut avoir plusieurs équipements)
- [ ] Changement : au lieu de 10 ans, mettre l'année dernière --> pas sûre que l'on veuille modifier cela

**Comment by Clemog** [comment]
Je ferme au profit de #1728 qui reprend entre autres ces commentaires
