### ISSUE TITLE
Nombre d'enfants

### ISSUE THREAD

**Issue by jyoberle** [datagir/nosgestesclimat#1420]
## Poser une question 

Vous ne posez pas la question du nombre d'enfants : un enfant en plus dans une famille, c'est aussi 58,6 tonnes de CO2 en plus par an (source : https://iopscience.iop.org/article/10.1088/1748-9326/aa7541/meta;jsessionid=BE58B8A7FDC40EF66BE91A2EAF712462.c1.iopscience.cld.iop.org)

## Proposer une amélioration 

Intégrer le nombre d'enfants dans vos calculs : 
1 enfant = 58,6 tonnes de CO2
2 enfants = 117,2 tonnes de CO2
3 enfants = 175,8 tonnes de CO2
etc.

**Comment by laem** [comment]
Bonjour, non ce n'est vraiment pas si simple. Si l'empreinte d'un enfant est attribuée aux parents, alors votre empreinte est celle de vos parents, donc la votre est nulle ;) 

Une bonne lecture sur le sujet : https://medium.com/enquetes-ecosophiques/l-heritage-carbone-n-a-aucun-sens-e2bd030cd2a6

**Comment by laem** [comment]
Je ferme au profit de 984
