### ISSUE TITLE
Mode conférence bug

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1425]
Firefox
Tests de conférence à 2. Envoi du lien aux 2 autres personnes, mais 1 seule a pu rejoindre l'animateur. L'autre est sur une autre conférence

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, quel est le lien de partage ? C’est un mode conférence, pas un mode sondage ?
