### ISSUE TITLE
réponses non labellisées

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1428]
Bonjour, J'utilise le navigateur brave mais le souci vient du fait que plusieurs items ne sont pas labellisées. Je suis aveugle et je n'ai pas accès aux images pour le type de chauffage et les appareils de moinsde 10 ans par ex. J'ai dû arrêter le test. Dommage ☹

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je ferme au profit de https://github.com/datagir/nosgestesclimat/issues/1429
