### ISSUE TITLE
Pouvez-vous rajouter une question qui demanderait combien de bains, combien de douches de 5 min prend-on par semaine ou jour ?

### ISSUE THREAD

**Issue by Cellochoco** [datagir/nosgestesclimat#1432]
## Poser une question 

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by laem** [comment]
Bonjour, c'est inclus dans la facture énergétique, en fonction du chauffage, gaz, élec, etc :)
