### ISSUE TITLE
Manque de précision.

### ISSUE THREAD

**Issue by Gwirionez** [datagir/nosgestesclimat#1446]
Bonjour,

Votre simulation manque de précision pour les véhicules.
Je possède un véhicule GPL et ce carburant n'est pas référence donc je ne peux considérer vos estimations comme fiables.

Cordialement.

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour ! 

Le sujet a déjà été identifié ici #445, le modèle de calcul actuel semble propice à l'ajout du GPL (La base carbone donne : GPL pour véhicule routier 1.86 kgCO2e/litre).

**Comment by laem** [comment]
Je me permets de fermer l'issue pour ne pas garder de doublons
