### ISSUE TITLE
Sauvegarde

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1447]
Bonjour,
Je ne sais pas pourquoi, j'ai perdu toute mes réponses au test visiblement sans possibilité d'y remédier :(
Une fonctionnalité d'export/import dans un fichier serait très utile pour suivre son bilan carbone dans le temps.

Cordialement

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour la remarque. Désolé pour la perte. Avez-vous plus d'informations sur ce qu'il s'est passé ? 
Avez-vous effacé les données de site (cookies etc.) ? Avez vous changé de navigateur ? Fait le test en mode privé ? 

N'hésitez pas à consulter cette issue pour comprendre pourquoi nous ne proposons pas encore de compte utilisateur. 

https://github.com/datagir/nosgestesclimat-site/issues/400
