### ISSUE TITLE
Construction logement ne devrait-elle pas être divisée par le nombre d'habitants du logement

### ISSUE THREAD

**Issue by RenaudRuffiot** [datagir/nosgestesclimat#1456]
Selon les 3 formules ci-après, le nombre d'habitants n'intervient pas dans le calcul de Construction logement. Est-ce que cela ne devrait pas être le cas ?

logement . construction . par surface:
  formule:
    variations:
      - si: éco-construit
        alors: 144 kgCO2e/m2
      - si: appartement
        alors: 525 kgCO2e/m2
      - sinon: 425 kgCO2e/m2

logement . construction . annuelle et par surface:
  formule: par surface / durée d'amortissement
  unité: kgCO2e/m2

logement . construction:
  icônes:
  formule:
    variations:
      - si: âge < durée d'amortissement
        alors: surface * annuelle et par surface
      - sinon: 0

**Comment by laem** [comment]
Bonjour Renaud, normalement la division par le nombre d'habitants se passe tout en haut de l'arbre de calcul logement. 

https://github.com/datagir/nosgestesclimat/blob/master/data/logement/logement.yaml#L11

**Comment by laem** [comment]
C'était bien ta question ?

**Comment by RenaudRuffiot** [comment]
Oui, c'était bien ma question. Tout est clair. Merci.
