### ISSUE TITLE
29 pleins de carburant fossile avec un véhicule électrique

### ISSUE THREAD

**Issue by ViveLevant** [datagir/nosgestesclimat#1461]
Je reste étonné que mes kilomètres en véhicule électrique génèrent un nombre de plein de carburant. c'est un peu contre-intuitif.

## Proposer une amélioration 

Puisque l'énergie électrique est proposée, en faire un multiplicateur par 0 de la quantité de carburant.

**Comment by Clemog** [comment]
Merci beaucoup pour le retour ! C'est corrigé ici : https://github.com/datagir/nosgestesclimat/commit/87bd28b1036b4ab526ece2d1d1c62ee32824024b

Il y avait effectivement une erreur ! Belle journée
