### ISSUE TITLE
Je suis bloquée après chauffage

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1469]
firefox version 104.00

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan?catégorie=services publics`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Fixed by https://github.com/datagir/nosgestesclimat-site/commit/39f52f292c6502ecd5adda659576e3f4017f748f
