### ISSUE TITLE
Consommation véhicule

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1470]
J'ai un véhicule qui fonctionne au GPL qui n'est pas pris en compte dans le test

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
J'ai l'impression qu'on peut facilement le proposer https://github.com/datagir/nosgestesclimat/issues/445, je fais une PR @laem @Benjamin-Boisserie-ABC ?

**Comment by Clemog** [comment]
Je ferme au profit de #445
