### ISSUE TITLE
Bouton suivant ne fonctionne plus

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1471]
Au tiers du test, le bouton suivant n'as plus fonctionné. Impossible de terminer le test ni de revenir au débût.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, avez-vous noté la question qui bloque ?

**Comment by Clemog** [comment]
Fixed by https://github.com/datagir/nosgestesclimat-site/commit/39f52f292c6502ecd5adda659576e3f4017f748f
