### ISSUE TITLE
Aucune question sur mon kilométrage ni sur l'avion

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1474]
Bonjour, je suis en train de passer tous mes déplacements quotidiens au vélo
et j'ai choisi de ne plus prendre l'avion du tout.

Mais aucune question à ces sujets dans le test : on me demande juste le type de carburant de ma voiture. 🤔

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan?catégorie=transport`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Je ne comprends pas trop ce retour ..
