### ISSUE TITLE
j'ai fait la simumation complète et je voudrais coriger la partie logement, mais je n'arrive pas à revenir en arrière sur cette partie

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1479]
Firefox

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci, je ferme au profit de #1480
