### ISSUE TITLE
Le FE du café n'intègre pas la consommation 

### ISSUE THREAD

**Issue by florianpanchout** [datagir/nosgestesclimat#1487]
## Poser une question 

Le [FE utilisé pour le café](https://agribalyse.ademe.fr/app/aliments/18003#Caf%C3%A9,_moulu) n'intègre pas la consommation, contrairement à [celui du thé](https://agribalyse.ademe.fr/app/aliments/18020#Th%C3%A9_infus%C3%A9,_non_sucr%C3%A9)

## Proposer une amélioration 

J'ai l'impression que [ce FE](https://agribalyse.ademe.fr/app/aliments/18004#Caf%C3%A9,_non_instantan%C3%A9,_non_sucr%C3%A9,_pr%C3%AAt_%C3%A0_boire) décrit la "boisson café", c'est à dire une fois préparée. En faisant le même calcul qu'avec le thé (des tasses de 250mg), on obtient [un FE pas très éloigné de l'actuel ](https://divers--monconvertisseurco2.netlify.app/empreinte-carbone/divers/tassecafe).

**Comment by laem** [comment]
C'est une question compliquée : si le café est bu à domicile, la consommation (qui vaut le fait de faire bouillir de l'eau je pense) est déjà incluse dans la facture électrique du logement. S'il est pris dans un café, il est à ajouter. 

Mais clairement, on a ici deux choix différents pour l'inclusion de la consommation. @Clemog tu avais vu cette subtilité ?

**Comment by Clemog** [comment]
Effectivement, je n'avais pas noté cette erreur .. 

2 options pour être cohérent:
- Approximer l'empreinte du thé via la même méthode que pour café (en faisant l'hypothèse que 100% de l'empreinte est liée aux grains de café) en enlevant la part de consommation du FE du thé (30%).
- Utiliser ce FE pour le café comme tu le suggères @florianpanchout : on serait à 0,11 gCO2/tasse (250mg) (0,14 actuellement). A noter que la consommation représente seulement 3% pour une tasse de café vs 30% pour une tasse de thé (logique vu l'empreinte 10x plus faible du thé)

Pour le café, je trouve que c'est mieux de partir sur l'option 1 car souvent j'ai l'impression que la quantité de café est la même dans les tasses mais qu'un café est plus ou moins allongé non ?

**Comment by Clemog** [comment]
Je propose une modif ici : https://github.com/datagir/nosgestesclimat/pull/1494
