### ISSUE TITLE
Je n'arrive pas à revenir en arrière

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1491]
A la fin de la simulation, impossible de revenir en arrière sur les différents thèmes ! 
Utilisation de chrome sur Macbookair / même problème sur iPad 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan?catégorie=transport`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Je ferme au profit de https://github.com/datagir/nosgestesclimat-site/issues/642
