### ISSUE TITLE
Zone rurale pas de transport en commun 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1496]
Vous ne prenez pas en compte la localisation.
Zone rurale de montagne sans teransport en commun, comment faites vous sans voiture. 

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Le test ne se préoccupe pas de la facilité de changement, qui est d'ailleurs très relative, politique voir philosophique.
