### ISSUE TITLE
J'ai une question : y a-t-il une version anglaise (pour partager avec mes collègues néerlandais) ?

### ISSUE THREAD

**Issue by epavot** [datagir/nosgestesclimat#1497]
## Poser une question 

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by laem** [comment]
> Ne devrait-on pas ajouter : combien d'enfant avez-vous ? Cela a un impact enorme en termes de CO2 ? Et aussi quel métier faites-vous ? Car si on travaille pour le climat, cela devrait aussi baisser notre empreinte carbone non ?

C'est hors du périmètre de la compta climat de consommation. N'hésitez pas à aller voir la FAQ qui y répond https://nosgestesclimat.fr/contribuer

> Et aussi vous devriez créer une page instagram pour qu'on puisse partager le lien et se comparer entre amis.

Merci pour la suggestion :)

**Comment by epavot** [comment]
Génial !


________________________________
De : Mael ***@***.***>
Envoyé : mardi 27 septembre 2022 10:37
À : datagir/nosgestesclimat ***@***.***>
Cc : epavot ***@***.***>; Author ***@***.***>
Objet : Re: [datagir/nosgestesclimat] J'ai une question : y a-t-il une version anglaise (pour partager avec mes collègues néerlandais) ? (Issue #1497)


Bientôt ;) Vous pouvez suivre l'avancement de la fonctionnalité sur datagir/nosgestesclimat-site#641<https://github.com/datagir/nosgestesclimat-site/pull/641>
Sinon, considérer qu'en mi-octobre ce sera en ligne.
