### ISSUE TITLE
déplacement pro

### ISSUE THREAD

**Issue by tdeffieux** [datagir/nosgestesclimat#1498]
J'ai bien vu que les déplacements pro ne sont pas a priori pas à compter, c'est qu'ils sont comptabilisés ailleurs hors des 2 tonnes / an ?
Dans mon cas, je suis fonctionnaire, est-ce que c'est déjà comptabilisé dans la catégorie service public ?

**Comment by laem** [comment]
Bonjour, oui c'est théoriquement le cas.

**Comment by laem** [comment]
En pratique, la comptabilité carbone est tellement peu rigoureuse qu'il y a des chances que ce ne soit pas le cas.

Et puis si vous avez une influence directe sur ces transports (droit de refuser des séminaires en avion inutiles par exemple), libre à vous de les inclure dans "votre" bilan :) La plupart du temps c'est ni noir ni blanc.

**Comment by lbranaa** [comment]
Je ferme, réponse proposée par @laem + une réponse est également disponible dans la FAQ sur la question des déplacements professionnels.
