### ISSUE TITLE
Mauvais texte pour la question "énergie"

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1499]
Je me rend compte qu'on fait une erreur dans la question, ça devrait être "quels types d'énergie utilisez-vous ?"

Car le gaz des plaques de cuisson et surtout le chauffage de l'eau c'est pas considéré comme "chauffer mon logement" :fearful: 

-----------
![image](https://user-images.githubusercontent.com/1177762/192475995-621f2b02-5056-4441-b30b-d29b2fea23bf.png)

**Comment by Clemog** [comment]
Il y a un problème avec l'électricité du coup ...

**Comment by laem** [comment]
Oui, sa présence ne sert à rien du coup ici, si ?

**Comment by Clemog** [comment]
On a besoin de cette information pour les actions notamment et pour savoir si une part de l'électricité sert au chauffage pour attribuer la bonne valeur par défaut pour l'électricité

**Comment by laem** [comment]
Est-ce qu'on peut pas simplement changer le label de la question électricité pour "Chauffage électrique" ?

**Comment by Clemog** [comment]
> Est-ce qu'on peut pas simplement changer le label de la question électricité pour "Chauffage électrique" ?

Comment ça ?
