### ISSUE TITLE
Conférence chargement du modèle de calcul

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1501]
Bonjour je suis sur microsoft Edge sur un Mac. Lorsque je veux créer une conférence pour faire le test en groupe jamais aucun test n'apparait sur mon ordinateur ni sur celui des personnes de mon groupe. Il est affiché "chargement du modèle de calcul" tout le temps.

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
C'est peut-être spécifique à Edge/Mac. à tester, je n'arrive pas à reproduire chez moi.

**Comment by laem** [comment]
Résolu.
