### ISSUE TITLE
Le test ne se lance pas

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1507]
Bonjour, quelque soit l'appareil utilisé (smartphone android ou PC windows 10) et le moteur de recherche (Firefox, chrome, autres) le test ne se lance jamais. il reste écrit "chargement du modèle de calcul" et rien d'autre.
Je ne suis pas la seule dans ce cas dans mon entourage.
Merci d'avance de ce que vous pourrez faire

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci pour le retour ! Voir  #1513
