### ISSUE TITLE
Impossible d'utiliser NGC

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1509]
Bonjour,
on dirait que "Nos Gestes Climat" ne fonctionne pas.
Les pages "Le test", "Agir" et "Mon profil" affichent toutes le message "Chargement du modèle de calcul" puis plus rien.
Quand je change de navigateur ou que je passe en navigation privée, la page d'accueil de NGC affiche une infobulle 
"Nouveautés 
Mise à jour le Invalid Date 
Version Fake Release"
Essayé sur mon laptop Firefox 104, Edge 105 et Chrome 106
Essayé sur mon smartphone Android Chrome 105
Essayé sur d'autres ordis et smartphones autour de moi...

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci pour le retour ! Voir https://github.com/datagir/nosgestesclimat/issues/1513
