### ISSUE TITLE
Type de banque 

### ISSUE THREAD

**Issue by Melfauche89** [datagir/nosgestesclimat#1510]
## Proposer une amélioration 

Je comprends que le partie service public soit global pour tout le monde. Mais je trouverai intéressant qu'on prenne en compte le type de banque (éthique ou "traditionnelle") que l'on a dans le calcul de notre emprunte carbone

**Comment by laem** [comment]
Bonjour, nous avons répondu à cette question dans la FAQ https://nosgestesclimat.fr/contribuer
N'hésitez pas à rebondir après l'avoir lue. Je ferme le ticket mais nous pouvons continuer à en discuter :)
