### ISSUE TITLE
Impossible de faire le test

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1512]
Bonjour, lorsque je veux faire le test, la page indique "Chargement du mode calcul" sans résultat.
Autant sur PC Windows, Microsoft et Chrome que sur gsm Android.....
Merci 

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je ferme au profit de  #1513
