### ISSUE TITLE
(bug) Question climatisation 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat#1514]
La question sur la climatisation n'apparaît pas dans le test NGC (modèle Guadeloupe & France)

**Comment by Clemog** [comment]
Je l'ai bien pour la France métropolitaine pourtant

**Comment by Clemog** [comment]
C'est bon : https://github.com/datagir/nosgestesclimat/pull/1339/commits/76febb99ac50f3dd988932f4c8a9965abf19293b
