### ISSUE TITLE
Bouton "recommencer" pas trouvé

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1518]
bonjour, je souhaiterais refaire le test (ou permettre à d'autres personnes de mon foyer de le faire sur mon ordinateur) mais je ne parviens pas à réinitialiser le formulaire (effacer les données déjà renseignées pour recommencer). Merci d'avance pour votre aide.
J'utilise Firefox

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
J'avoue que je ne sais pas comment rendre plus évidente que ça la modification des données. Il y a un bouton profil, un nouvel écran pour chaque catégorie terminée pour afficher un bouton de modification du profil, et un autre bouton en fin de simulation... 

https://github.com/datagir/nosgestesclimat-site/pull/677

**Comment by laem** [comment]
Si quelqu'un d'autre à une idée, n'hésitez pas ^^

**Comment by Clemog** [comment]
Fermé au profit de https://github.com/datagir/nosgestesclimat-site/issues/790
