### ISSUE TITLE
Transport: Véhicule électrique

### ISSUE THREAD

**Issue by Noil66** [datagir/nosgestesclimat#1524]
## Poser une question 

*Dans la section transport en voiture, impossible de sélectionner un véhicule électrique, je me retrouve donc avec 15 pleins de pétroles alors que je n'en fait aucun!*

## Proposer une amélioration 

*Ajouter la possibilité de sélectionner une voiture électrique lorsqu'on saisi un nombre de km*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by YSavanier** [comment]
Bob

**Comment by YSavanier** [comment]
OK le sujet est traité dans la #966

**Comment by laem** [comment]
Tout à fait, c'est un défaut de notre côté, bien vu pour le ticket :)
