### ISSUE TITLE
Enlever le thé

### ISSUE THREAD

**Issue by Floraine-coach-CO2** [datagir/nosgestesclimat#1529]
Bonjour,

J'ai regardé en détail l'impact du thé, du café et du chocolat.
Alors que le café et le chocolat ont effectivement des impacts vraiment non négligeables, le thé en revanche a une contribution ridiculement faible.

Comme les utilisateurs ne vont pas regarder le détail des chiffres, je trouve dommage qu'on mette le thé comme étant l'un des facteurs sur lesquels on peut jouer pour baisser ses émissions de CO2, alors que ce n'est pas le cas.

Je suggère donc d'enlever le thé et de laisser les deux autres.

Merci
Floraine

**Comment by laem** [comment]
Merci pour la remarque. Nous avons déjà fait l'expérience sur un sujet autre : le vélo et la marche. 

Quand nous n'avions pas la question, des dizaines d'utilisateurs nous ont demandé "pourquoi vous ne me demandez pas combien d'heures de marche je fais par semaine" ? 

De la même façon, en ne proposant que café et lait chaud, nous aurions des tas de messages étonnés, car les gens sont très curieux de leur empreinte, même sur des choses qu'on sait a posteriori insignifiants. 

> Comme les utilisateurs ne vont pas regarder le détail des chiffres,

Normalement l'interface intéractive permet justement de constater que le thé n'a que très peu d'influence :)

Je me permets donc de fermer le ticket, mais n'hésite pas si tu as d'autres élément à partager sur le sujet.
