### ISSUE TITLE
Prendre en compte les véhicules GPL

### ISSUE THREAD

**Issue by fbaldo31** [datagir/nosgestesclimat#1534]
## Est-il prévu de prendre en compte les véhicules GPL ?

Il me semble que les véhicules GPL rejette 2 fois moins de CO² que les véhicules essence. Il pourrait donc être intéressant de les prendre en compte.

**Comment by laem** [comment]
Bonjour, oui nous avons déjà considéré cette possibilité, cf #445, je ferme au profit de cette issue déjà ancienne.
