### ISSUE TITLE
Transport par ferry

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1541]
Salut,
Est-il possible d'intégrer le transport par ferry ? 
Bon Pote a récemment sorti un calculateur en PubliCode (avec Datagir), cela vaudrait le coup d'intégrer le calcul à Nos Gestes Climat.

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre remarque ! C'est un sujet identifié, je ferme au profit de #1548
