### ISSUE TITLE
Zéro déchet ou 100% déchet

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1543]
Salut,
Serait-il possible d'avoir un entre-deux pour les déchets : pas forcément "zéro déchet" mais "démarche engagée" sans être totalement zéro déchet (par exemple "j'ai réduit mes déchets sans être à 100% zéro déchet"). Merci

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, nous avons longuement réfléchi à cette question, pour le moment, il a été décidé de ne pas proposer d'intermédiaires, l'intermédiaire étant défini par la question suivante sur les "éco-gestes" :) (Voir https://github.com/datagir/nosgestesclimat/pull/1415)
