### ISSUE TITLE
pas de questions sur l'isolation, ni la production d'électricité par panneaux 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1546]
en effet dans votre questionnaire, rien sur l'isolation des plafonds, murs, fenêtres, volets, aeration l'été avec fenêtres oscilobattantes la nuit et accumulation de l'air frais pour la journée 23° pour 35-38° dehors (fenêtres fermées et ombres au sud, production par panneaux solaires 8 MKWH en 2022 (estimés sur les deux derniers mois à 500kwh), ombre au sud; 

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, c'est dans la partie action que tout ceci pourrait figurer. Malheureusement, ce n'est pas notre priorité encore pour l'instant. Merci pour les idées :)
