### ISSUE TITLE
pas d'affichage collectif des résultats

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1547]
Bonjour, 

Nous avons testé les deux modes ocnférence et sondage dans l'optique d'une atelier jeudi. 
Seuls les résultats du participants créateur de la conférence apparaissent. LEs résultats des autres participants n'apparaissent pas.... 
Faisons-nous une erreur de manipulation ou est-ce que ça vient de l'outil? 
Nous sommes sur firefox et android/windows

Merci pour votre aide. 

Cordialement, 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
A priori, on ne pourra pas répondre à la personne ..
A nouveau un bug sur les 2 modes groupe @laem 

Je ferme au profit de #1537
