### ISSUE TITLE
la page se recharge sans explication

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1551]
ETQ utilisateur de la plateforme qui souhaite faire un test
When Au cours du test la page se recharge sans plus d'explications

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Le bug peut provenir d'une surchage de mémoire sur un vieil appareil ?
