### ISSUE TITLE
Arrêter de fumer

### ISSUE THREAD

**Issue by OliC-BE** [datagir/nosgestesclimat#1554]
Bonjour,

Désolé du doublon... Lisant sur l'empreinte carbone du tabac, je me disais que nous ne pouvions pas passer à côté d'un calcul...
https://www.who.int/fr/news/item/31-05-2022-who-raises-alarm-on-tobacco-industry-environmental-impact

https://www.greenly.earth/blog-fr/quelle-est-l-empreinte-carbone-de-l-industrie-du-tabac#:~:text=Une%20cigarette%20c%27est%20%3A,et%20de%20l%27oxyde%20nitreux.

En espérant la graine inspirante.

Merci

**Comment by Clemog** [comment]
Merci pour le retour ! Effectivement c'est un sujet identifié ! https://github.com/datagir/nosgestesclimat/issues/135, nous allons priorisé cette issue prochainement !
