### ISSUE TITLE
Plein de fautes d'orthographe !

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#1555]
Sur la page "https://nosgestesclimat.fr/nouveaut%C3%A9s/guadeloupe", je note "les principales particularité" manque le "s". "qu'y a la climatisation" -> 'qu'a la clim...", "qui ne veulement pas d'embêter" -> "qui ne veulent pas s'embêter".

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
C'est corrigé merci !
