### ISSUE TITLE
Vélo électrique et trottinette

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1557]
https://bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=v%C3%A9lo
Trottinette aussi. 
Voir comment intégrer le vélo simple. 
Estimer la consommation annuelle d'un vélo électrique sans demander les km (relou) ? 

#914

**Comment by mquandalle** [comment]
S'il y a un lien direct vers un sous-simulateur vélo, je l'intègre sur mesaidevelo :)

**Comment by lbranaa** [comment]
#914
