### ISSUE TITLE
Oser évoquer l'empreinte écologique des êtres vivants liés - enfant/animaux

### ISSUE THREAD

**Issue by OliC-BE** [datagir/nosgestesclimat#1580]
Initialement, j'étais pour proposer d'ajouter qq questions pour regarder du coté de l'alimentation des animaux domestiques.
Le régime d'un chien ou chat ne doit pas être négligeable à l'échelle "individuel".

En fait, peut-être pourrait-il aussi y avoir une question pour faire le calcul de l'empreinte écologique de son/sa conjointe ou ses enfants... (et avoir un peu plus de finesse que juste multiplier son chiffre par le nombre d'occupant du ménage)...

Il est sans doute vrai que l'électricité d'un aquarium se répercute dans les factures... mais souvent se sont aussi des produits (installation/ entretien) qui ont leur empreinte écologique aussi.

Merci pour votre attention/ considération

**Comment by laem** [comment]
Bonjour, 

Merci pour votre retour. En effet, nous avons prévu d'ajouter les animaux domestiques. Voir https://github.com/datagir/nosgestesclimat/issues/35

Nous n'avons pas prévu encore de faire un mode de simulation où on répond pour l'ensemble du foyer, mais c'est une idée déjà évoquée plusieurs fois également. 

Au sujet de l'aquarium : je note :) 

Cordialement
