### ISSUE TITLE
Sauvegarde profil temporel

### ISSUE THREAD

**Issue by aguerin55** [datagir/nosgestesclimat#1587]
Bonjour,

Je viens de faire mon test avec des données peut-être un peu grossières. Je voudrais faire des modifications et de faire d'autres saises (semi-annuel ou annuel) pour voir mes améliorations dasn le temps.

Commen récupérer mes données de saisies et calcul associé par un fichier (à éviter le Cloud je présume).

Salutations.

**Comment by Benjamin-Boisserie-ABC** [comment]
Bonjour @aguerin55

Nous ne donnons pas (actuellement) la possibilité de récupérer les données saisies. Cependant, si vous revenez sur la page nosgestesclimat, les résultats de votre dernière simulation seront accessibles du fait des cookies de votre navigateur.

Concernant l'aspect temporel et de suivi dans le temps de votre empreinte, nous prenons en compte votre retour. Sachez que nous réfléchissons à mettre en œuvre un éventuel suivi.

Cordialement,

Benjamin

**Comment by laem** [comment]
J'ajoute un lien vers nos réflexions au sujet du stockage des simulations sur un compte personnel : https://github.com/datagir/nosgestesclimat-site/issues/400
