### ISSUE TITLE
Air travel describes flying in france

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1593]
Why describe “hours in France” and “hours in Europe,” etc? Why not just ask how many km flying per year? The first question phrasing can’t be answered by those living outside France, but distance can be answered by anyone
> This ticket was created automatically by our robot from our [contribution page for translation](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by laem** [comment]
Because the model is specific to France. It can be used by english speakers living in France, but not people from the United States for example. 
This will change once we at least internationalise the electricity mix factors.
