### ISSUE TITLE
Smartphone is not translated

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1595]
La reponse sur les smartphone / type de telephone n'est pas traduite en anglais

Ce serait top aussi d'avoir les distances en miles et pas seulement km, et rendre les questions de transport plus generiques (par exemple "trajets en France" => "trajets a moins de 5h de route ou 1000 km") pour que ca puisse s'appliquer a d'autres pays
> This ticket was created automatically by our robot from our [contribution page for translation](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by laem** [comment]
> les questions de transport plus generiques (par exemple "trajets en France" => "trajets a moins de 5h de route ou 1000 km") pour que ca puisse s'appliquer a d'autres pays

Oui, seulement une fois que l'on aura internationalisé au moins le facteur d'émission du mix électrique. En attendant c'est bien que l'on montre que le calcul se fait en France, malgré la langue anglaise.

**Comment by EmileRolley** [comment]
Closed by #1596
