### ISSUE TITLE
compter les animaux domestiques

### ISSUE THREAD

**Issue by yl3331** [datagir/nosgestesclimat#1598]
Puisque l'alimentation a un impact important, ça serait bien de comptabiliser celle de nos animaux domestiques : j'imagine que l'impact sera très différent selon que j'ai seulement une souris blanche, ou 3 gros chiens de 40 kilos.
Voir par exemple cet article : https://www.sudouest.fr/environnement/animaux/environnement-quel-est-l-impact-de-vos-animaux-de-compagnie-sur-la-planete-1756503.php
L'étude citée semble ne s'intéresser qu'à la portion de viande des aliments pour animaux, alors qu'un grande partie de aliments pour chiens est constituée de végétaux (céréales).

**Comment by laem** [comment]
Merci pour votre retour, c'est prévu :) 

https://github.com/datagir/nosgestesclimat/issues/35
