### ISSUE TITLE
Connexion

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1599]
The link to my group test is broken
> This ticket was created automatically by our robot from our [contribution page for translation](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by laem** [comment]
What was the link to your group test ? If private, send it by ✉️ to contact AT   nosgestesclimat.fr

To be followed, too few information to make it a bug yet.

**Comment by EmileRolley** [comment]
Response #1601
