### ISSUE TITLE
carburant GPL manquant

### ISSUE THREAD

**Issue by e-redondo** [datagir/nosgestesclimat#1603]
## Poser une question 

Dans la partie voiture, le carburant GPL n'apparaît pas. Ce carburant est de plus en plus présent.

## Proposer une amélioration 

Serait-il possible d'ajouter le GPL?
Il faudrait dans ce cas prendre en compte aussi le double réservoir (souvent essence + GPL), avec estimation des kilomètres fait dans l'un et dans l'autre...

**Comment by Clemog** [comment]
Bonjour merci pour votre retour ! 
Le sujet est identifié ici : #445 
Je n'avais pas en tête le "double réservoir", sujet à investiguer au niveau du facteur d'émission lui-même à priori
