### ISSUE TITLE
Pas d’option pour avancer

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1605]
Quelle est votre consommation de boissons chaudes pour une semaine type (nombre de tasses par semaine)?
Les seuls choix proposés une fois qu’on a saisi les infos sont « Précédent » ou « Je ne sais pas ». Impossible de valider sa saisie !!!
L’IHM de ce site est mal conçue.
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, 
Quand vous saisissez une valeur, cliquez sur + ou -, ou sur une suggestion, le bouton "Suivant" apparait. 

Pouvez-vous réessayer et nous dire précisément comment vous avez saisie vos consommations de boissons chaudes ? 

Je ferme en attendant plus d'informations (issue relevée qu'une fois).
