### ISSUE TITLE
sondage en groupe

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1613]
Les textes explicatifs pour faire les sondages en groupe sont bourrés de fautes, les liens pour ajouter des questions renvoient à des pages inexistantes, impossible à utiliser
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, quelles fautes avez-vous repérées ? Quels liens sont cassés ?
