### ISSUE TITLE
Accès au résultat d'un groupe

### ISSUE THREAD

**Issue by PhilLAL** [datagir/nosgestesclimat#1618]
Bonjour,
merci pour ce site, qui ne se concentre pas que sur le négatif !

Lorsqu'on arrive par un lien d'un sondage en groupe, qu'on a déjà rempli, on ne voit pas le résultat du groupe.

Peut-on y mettre un lien explicite pour y accéder ?

**Comment by laem** [comment]
Bonjour PhiLAL, est-ce que tu aurais une capture d'écran pour nous montrer l'état du site sur lequel tu arrives ?

**Comment by laem** [comment]
Je ferme en attendant plus d'informations de votre part.

**Comment by PhilLAL** [comment]
Voici
![nosgestesclimat sans accès sondage de groupe](https://user-images.githubusercontent.com/10073821/207017947-1ee69b8f-bd9b-4a91-934e-dcafb55deb47.png)

**Comment by laem** [comment]
Tu n'as pas le bloc "Participer au sondage" ? 

![image](https://user-images.githubusercontent.com/1177762/207655642-50667572-dfc9-4b46-be70-439112a05dae.png)
