### ISSUE TITLE
Vacation : "non" button

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1620]
Believe it or not, many people in the world (like myself) don't take vacations away from our own home.

This is for financial reasons, for environmental reasons, for disability reasons, & (very frequently) for a combination of 2 or more of those reasons.

'None' appears as a choice for the 'Vacations' section, yet it's impossible to select, & should definitely be an option!
> This ticket was created automatically by our robot from our [contribution page for translation](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by laem** [comment]
Hi, it is indeed possible to select "None" :) 


![image](https://user-images.githubusercontent.com/1177762/207654605-4bd09e74-f716-4d1c-9876-642f21fe1567.png)

Did you see this button ? It could be that we have a bug.
