### ISSUE TITLE
Erreur d'affichage bilan -> Services sociétaux

### ISSUE THREAD

**Issue by Sekiltoyai** [datagir/nosgestesclimat#1628]
Sur la page https://nosgestesclimat.fr/documentation/bilan à l'issue d'un calcul, le détail du bilan des Services sociétaux. est affiché en ktCO2e au lieu de kgCO2e.

1. Dans l'encart "Comment cette donnée est-elle calculée ?"
2. Sur la ligne "Services sociétaux" (le total est correctement affiché en kgCO2e)
3. Cliquer sur "déplier"

Une fois déplié : 
- La ligne "Services publics" affiche un total en ktCO2e alors qu'il devrait afficher un total en kgCO2e.
- La ligne "Services marchands" affiche un total en ktCO2e alors qu'il devrait afficher un total en kgCO2e.
- La somme des lignes "Services publics" et "Services marchands" affiche un total en ktCO2e alors qu'il devrait afficher un total en kgCO2e.

**Comment by Clemog** [comment]
Merci beaucoup ! Il est effectivement nécessaire de mieux gérer les unités du calcul. C'est également l'occasion d'ajouter les descriptions manquantes pour les nouvelles variables associées au calcul !

**Comment by Clemog** [comment]
@Sekiltoyai êtes vous parvenu à naviguer facilement dans la documentation ? Avez-vous compris le principe de calcul facilement ?

**Comment by Sekiltoyai** [comment]
@Clemog Dans l'ensemble je trouve le principe d'une documentation "data-driven" plutôt malin et bien foutu. Donc personnellement je trouve ça clair, mais je suis informaticien donc mon opinion n'est probablement pas représentative...

Dans les détails de la navigation et de l'affichage, cela m'a pris du temps à comprendre comment naviguer entre le bilan du test et la documentation.
* C'est à dire qu'en cliquant sur le bloc "Logement" par exemple, on obtient le calcul pour toutes les sources du logement, tandis qu'en cliquant sur le bloc "Construction", on obtient uniquement le calcul pour la construction (sachant qu'on doit naviguer dans la variable "Impact" pour avoir la décomposition).
* Le bloc "Divers" est beaucoup plus lisible, puisqu'on a une liste d'éléments qu'on peut déplier. Il serait plus lisible d'organiser la documentation des autres blocs sous la même forme.
* On peut perdre le résultat de son test à force de naviguer dans la documentation (je ne sais pas si c'est en ouvrant des onglets ou autre)

Personnellement les calculs m'intéressent parce que j'essaye de voir s'il est possible construire un fichier excel de "compta carbone" (sur la base des mêmes calculs/données ou des sources externes référencées par NGC) pour suivre des émissions de manière plus régulière (en considérant par exemple que 1€ dépensé dans un commerce de tel ou tel type (boulangerie, charcuterie, primeur) aura un coefficient d'émission moyen correspond à ce qu'on achète dans ce commerce). Et de manière globale toute émission peut être calculée par un nombre d'euros dépensés x un coefficient d'émission par euro.

**Comment by laem** [comment]
Merci pour les retours ! On a en effet beaucoup de travail pour améliorer la documentation. On n'a jamais entreprit de réel travail de design spécifique à notre projet, la documentation étant automatiquement générée par publicodes. 

C'était le but du travail sur cette page, mais il s'agit seulement de la racine. 

![image](https://user-images.githubusercontent.com/1177762/210366389-b553bda4-934a-4aaf-96b4-b5758cb23a13.png)

**Comment by laem** [comment]
> Et de manière globale toute émission peut être calculée par un nombre d'euros dépensés x un coefficient d'émission par euro.

Attention tout de même à éviter les effets négatifs de la comptabilité par coefficient financier, en premier lieu l'effet qualité, mais aussi les achats d'actifs (acheter un appartement à 200k€ sans y faire de travaux n'émet rien ou presque). 

Voir par exemple cet article (section 4.1) https://www.cairn.info/revue-de-l-ofce-2020-5-page-73.htm ainsi que ma critique de l'article https://hackmd.io/@laem/critique-de-qui-emet-du-co2

**Comment by Sekiltoyai** [comment]
> > Et de manière globale toute émission peut être calculée par un nombre d'euros dépensés x un coefficient d'émission par euro.
> 
> Attention tout de même à éviter les effets négatifs de la comptabilité par coefficient financier, en premier lieu l'effet qualité, mais aussi les achats d'actifs (acheter un appartement à 200k€ sans y faire de travaux n'émet rien ou presque).
> 
> Voir par exemple cet article (section 4.1) https://www.cairn.info/revue-de-l-ofce-2020-5-page-73.htm ainsi que ma critique de l'article https://hackmd.io/@laem/critique-de-qui-emet-du-co2

Oui, bien sûr. Par coefficient financier, je pense surtout aux dépenses courantes/quotidiennes.

Pour les dépenses importantes (e.g. appartement) ou les abonnements énergie (gaz, électricité, eau), on le fait assez peu souvent pour pouvoir le considérer qualitativement (sachant qu'en fonction de son prix d'énergie, le coefficient fluctue). Par contre pour les dépenses quotidiennes c'est plus facile, quand on fait déjà sa compta financière mensuelle, de fonctionner sur la base des dépenses que sur une base qualitative (nombre de kilos achetés de chaque type de produits).

Donc en réalité je suis plus parti sur un modèle hybride.
