### ISSUE TITLE
Mon empreinte carbone 

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1629]
L’empreinte à atteindre de 2tonnes par an correspond à celle des services publics ; il faudrait donc que je ne consomme rien pour atteindre le résultat demandé ; il faudrait donc que je sois mort! Et encore là je n’y arriverais pas puisque les services des cimetières ont eux aussi une empreinte! Les vivants et les morts contribuent tous au changement climatique : il n’y a rien à faire! La solution est donc à  hercher ailleurs : il faut se démener !
> Depuis la page: `https://nosgestesclimat.fr/documentation/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour votre message. Nous tentons de répondre à ce commentaire dans [notre FAQ](https://nosgestesclimat.fr/contribuer#:~:text=Pourquoi%20cet%20objectif%20de%202%20tonnes%20%3F%20C%27est%20super%20ambitieux%20!) et plus récemment dans cette issue #1625 :)
