### ISSUE TITLE
suite bloquée aux services publics

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1630]
bonjour, je ne parviens pas à accéder au bouton suivant au moment du calcul de l'utilisation des services publics, je ne peux accéder à la suite et progresser davantage
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
C'est à dire ? Voyez-vous toujours le bouton "je ne sais pas" ou bien "suivant" ?

**Comment by Clemog** [comment]
Je ferme, ne pas hésitez à ré-ouvrir si besoin !
