### ISSUE TITLE
Taille du groupe pour une utilisation en groupe

### ISSUE THREAD

**Issue by AgnesG44** [datagir/nosgestesclimat#1632]
## Poser une question 

Je voudrais utiliser votre calculateur pour un groupe supérieur à 100 étudiants, est-ce qu'il y a une limite technique à cette utilisation en simultané pour un même groupe en temps réel ?

Merci par avance pour votre réponse

Agnès Giffard

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by Clemog** [comment]
Bonjour @AgnesG44, il n'y aura pas de problème pour un groupe de cette taille. N'hésitez pas à utiliser le mode "sondage" car le réseau internet de certains établissements bloquent parfois le mode conférence (qui utilise le peer to peer).

**Comment by Clemog** [comment]
Je ferme l'issue, n'hésitez pas à nous faire un retour à la suite de votre utilisation de Nos Gestes Climat en mode groupe
