### ISSUE TITLE
Suggestion action "Remplacer la voiture par le train"

### ISSUE THREAD

**Issue by Agneschapelain** [datagir/nosgestesclimat#1640]
bonsoir,
pourriez-vous ajouter une action à fort impact pour réduire ses émissions de CO2 : comme il existe déjà "remplacer l'avion par le train" proposer également "remplacer la voiture par le train" ? L'enjeu est encore plus majeur.
Merci

Agnès Chapelain

**Comment by Clemog** [comment]
Merci pour le retour ! C'est noté dans #695, ce sera priorisé prochainement ! N'hésitez pas à ouvrir à nouveau si vous souhaitez continuer la discussion.
