### ISSUE TITLE
my house is 45 years olb, but externally isolated since. No option was shown for it

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1643]
&gt; This ticket was created automatically by our robot from our [translation contribution page](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by Clemog** [comment]
Hi, thank you for your feedback. The age of your house is used only to calculate the part of construction attributed to your yearly carbon footprint, your isolation will be taken into account in your energy bills.
