### ISSUE TITLE
Précisions chauffage collectif

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1645]
You do not seem to have a way to take into account those of us who are living in  multi-apartment buildings with central building heating . Neither  di you seem to take into account the heat leaking levels or the geographical zones.  
&gt; This ticket was created automatically by our robot from our [translation contribution page](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by Clemog** [comment]
Hi, thank you for you feedback. For now, we only give an averaged energy consumption based on French statistics (https://nosgestesclimat.fr/documentation/logement/chauffage).
We could try to alert users information about the access of energy bills

**Comment by Clemog** [comment]
- [ ] Ajouter une phrase ou une notification dans la partie info pour alerter l'utilisateur sur l'accès aux factures d'électricité
