### ISSUE TITLE
https://nosgestesclimat.fr/contribuer

### ISSUE THREAD

**Issue by Guilhem67** [datagir/nosgestesclimat#1647]
## Poser une question 

Simu réalisée au jour de l’envoi du mail : cette simu est BIDON.

Je consomme 7691kWh élec + 3600 kWh bois (2x600kgx3kWh) = 11291kWh (40%)
Ma voiture consomme 200*6,7*10=13400 kWh
A/C 12hx600km/100*3,5*10=2520 kWh
(11291+13400+2520=27211)

Ma conso maison représente 40% de ma conso déplacement, OR sur le site c’est 2% (1 carré pour 51 carrés)!!!

## Proposer une amélioration 

revoir le calcul qui se trouve derriere le simulateur!

**Comment by Clemog** [comment]
Je ferme cette issue, n'hésitez pas à nous écrire sur cette issue pour échanger davantage.
