### ISSUE TITLE
Bug version Guadeloupe page blanche fin de test

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1649]
Firefox mobile, Android Note 10+
Après avoir terminé les questions sur les aliments, impossible de poursuivre, écran blanc, même après rafraîchissement.
Bêta Guadeloupe.
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Remontée d'un bug à gérer rapidement, surement lié au renommage de certaines règles, notamment les services sociétaux, appelées depuis le site
