### ISSUE TITLE
consomation par défaut en chauffage fioul d'un vieil appartement

### ISSUE THREAD

**Issue by Marc-marc-marc** [datagir/nosgestesclimat#1651]
Comment est estimé la consommation chauffage par défaut d'un logement ?
un appartement de 1986, vieux de 36 ans 112m2 fioul fournit la valeur par défaut de 11 965 litres
soit une consommation supérieure à 100 000 kWh/an et supérieur à 1000 kWh/m2/an soit un DPE G très prononcé.

selon [notre-environnement.gouv.fr](https://notre-environnement.gouv.fr/actualites/breves/article/performance-energetique-des-logements-les-estimations-selon-le-nouveau-dpe) seul 6% des appartements sont en DPE G, 4% des logements de plus de 100m2, 2% selon son age.
Même les stats basé sur le type de combustible fioul donne un médiane en classe F

Tout cela pour dire que la valeur par défaut me semble très pessimiste sur ce point

PS: pour l'anecdote la consommation estimée est de 6000 litres pour 8 appartement soit un facteur 10x inférieur à la valeur par défaut malgré une consigne en surchauffe (23°)

**Comment by Clemog** [comment]
Bonjour @Marc-marc-marc ! Effectivement, il semble qu'il y a un problème dans notre calcul de cette valeur, merci pour votre retour précieux, nous allons travailler dessus très rapidement !

Pour info, la documentation du calcul est accessible ici : https://nosgestesclimat.fr/documentation/logement/chauffage/fioul/consommation

Il semble que c'est un problème d'unité, merci !
