### ISSUE TITLE
suggestion incorrecte de rénover un logement passif en BBC

### ISSUE THREAD

**Issue by Marc-marc-marc** [datagir/nosgestesclimat#1655]
En encodant un logement passif (la norme la plus aboutie d'efficacité énergétique d'un logement), il propose comme action de le rénover en bâtiment base consommation (norme moins poussée) ce qui n'a évidement pas de sens.

Suggestion : ne pas proposer cette action lorsque la consommation énergétique totale du logement est inférieur à la limite BBC

**Comment by lbranaa** [comment]
Bonjour Marc,
Merci beaucoup pour votre retour très pertinent ! J'intègre cela à une issue plus large de refonte de la partie actions (https://github.com/datagir/nosgestesclimat-site/issues/714). Proposer des actions pertinentes en fonction des réponses de l'utilisateur est en effet un point très important, comme vous le montrez ici avec le logement.
Bonne journée,
Laurène

**Comment by lbranaa** [comment]
Je ferme au profit de https://github.com/datagir/nosgestesclimat-site/issues/714.
