### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CathyBouAgape** [datagir/nosgestesclimat#1660]
Je rencontre un problème sur le sondage osmose-and-co mes résultats 5,2tonnes ne s'enregistrent pas et les résultats ne s'affichent pas sur la page.
merci de votre aide.
j'anime une conférence vendredi matin, je dois être prète jeudi après midi.

Merci d'avance
Cathy Bou

**Comment by Clemog** [comment]
Bonjour,

Je vois seulement un sondage au nom de "bni-osmose-and-co", est celui-ci ? https://nosgestesclimat.fr/sondage/bni-osmose-and-co

<img width="917" alt="image" src="https://user-images.githubusercontent.com/55186402/212040114-f5bfb488-da08-4eb0-bae8-b420fb10da04.png">

**Comment by CathyBouAgape** [comment]
Bonjour

oui le bug est réparé merci.

bien à vous
Cathy Bou
*Agapé*
06 50 41 89 21
www.agape-rse.com
