### ISSUE TITLE
Bug emoji page d'accueil

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat#1664]
L'emoji pour la brique "le code source est ouvert" n'apparait pas, on voit un point d'interrogation à la place.

![Capture d’écran 2023-01-16 à 11 32 56](https://user-images.githubusercontent.com/120486950/212693931-f119fa04-2ffc-455d-a695-ae0979abe821.png)

**Comment by laem** [comment]
Je ferme au profit de https://github.com/datagir/nosgestesclimat-site/issues/816
