### ISSUE TITLE
Ambiguïté dans les services sociétaux : génie civil

### ISSUE THREAD

**Issue by Marc-marc-marc** [datagir/nosgestesclimat#1670]
La page du test à propos du services sociétaux liste 2x le génie civil.

**Comment by Clemog** [comment]
Merci pour la remarque, nous sommes partis des décompositions par branches économiques (méthode ici : https://github.com/datagir/nosgestesclimat/wiki/Guide-technique-services-soci%C3%A9taux). Nous allons modifier le titre pour préciser ces postes et éviter les ambiguités

**Comment by Clemog** [comment]
Je précise ma réponse :

Nous avons travaillé sur 2 branches différentes (code F42 et F43) dont les contenus d'activités sont précisées ici :

https://nosgestesclimat.fr/documentation/empreinte-branche/F42
https://nosgestesclimat.fr/documentation/empreinte-branche/F43

**Comment by Clemog** [comment]
Le titre a été modifié, il semble que "Génie civil" comprend la partie "construction" uniquement : ex: construction d'une route alors que la partie "travaux divers" prend en compte la mise en place d'éclairage ou encore des barrières.
