### ISSUE TITLE
Evaluation des nuitées hors logement

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat#1674]
Cette issue pour explorer l'évaluation GES des nuitées ayant lieu en dehors du logement (i.e. consommation d’hôtellerie).

### Source 
Je me base sur le travail de l'initiative Hotel Carbon Measurement Initiative (HCMI) qui alimente le Cornel Hotel Sustainability Benchmarking Index. Cet index met à disposition des informations carbone, eau et énergie fournies par les hôtels participant à l'initiative. 
[Hotel Sustainability Benchmarking Index 2021.xlsx](https://github.com/datagir/nosgestesclimat/files/10435863/Hotel.Sustainability.Benchmarking.Index.2021.xlsx)

A titre d'info, cet outil qui reprendre les données de l'Excel : https://www.hotelfootprints.org/ 

### Facteur d'émissions
Je pense que ce qui nous intéresse c'est la Measure 1 "Carbon footprint of 1 room-night stay" (onglet "M1") et les valeurs "Mean"

### Périmètre 
Le périmètre inclus le scope 1 et 2 ainsi qu'une partie du scope 3 des hôtels (blanchisserie et émissions des réfrigérant). Ce périmètre semble adéquat pour NGC et n'induit pas de double comptage.

### Modèle de calcul
Sujet à creuser car les données des hôtels sont distribuées très inéquitablement de part le monde (60 % des données proviennent des USA, 15 % de la Chine, le reste est distribué la encore de manière inégale entre pays) et étant donné qu'il s'agit d'une démarche volontaire certains types d’hôtels sont manquants. Exemple, en France on dispose de données uniquement d'hôtels 3, 4 et 5 étoiles (une extrapolation peut toutefois s'envisager je pense pour les hôtels 1 et 2 étoiles)
Une première approche pourrait être de questionner le nombre de nuits, la région du monde et éventuellement le type d'hôtel (ou sinon on fait une moyenne)

Next step : 
- [x] proposer un premier modèle de calcul
- [ ] creuser le périmètre d'évaluation GES de l'index pour savoir si les émissions de réfrigérant se limite à la climatisation ou si cela inclus tous les systèmes frigorifiques

**Comment by Marc-marc-marc** [comment]
idée intéressante mais il y a un problème d'unité sur le site web posté ci dessus
une nuit d’hôtel en France 0,0067 MT Co2e soit 6700 T Co2e ce qui est une erreur.
dans leur tableur, la valeur médiane est 6,7 kc Co2e soit un facteur d'erreur d'un million
je leur ai envoyé un email pour le signaler
