### ISSUE TITLE
Bug sur Chrome : question intempestive 

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat#1675]
Voici un bug que j'ai eu hier mais uniquement sur Chrome. Le problème n'a pas lieu sur Mozilla.

Une question intempestive (qui semble correspondre à une explication) apparait après la question de l'âge de la voiture
et avant le nombre moyen de personnes dans la voiture.

![image](https://user-images.githubusercontent.com/66410914/212866029-12796b6f-edd8-400a-bce3-e21a075168dc.png)

**Comment by Clemog** [comment]
Je n'ai pas réussi à reproduire le bug mais j'ai modifié le modèle publicodes pour faire en sorte que la variable qui donnait lieu à cette question ne la pose plus.
