### ISSUE TITLE
Bug "en savoir plus"

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat#1684]
Quand je clique sur "en savoir plus" dans les informations des deux questions logement suivantes (cf. captures d'écran), il ne se passe rien (c'est comme s'il n'y avait pas de lien). Je ne sais pas si c'est normal ? 
![Capture d’écran 2023-01-22 à 15 46 03](https://user-images.githubusercontent.com/120486950/213922029-7df1cb44-7f89-4d0c-890a-cdd27cfcefe0.png)
![Capture d’écran 2023-01-22 à 15 45 53](https://user-images.githubusercontent.com/120486950/213922044-508c58cc-9ff1-4f5c-b389-c808c03df956.png)

**Comment by laem** [comment]
Je ne me rappelle plus du rôle de cet En savoir plus, je me demande si ce n'est pas un bug, un composant qui n'a rien à faire là.

**Comment by Clemog** [comment]
@laem c'est ici :

https://github.com/datagir/nosgestesclimat-site/blob/7d0527f06ddc8305e72ee1ee68f1ac262c5c4c5f/source/components/conversation/Aide.tsx#L25-L55

Il y a effectivement un bug actuellement et je me demande si c'est pertinent d'ailleurs de mettre un lien externe à ce niveau là vers une "source" qui peut etre assez technique.

Je me dis que c'est aussi l'occasion de gérer la présence de `référence` et `références` et d'acter sur l'utilisation (oui ou non ? Si oui, comment ?) de ce mécanisme.

**Comment by lbranaa** [comment]
Je ferme car fixé par https://github.com/datagir/nosgestesclimat-site/pull/982
