### ISSUE TITLE
La part de notre épargne

### ISSUE THREAD

**Issue by JulieMat** [datagir/nosgestesclimat#1694]
## Poser une question 

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by JulieMat** [comment]
Il me semble problématique de ne pas comptabiliser l'épargne des français. On sait qu'ils épargnent dès qu'il peuvent, principalement sur des Livret A ou LDD. Et on sait aussi par ailleurs que l'empreinte carbone des banques est considérable. Si j'en suis par exemple le compteur mis en place par Oxfam en 2019 - mon épargne (qui était jusque là au Credit Agricole) émettait à elle seule presque 7 tonnes de CO2 par an - donc plus que mon bilan annuel quand je fais l'exercice sur votre plate forme! Les chiffres sont énormes et passent sous le radar ! 
Le BNP, le Credit Agricole, la Société Générale ont chacune d'elle un bilan annuelle plus élevé que l'ensemble des émissions annuelles de le France !
Ci dessous un petit résumé qui fait froid dans le dos...
https://www.oxfamfrance.org/climat-et-energie/impact-banques-climat/

**Comment by Benjamin-Boisserie-ABC** [comment]
Bonjour @JulieMat 

Quelques petits points d'attention quant à la comparaison de l'empreinte de l'épargne et de celle l'empreinte carbone individuelle. 

Le chiffrage de l'empreinte carbone des banques repose sur un périmètre extrêmement élargis (physiquement - et très certainement temporellement) qui même une fois ramené à l'euro d'épargne est difficilement comparable à celui de l'empreinte carbone individuelle.
Qui plus, il y a très certainement un double compte entre le chiffre de l'épargne et celui de votre empreinte perso. Un ex : si vos économies placées au Crédit Agricole finance des projets pétroliers, vous verrez imputer la charge de ces émissions alors que l'empreinte carbone personnelle intègre elle aussi, via les facteurs d'émissions, les émissions amont nécessaires à l'extraction et l'acheminement du pétrôle.

On peut donc difficilement mener une comparaison brut de l'empreinte de consommation et de celle de l'épargne. 

Cependant, cela ne veut pas dire que les problématiques de l'épargne ne doivent pas être expliquées, bien au contraire.

**Comment by laem** [comment]
J'ajoute que nous avons pour cela une entrée dans la FAQ. 
https://nosgestesclimat.fr/contribuer#finance
