### ISSUE TITLE
Evaluation des équipements et fournitures d'intérieur

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat#1695]
### Proposition

A l'instar des mosaïques électroménagers, électroniques et vêtements on pourrait trouver une mosaïque sur les équipements et fournitures d'intérieur. Dans la Base Carbone, il y a un nombre de FE suffisant pour proposer une estimation cohérente. On a : 
- armoire
- canapé convertible / cuir / textile
- chaise en bois / plastique / bois textile (=fauteuil ?)
- matelas mousse / ressort
- salon de jardin bois / métal / résine tressée
- sommier à latte / tapissier
- table
- cadre de lit

De plus, avec ce FE : Mobilier - fabrication (exprimé en kgCO2eq/tonne) on doit pouvoir proposer des choix types petits mobiliers (< 10kg comme une petite commode) et gros mobiliers (> 10 kg comme un bureau)

Les FE salons de jardin pourraient s'inscrire dans l'objectif de coller au mode de vie plus ruraux cf. #1309. Comme les autres sujets équipements elle fera le lien avec #1549  

### A garder en tête

C'est peut être une question supplémentaire pour un poste responsable que de peu d'émissions (surtout si on amorti les biens). Dans l'empreinte carbone nationale le code propre à l'activité de la fabrication de bien meubles (C.31) c'est 1,34 % (fusionné toutefois avec le C.32 représentant les autres produits manufacturés). Ça peut être jugé comme peu significatif mais la fabrication de biens électroménagers représente une sous-activité au sein du code C.27 représentant 0,71 % et ces biens ont leur propres question.

### A faire

- [ ] Vérifier si les constructeurs proposent des estimations GES de leurs biens (pour combler les manques de la Base Carbone)
- [ ] Proposer un modèle type mosaïque pour ces biens

**Comment by Benjamin-Boisserie-ABC** [comment]
Il ne semble pas que les vendeurs d'ameublement indique l'empreinte carbone de leur produit.

J'ai cependant trouvé cette source de la Furniture Industry Research Association qui donne d'autres chiffrage GES de biens d'équipements mais même si en page 15 on peut penser que le périmètre et les flux considérés sont exhaustifs, il y a plusieurs limites : 
- contrairement au données de la Base Carbone la phase de distribution jusqu'au magasin n'est pas prise en compte (on aurait pu toutefois palier à ce problème en considérant la composante distribution d'un FE produit (similaire) issu de la Base Carbone(r)
- ce document semble plus là pour donner des ordres de comparaison sur des produits aux entreprises membres de la FIRA plutôt que de réellement faire des ACV produits. Ainsi, ils font l’hypothèse de répartir l'ensemble des "utility" (consommation d'énergie) entre tous les produits sans distinction de type
- l'approvisionnement en matière première ne prend en compte "qu'une entrée" dans la chaine de valeur : celle du fournisseur primaire et qui plus est, il ne semble pas considéré la réalité géographique de la matière première mais la localisation du distributeur local...
- le poids des matériaux considérés sont ceux du produit final et non du besoin réel en matière. Je n'ai pas trouvé d'info là dessus dans les ACV de l'ADEME mais ça m'étonnerait que cette hypothèse soit faite

Bref, les données de la FIRA semblent ainsi très sous-estimées. Exemple : 
- cadre de lit : ADEME = 115 kgCO2eq vs FIRA = 22 kgCO2eq 
- matelas : ADEME = 285/282 kgCO2eq vs FIRA = 79 kgCO2eq 

**Je propose qu'on utilise uniquement les données ADEME**

**Comment by Clemog** [comment]
> J'ai cependant trouvé cette source de la Furniture Industry Research Association

Je ne vois pas le lien dans le message ?

**Comment by Benjamin-Boisserie-ABC** [comment]
My bad @Clemog [ici](http://www.healthyworkstations.com/resources/Environment/FIRA.CarbonFootprint.pdf)
