### ISSUE TITLE
Test already done as a simulation I want to delete

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1698]
Hello i made a test and to want to delete to restart
&gt; This ticket was created automatically by our robot from our [translation contribution page](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by lbranaa** [comment]
Hello,
Thank you for your message. If you go to "My profile" (on the left side of the screen), you can click on "Start over" to start the test again.
Have a nice day,
Laurène
![Capture d’écran 2023-02-06 à 10 07 30](https://user-images.githubusercontent.com/120486950/216930720-fd954cdb-8d45-4d38-980e-f72c0793e61c.png)

**Comment by Clemog** [comment]
Fermé au profit de https://github.com/datagir/nosgestesclimat-site/issues/790
