### ISSUE TITLE
Gérer la traduction des modèles localisés via un script

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat#1710]
Aujourd'hui, nous avons décidé de faire du français la langue d'implémentation d'un modèle régional. L'anglais étant partie intégrante du site désormais, on doit avoir une version traduite du site nouvellement créé. 

Un script qui utilise les fonctions de traductions déjà utilisées pour traduire le modèle de base semble pouvoir résoudre ce pb facilement.

**Comment by EmileRolley** [comment]
## Point 2023-02-28 \w @Clemog  

Pour une v0 (Clément doit pouvoir rapidement rédiger tous les fichiers nécessaires pour https://github.com/datagir/nosgestesclimat/pull/1732):
* Pas besoins de gestion des `.lock`.
* Simplement retraduire le ficher entier avec une demande de confirmation si il existe déjà.
* Pouvoir gérer différentes langues sources.

Pour une v1 (itérations sur les fichiers existants + potentielles contributions externes):
* Ajouter l'échelle de la règle et du mécanisme.

**Comment by EmileRolley** [comment]
Done by #1747
