### ISSUE TITLE
Test transport foireux!

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1711]
Votre test surestime de ouf ma consommation de transports! Vous me mettez 6To en tram/métro... Or, ils fonctionneraient que je les prenne ou pas! De ce que je vois, votre test considère que je ferai mieux de prendre ma voiture tout seul pour aller de Monthieux (01) à l'Université Lyon 2 Portes des Alpes plutôt que de me faire chier à prendre les transports (moyennant 75€/mois en PLUS de ma voiture) en commun 2 jours dans la semaine!

Je boss au lycée de la côtière les lundi, jeudi vendredi (donc BESOIN de voiture qui me coûte déjà la peau du cul).
Et je prend les transports en commun pour aller à l'Université Lyon 2 les mardi et mercredi... (j'ai considéré train jusqu'à Perrache et ensuite tram T2 jusqu'à la fac)

Je ne vois pas comment j'arrive à 10 pour les transports dont 6 pour les trams/métro et seulement 4 pour la voiture (je crois que c'était même moins que 4)... Il y a un problème quelque part... C'est FORCEMENT plus écologique de prendre les transports en commun que de prendre la voiture tout seul...
> Depuis la page: `https://nosgestesclimat.fr/documentation/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour,

C'est étonnant, c'est peut-être un bug dans notre modèle de calcul... Pouvez-vous nous transmettre les valeurs entrées pour les questions voiture & transport en commun ?

Merci,
Clément

**Comment by Clemog** [comment]
Je ferme l'issue, ne pas hésiter à rouvrir si nouveaux éléments :)

**Comment by laem** [comment]
L'utilisateur a probablement renseigné le nombre d'heures par an. À part ça je vois pas ^^
