### ISSUE TITLE
🇨🇭 Change default value of flight duration for Switzerland

### ISSUE THREAD

**Issue by sebeeek** [datagir/nosgestesclimat#1725]
When selecting Switzerland, and replying "I don't know" to all questions, the footprint is 8.7 T:

![ngc-suisse](https://user-images.githubusercontent.com/90280450/219323814-98033f33-3636-486f-8e72-0c6ed1de8038.png)

However the [WWF calculator](https://www.wwf.ch/fr/vie-durable/calculateur-d-empreinte-ecologique) gives a footprint 13.51 T. The source seems to be esu-services.ch, 2018:

![wwf](https://user-images.githubusercontent.com/90280450/219324209-defd9e99-ad59-4cdd-9e23-ffd4267ac739.png)

An older study, the [Carbon footprint of nations](https://pubs.acs.org/doi/10.1021/es803496a), with data from 2001, was giving 18.4 T.

**Comment by Clemog** [comment]
Hi @sebeeek ! Thank you for your feedback ! 
Firstly, the carbon model in Nos Gestes Climat is based on consumption data and not on macro results (it's a bottom-up model) which can explain some differences with other figures.
Secondly, the Switzerland model is under construction. The objective of the team is to allow contributors to create their own model and have people in charge of this model within different regions. [Here is the model for Switzerland](https://github.com/datagir/nosgestesclimat/blob/master/data/i18n/models/CH-en-us.yaml), you will see only differences from the French model.
Finally, the carbon model of the test is still in progress. We identified several missing points the model is certainly under estimated. For instance, implementation of #1700 should improve the result.

**Comment by sebeeek** [comment]
Thanks! Comparing the WWF results with NGS, one striking difference is Transportation.

This [article](https://www.swissinfo.ch/eng/swiss-co2-emissions--small-country--big-footprint/45810036) says that "the average Swiss flew about 9,000km per year".

**Comment by Clemog** [comment]
Thank you for your feedback and references !

**Comment by sebeeek** [comment]
IIUC that would mean adding this to the swiss model:

```
transport . avion . long courrier . durée moyennne
par défaut: 9000 km/an
  note: |
    Source for average annual km : [Office fédéral de la statistique](https://www.bfs.admin.ch/bfs/fr/home/actualites/quoi-de-neuf.assetdetail.1840421.html).
```

If yes, I can do that.

**Comment by Clemog** [comment]
Yes, this is exactly the way you can change it ! :)

Be careful, flights are divided into short, medium and long haul.

Does this figure correspond to an average for the whole Swiss population or only for those who take the plane ?

**Comment by laem** [comment]
This relevant issue makes me think we could maybe use a worldwide (or just OECD for instance) survey on the use of flights to adapt the default values for a set of countries once and for all. 

But if we can change the :switzerland: value, it's already great :)

**Comment by sebeeek** [comment]
> Be careful, flights are divided into short, medium and long haul.

Unfortunately the source I have does not make the distinction. Given the very high number, I assume that most of it happens with long haul.

> This relevant issue makes me think we could maybe use a worldwide (or just OECD for instance) survey on the use of flights to adapt the default values for a set of countries once and for all.

I found [Per capita international aviation passenger kilometers, 2018](https://ourworldindata.org/grapher/per-capita-international-aviation-km?tab=chart&country=~CHE) from Our World in Data, based on a an [ICCT study](https://theicct.org/publication/co2-emissions-from-commercial-aviation-2018/). There is no distinction between Short/Medium/Long haul. The ICCT study had an Domestic/International distinction though. 

In this study, average for France is at 2700km (vs 1881km currently) and Switzerland at 6000 km.

**Comment by Clemog** [comment]
> Unfortunately the source I have does not make the distinction. Given the very high number, I assume that most of it happens with long haul.

I think we are excluding regular travelers with this assumption, which concerns professional trips. 
Even if we shouldn't take it into account in the test, averaged figures include it. 



> I found [Per capita international aviation passenger kilometers, 2018](https://ourworldindata.org/grapher/per-capita-international-aviation-km?tab=chart&country=~CHE) from Our World in Data, based on a an [ICCT study](https://theicct.org/publication/co2-emissions-from-commercial-aviation-2018/). There is no distinction between Short/Medium/Long haul. The ICCT study had an Domestic/International distinction though.
> 
> In this study, average for France is at 2700km (vs 1881km currently) and Switzerland at 6000 km (vs 9000km from [OFS](https://www.bfs.admin.ch/bfs/fr/home/actualites/quoi-de-neuf.assetdetail.1840421.html)).

Very interesting ! It might be better to use international data. 
For now, we use figures from [this study](https://www.statistiques.developpement-durable.gouv.fr/sites/default/files/2018-11/datalab-essentiel-138-mobilite-longue-distance-2016-fevrier2018.pdf), which gives 47 + 149 + 1805 = 2001 km ([updated with the aerial growth factor from 2016 to 2019](https://nosgestesclimat.fr/documentation/transport/avion/croissance-2016-2019))

**Comment by sebeeek** [comment]
Thanks. What do you suggest for now? I have a PR with the 9000km figure: https://github.com/datagir/nosgestesclimat/pull/1761

**Comment by sebeeek** [comment]
> These figures seem to include also domestic flights https://ourworldindata.org/grapher/per-capita-km-aviation but it's really close to https://ourworldindata.org/grapher/per-capita-international-aviation-km?tab=chart&country=~CHE.

They are from the same source, check the "Source" tab.

> Nevertheless I am wondering if figures correspond to country flight "consumption". 

They are. From the "Source" tab `We have therefore also calculated 'adjusted' aviation footprints by multiplying per capita international RPKs and CO2 emissions by an adjustment factor.`

> I did not check how it is calculated for OFS but it seems to concern Swiss only.

Yes, from the [english snippet](https://www.bfs.admin.ch/bfs/en/home/news/whats-new.assetdetail.1840423.html) "Swiss resident population".

> A first step may be to consider 9000km with French ratios for short, medium and long haul flights

Looking at nosgestesclimat/data/transport/transport . avion.yaml, the french population travels: 
* 2.7B km short haul (2.4%)
* 8.4B km medium haul (7.4%)
* 101B km long haul (90.2%)

If we apply the same ratios to Swiss average flying distance of 9000 km that would mean:
* 216 km short haul
* 666 km medium haul
* 8118km long haul

I can prepare a new PR.

**Comment by Clemog** [comment]
Sorry for the late reply : it's done in your PR ! And merged ;)

**Comment by Clemog** [comment]
Thank you for your help !
