### ISSUE TITLE
TRANSPORT : 2 véhicules ?

### ISSUE THREAD

**Issue by Chris67** [datagir/nosgestesclimat#1727]
Bonjour,
je ne peux remplir votre test car j'ai deux véhicules familiaux, un petit et un SUV. mon test s'arrête donc assez vite : dommage. 
Chris

**Comment by Clemog** [comment]
Bonjour @Chris67 ! Merci pour votre retour ! 

C'est un sujet bien identifié (notamment #646) ! Il dépend d'améliorations de la structure de la base de code qui rentrent dans une priorisation assez globale. C'est un réel besoin.

Néanmoins, vous pouvez contourner le problème en identifiant la voiture que vous utilisez le plus, ou bien en "moyennant" la voiture que vous caractérisez :)

**Comment by Clemog** [comment]
Je ferme l'issue, n'hésitez pas à ouvrir à nouveau si besoin !
