### ISSUE TITLE
Administrative part almost bring us to the 2t objectives

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1740]
This is my main contribution and I cannot do anything on that
Problem is not the tool but the society...
&gt; This ticket was created automatically by our robot from our [translation contribution page](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by Clemog** [comment]
Thanks for your feedback, you can find some answers in [our FAQ](https://nosgestesclimat.fr/contribuer). It is true that the aim is to make public services footprint decrease as well as individual carbon footprint ! Individual actions must support collective changes.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/55186402/221565117-08c27660-4838-45d0-b357-848280e0bf6b.png">
