### ISSUE TITLE
Ajout action réseau de chaleur

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat#1744]
Beaucoup de travail préliminaire a été réalisé pour l'ajout d'une option réseau de chaleur (https://github.com/datagir/nosgestesclimat/issues/872, https://github.com/datagir/nosgestesclimat/pull/1328). La start-up d'Etat France Chaleur Urbaine a accès à des données qui peuvent être utiles pour passer à l'action. 
L'objectif de cet issue est de proposer une v1 de l'option réseau de chaleur, à la fois en question dans le test et en proposition d'action dans le parcours actions.

Nous proposons pour la partie actions de rajouter une carte pour mettre en avant France Chaleur Urbaine qui permet de voir
Conditions pour voir l'action : 
- Etre propriétaire
- Se chauffer au gaz / fioul
- Vivre en ville ?
--> Voir avec France Chaleur Urbaine si d'autres conditions pertinentes

- [x] Rajouter une question "êtes-vous propriétaire de votre logement ?" -> on ne pose finalement pas cette question cf https://github.com/datagir/nosgestesclimat/issues/1743#issuecomment-1475906858)
- [x] Rajouter une action qui apparaisse uniquement selon les conditions ci-dessus, et faisant le lien avec France Chaleur Urbaine

Sources : voir avec France Chaleur Urbaine s'ils ont des infos spécifiques à mettre dans la carte actions.

**Comment by laem** [comment]
@lbranaa quand tu dis "carte", c'est une vignette action, ou la carte de FCU ? 

Je suis pas sûr que l'ajout de la carte (géo) soit la meilleure solution. C'est pas facile en termes d'UI d'ajouter la carte, qui est un iframe, dans notre parcours action, qui est en termes d'UX très moyen, dans NGC qui est souvent un iframe.

Demander l'adresse me semble plus simple. 

Mais sinon :+1:

**Comment by lbranaa** [comment]
Je parlais de vignette action, dans laquelle on ferait le lien vers FCU (j'ai changé dans le texte au-dessus pour que ce soit plus clair). Tout le côté carte (géo) serait plutôt dans une v2, on partirait là sur une v1 plus simple sans adresse / carte, mais uniquement le lien vers FCU.

**Comment by Clemog** [comment]
Done in #1764
