### ISSUE TITLE
Remarques question meubles actuellement en démo

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1748]
> Ne renseignez ici que les produits neufs ! Nous excluons ici l'achat d'occasion et en dépot vente. N'oubliez pas vos meubles de cuisine !

Répétition de point d'exclamation. 

> Cadre de lit (hors sommier)

Je ne comprends pas la différence entre "sommier" et "cadre de lit (hors sommier)". 

Je crois comprendre que le sommier c'est en gros les lattes, et le cadre c'est le rectangle avec pied et dossier sur lequel on pose les lattes ? 

Le problème que j'y vois, c'est qu'à mon avis une proportion énorme de lits sont de simples sommiers avec des pieds, donc pile entre les deux catégories. 

Est-ce que la meilleure dichotomie ne serait pas : sommier en bois intégral vs sommier avec cadre en métal ?

**Comment by laem** [comment]
Autre sujet : j'ai l'impression qu'étant donné que dans un logement il y a souvent plusieurs lits, on a un risque que la personne ne réponde que pour son lit, or c'est divisé par le nombre de personnes. Peut-être le rappeler dans la description de la question ? 
-

**Comment by laem** [comment]
À part ça c'est trop cool ces nouveaux éléments du test :) 

D'accord avec toi @Clemog faut qu'on améliore l'interface de la mosaique, elle devient très lourde visuellement.

**Comment by Clemog** [comment]
> Est-ce que la meilleure dichotomie ne serait pas : sommier en bois intégral vs sommier avec cadre en métal ?

De mon côté ce n'est pas beaucoup plus clair, bois intégral = cadre de lit ?

Au départ je pensais fusionner cadre de lit et sommier mais pas forcément une bonne idée non plus

On pourrait peut etre avoir l'option "sommier seul" à côté de "sommier + cadre de lit" ?

**Comment by Clemog** [comment]
> Autre sujet : j'ai l'impression qu'étant donné que dans un logement il y a souvent plusieurs lits, on a un risque que la personne ne réponde que pour son lit, or c'est divisé par le nombre de personnes. Peut-être le rappeler dans la description de la question ?

J'ai ajouté une phrase dans la description de la question

**Comment by Benjamin-Boisserie-ABC** [comment]
> On pourrait peut etre avoir l'option "sommier seul" à côté de "sommier + cadre de lit" ?

On ne s'était pas dit qu'on proposait qu'une seul réponse "sommier" qui était en réalité la moyenne des 2 FE sommier et du FE cadre de lit ?

**Comment by laem** [comment]
Pour clarifier mon point en image : 90% des résultats de cette recherche "sommier" sont en fait des cadres de lit + sommier (ou sommier + pieds, qui fusionnent donc cadre et sommier). 

![image](https://user-images.githubusercontent.com/1177762/223073571-c9f35124-bba7-483a-b7b2-e9bf54f31de8.png)

**Comment by Clemog** [comment]
Description de l'étude que nous utilisons:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/55186402/223080212-5eae6e6b-476e-4be5-8cc3-ed769a0686f6.png">

**Comment by Clemog** [comment]
Pour moi, un cadre de lit c'est ça :

![](https://www.vidaxl.fr/dw/image/v2/BFNS_PRD/on/demandware.static/-/Sites-vidaxl-catalog-master-sku/default/dwab037a89/hi-res/436/6433/505764/247262/image_2_247262.jpg?sw=400)

**Comment by Clemog** [comment]
Je propose donc d'implémenter :

1) Sommier seul, avec simples pieds
2) Cadre de lit, sommier et encadrement

je trouve difficle en revanche de trouver les termes adequats mais j'ai peur qu'un unique FE pour les 2 soit un peu trompeur
En même temps, on ne différencie pas les tailles de sommier ce qui a peut etre un impact bien plus important que la dénomination exacte du lit

**Comment by Benjamin-Boisserie-ABC** [comment]
Je suis un peu perdu dans les échanges. On partirait donc sur 

> 1. Sommier seul, avec simples pieds

On pointerait ici sur le FE "sommier à lattes" ?

> 2. Cadre de lit, sommier et encadrement

On pointerait ici sur la moyenne des FE "sommier tapissier" et "cadre de lit"

Après le plus simple c'est peut être, comme tu le dis @Clemog d'avoir un choix unique qui me semblait être la conclusion de nos échanges sur l'autre PR

Pour info, je suis d'accord avec @Clemog sur la différence cadre de lit vs sommier

**Comment by Clemog** [comment]
Fixed ici [fusion sommier et cadre de lit](https://github.com/datagir/nosgestesclimat/pull/1700/commits/959ba2aae351d2d513a3439f800970b5ff0b2b7c)

**Comment by Clemog** [comment]
On peut fermer ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Ok pour moi
