### ISSUE TITLE
Question "quel type de voiture utilisez-vous"

### ISSUE THREAD

**Issue by oblab** [datagir/nosgestesclimat#1758]
Parmi les réponses proposées, vous devriez ajouter "GPL" à la première réponse (environ 250 à 300 000 véhicules en France). Si j'en crois l'ADEME, une voiture au GPL rejette autant de CO2 qu'une voiture diesel, mais en revanche elle ne rejette pas de particules nocives (source : https://expertises.ademe.fr/air-mobilites/mobilite-transports/passer-a-laction/solutions-technologiques/choisir-carburant)

Donc, formulez la première réponse comme suit : 
"Thermique (diesel/essence/GPL)"

Idem pour la question "Quel type de carburant", ajouter "GPL" parmi le réponses. La question est, faut-il mettre le GPL avec le diesel ? Vous semblez considérer que l'essence a un impact moindre sur le climat que le diesel, sans-doute parce-que vous ne prenez pas en compte que le CO2 émis ? Dans ce cas, le GPL a sans-doute un impact encore moindre que l'essence, voir même que les bio-carburants.

Le GPL est en effet un résidu de l'extraction du pétrole qui était autrefois brulé (https://fr.wikipedia.org/wiki/Gaz_de_p%C3%A9trole_liqu%C3%A9fi%C3%A9 ), donc a priori, faible impact à la production (contrairement aux bio-carburants), et il émet très peu de particules nocives. Donc bilan positif sur la qualité de l'air, en revanche le GES du GPL n'est pas exemplaire (source : https://expertises.ademe.fr/sites/default/files/assets/documents/2020-02_comparatif_des_filieres_vl_france_metropole.pdf)

**Comment by oblab** [comment]
Idem pour la question "Quel type de carburant", ajouter  "GPL" parmi le réponses. La question est, faut-il mettre le GPL avec le diesel ? Vous semblez considérer que l'essence a un impact moindre sur le climat que le diesel, sans-doute parce-que vous ne prenez pas en compte que le CO2 émis ? Dans ce cas, le GPL a sans-doute un impact encore moindre que l'essence, voir même que les bio-carburants.

Le GPL est en effet un résidu de l'extraction du pétrole qui était autrefois brulé (https://fr.wikipedia.org/wiki/Gaz_de_p%C3%A9trole_liqu%C3%A9fi%C3%A9 ), donc a priori, faible impact à la production (contrairement aux bio-carburants), et il émet très peu de particules nocives.

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour !
Le sujet est identifié ici : https://github.com/datagir/nosgestesclimat/issues/445

Effectivement, c'est une option à ajouter, je relie votre commentaire très complet à l'issue !
