### ISSUE TITLE
Je pense que je me suis trompée de lien enquete

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1775]
Je travaille avec Ecole MoPA, on travaille avec les Shifters et j'ai suivi leur lien pour etudiants au debut pour faire le test. Mais ensuite j'ai basculé sur un lien administration. Je peux recommencer et effacer mes anciens resultats? 

I work with Ecole MoPA, we work with Shifters and I followed their student link at first to do the test. But then I switched to an administration link. Can I start over and erase my old results?

&gt; This ticket was created automatically by our robot from our [translation contribution page](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by Clemog** [comment]
Bonjour, je ne suis pas sur de bien comprendre le problème ?
