### ISSUE TITLE
Service sociétaux

### ISSUE THREAD

**Issue by Superpo06** [datagir/nosgestesclimat#1780]
Si les services sociétaux comptent déjà pour environ 1,7tonnes comment est ce que l'objectif de 2tonnes est réalisable?
Pour moi ça semble un peu difficile de limiter notre consommation si en contrepartie on nous autorise que 0,3 tonnes pas an

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour ! Effectivement, le changement doit être global et pas seulement individuel ! Nous apportons quelques éléments de réponses dans notre FAQ : https://nosgestesclimat.fr/contribuer :)
Bonne journée !
