### ISSUE TITLE
Un espace manquant dans la traduction

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1790]
💡 We improve the calculation and its default valuesevery month!

Problème à cet endroit.
&gt; This ticket was created automatically by our robot from our [translation contribution page](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by Clemog** [comment]
Fixed by https://github.com/datagir/nosgestesclimat-site/commit/92d35f69c32c680bab75b5ab0c05394fa854f261 thanks !
