### ISSUE TITLE
Amortissement avion sur plusieurs années

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1793]
This website assumes I ride the plane for x hours _every_ year, whereas a lot of people will travel once every y years. This should be allowed.
&gt; This ticket was created automatically by our robot from our [translation contribution page](https://nosgestesclimat.fr/contribuer-traduction).

**Comment by Clemog** [comment]
Again, we might try to force this box .. It is asked for Swiss version for instance

**Comment by laem** [comment]
Closed, to be followed here #1804
