### ISSUE TITLE
J'ai planté 6 ha d'arbres ily a 25 ans à ma retraite

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1822]
ordinateur windows 11
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, merci pour votre message, effectivement, nous ne prenons pas encore en compte (cf #1262)
