### ISSUE TITLE
 c est bloqué à la question nb d animaux

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1835]
firefox   windows
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Zut, peut-être un pb d'UX, un peu comme les caravanes et camping car : le bouton `aucun` est très peu visible (@laem, @jeremiecook ?)

**Comment by Clemog** [comment]
Devrait avoir été corrigé par #1844
