### ISSUE TITLE
Incidence du fait d'être locataire

### ISSUE THREAD

**Issue by yanbasket** [datagir/nosgestesclimat#1853]
je suis LOCATAIRE de mon logement, les questions sur mon appartement ne sont pas compatibles.

**Comment by JuliePouliquen** [comment]
Bonjour Yann,
À quelles questions fais-tu référence ?
Le fait d'être locataire n'a pas a priori d'incidence sur ton empreinte, mais sur les actions proposées en fin de parcours oui. 
Je dis "a priori" car la question est un peu plus complexe. Elle fait l'objet d'une discussion [ici](https://github.com/datagir/nosgestesclimat/issues/1800).

**Comment by yanbasket** [comment]
Bonjour,
j'aurais en effet pu être fortement intéressé à la discussion étant diplômé du CUEPE-uni Genève (Centre Universitaire d'Études des Problèmes de l'Énergie!) mais désormais:

- je suis en traitement cancer pour... un moment
- j'ai pris ma retraite (pas seulement à cause du point précédent mais parce que beaucoup de physiciens CERN (où j'ai travaillé 30 ans et "attrapé" mon cancer...) tentent encore de relancer le nucléaire
- en conséquence je déménage en province

Mon intervention, peut-être mal exprimée, signalait (mais mon cerveau, impacté par ma santé question mémoire m'empêche de retrouver mon message...) que certaines questions ne pouvaient avoir de réponses pour un locataire. Désolé, je vous souhaite bon courage, personnellement j'ai démontré pendant 40ans que le nucléaire était aberrant dans TOUS les domaines (je suis aussi diplômé des Arts-et-Métiers) mais regardez le résultat.......
Néanmoins je peux apporter un témoignage concernant la transition énergétique, excusez-moi si cela pourrait être hors-sujet, mon cerveau se fatigue vite, mais ces réponses et actions sont INSTANTANÉMENT praticables dans ce cadre:

- j'ai DONNÉ ma voiture
- j'ai changé de banque pour une (la seule avec la Nef) qui est indépendante des paradis fiscaux: le Crédit Coopératif
- j'ai abandonné mon contrat EDF et suis passé à Enercoop, comme des dizaines de milliers de français et une multitudes de sociétés et même des communes
- et donc donné ma démission du CERN.............

Bon courage à toutes vos équipes!

Yves Renaud
désormais poète et déjà plus de 100 fois primé...

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

------- Original Message -------

**Comment by JuliePouliquen** [comment]
Bonjour Yves,
Merci beaucoup pour tes encouragements !
Je te souhaite beaucoup de courage et d'être bien entouré pour le combat que tu mènes actuellement.
Bravo aussi pour tes engagements et choix éclairés.
Julie
