### ISSUE TITLE
Propositions d'actions injonctives

### ISSUE THREAD

**Issue by jmr2790** [datagir/nosgestesclimat#1863]
Bonjour, sur les propositions de gestes pour réduire mon empreinte carbone, j'ai comme injonction, d'acheter une voiture électrique, dont on ne connait pas la facon de recycler la batterie, de devenir végétarien au risque de réséquilibrer mon régime alimentaire par un excès de sucre et avec des sources d'approvisionnement étrangères dont on ne connait pas les normes de production et d'arrêter l'avion. Si ce sont des injonctions, pourquoi ne pas nous les imposer comme lois ? et pourquoi ne pouvons nous pas donner notre avis directement sur les propositions faites ? un dialogue unilatérale n'est pas souhaitable.

**Comment by Clemog** [comment]
Bonjour @jmr2790, merci pour votre retour. Les actions que nous partageons sont personnalisées : sauf bug, vous devriez voir des actions qui correspondent à votre situation. En revanche, nous proposons peut d'interactions avec les propositions : vous pouvez "accepter" ou "écarter" des actions. C'est n'est pas optimal et nous travaillons sur le sujet pour améliorer l'UX de cet écran.
Est ce que votre commentaire va plus loin ? Vous attendez un dialogue sous quelle forme ?

**Comment by Clemog** [comment]
Hello @jmr2790, je ferme l'issue, n'hésitez pas à nous répondre quand même :)
