### ISSUE TITLE
Ajout d'un bouton "réinitialiser"

### ISSUE THREAD

**Issue by JuliePouliquen** [datagir/nosgestesclimat#1873]
Je me demande s'il ne serait pas pertinent de proposer à l'utilisateur un bouton "redémarrer mon test de zéro" / "réinitialiser le simulateur".
Dans le cadre de mes tests, je me retrouve souvent à vider le cache. Mais je pense à des gens qui feraient faire le test à d'autres sur leur ordi et se retrouveraient avec leurs réponses précédentes. Ou de gens qui se diraient (comme ça m'est arrivé) : "OK, mon résultat c'est ça. Et ça donnerait quoi si je changeais ça ?"
Ou alors je ne l'ai pas vu... ?

À ce jour, quand je reviens sur la page d'accueil, à la racine, je ne peux que "Reprendre mon test" mais pas redémarrer.

**Comment by Clemog** [comment]
C'est dans l'onglet `Profil` :)
 
Et c'est plutôt une issue "site": celle-ci ressemble https://github.com/datagir/nosgestesclimat-site/issues/790 ;)
