### ISSUE TITLE
Supprimer l'action "Ne pas prendre la voiture pour les trajets de moins de 5 km" quand pas propriétaire

### ISSUE THREAD

**Issue by JuliePouliquen** [datagir/nosgestesclimat#1879]
Si on n'a pas de voiture, a priori il n'y a quasi aucun trajet de moins de 5 km réalisé en voiture, à l'usage.
Une voiture sera louée ou empruntée pour les plus gros trajets, ou ceux avec des charges lourdes.

**Comment by JuliePouliquen** [comment]
À relier à #1045

**Comment by Clemog** [comment]
Effectivement, ça semble plus pertinent !

**Comment by Benjamin-Boisserie-ABC** [comment]
Pour info même si l'issue est fermée, je fais le lien avec une issue ouverte sur ce sujet #1816

**Comment by JuliePouliquen** [comment]
Ah oui merci @Benjamin-Boisserie-ABC ! Je me suis permise de cocher la case correspondante, désolée je ne l'avais pas vue. OK pour toi ?
