### ISSUE TITLE
🐛 Bug : au moment de la compilation, la règle pétrole n'est pas testée

### ISSUE THREAD

**Issue by JuliePouliquen** [datagir/nosgestesclimat#1889]
J'ai supprimé par incompréhension des données permettant le calcul de la règle `pétrole` et cela n'a pas empêché les tests de passer en local.

**Comment by EmileRolley** [comment]
#1890 devrait régler le problème soulevé par @Clemog et pour l'issue initiale je me demande si le problème ne vient pas du fait que tu n'as pas tenté de recompiler le modèle avant de lancer `yarn run test:personas` @JuliePouliquen ? En effet, les tests se font sur le dernier modèle compilé (qui donc par définition sera toujours _valide_).

**Comment by JuliePouliquen** [comment]
J'avoue que je suis encore un peu novice, donc j'essaie de comprendre tous les tenants et aboutissants mais ce n'est pas encore évident :smile: !
