### ISSUE TITLE
Résidence secondaire

### ISSUE THREAD

**Issue by Villerspub** [datagir/nosgestesclimat#1896]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/contribuer) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

## Poser une question : Pourquoi je ne peux pas sélectionner la case "résidence secondaire" ?

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by Clemog** [comment]
Merci pour votre message ! C'est en cours de rééflexion ;) #1455
