### ISSUE TITLE
1 meal per day

### ISSUE THREAD

**Issue by RaaoulDuuke** [datagir/nosgestesclimat#1897]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/contribuer) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

## Poser une question 

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 
I dont eat twice a day and i m not the o nly one: 
https://investir.lesechos.fr/budget/vie-pratique/budget-20-des-francais-sont-contraints-de-sauter-un-repas-faute-de-moyens-1923138
https://www.lefigaro.fr/conso/inflation-42-des-francais-les-plus-precaires-ont-supprime-un-repas-selon-une-etude-20230410

**Comment by Clemog** [comment]
Thank your for your feedback !

Yes, the problem is opened here : #1841 :)
