### ISSUE TITLE
Quel empreinte pour le tri ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#191]
Peut-on estimer un gain d'empreinte pour le fait de trier ses poubelles ? Est-ce inclus dans la question "démarche zéro déchet" ? Ou dans le poste "services publics" ?

**Comment by Clemog** [comment]
L'empreinte des déchets (et donc des déchets triés) est traité dans le modèle déchet (https://github.com/datagir/nosgestesclimat/pull/1415) et donc dans la question "Comment estimeriez-vous la quantité de déchets que vous jetez ?"
Pour le moment, aucun focus n'a été fait spécifiquement sur le tri des déchets
Je ferme au profit du #1443

**Comment by Clemog** [comment]
L'empreinte des déchets (et donc des déchets triés) est traité dans le modèle déchet (https://github.com/datagir/nosgestesclimat/pull/1415) et donc dans la question "Comment estimeriez-vous la quantité de déchets que vous jetez ?"
Pour le moment, aucun focus n'a été fait spécifiquement sur le tri des déchets
Je ferme au profit du #1443
