### ISSUE TITLE
Votre test ne comprend pas ma profuction rlectrique par panneaux solzite sui m’a fait economiser en 3 ans 21 tonnes de co2

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1911]
> Depuis la page: `https://nosgestesclimat.fr/documentation/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Merci pour le retour, je ferme au profit de https://github.com/datagir/nosgestesclimat/issues/624 et #1902
