### ISSUE TITLE
Questions voiture `non propriétaire`

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat#1915]
1. Le site n‘enregistre pas mes choix: quand j’arrive au bout et que je vérifie mes réponses, il m’affiche d’autres réponses (réponses standard/moyennes?)
2. En cochant « non » à voiture, il pose quand même tous les questions liées et la voiture et pas moyen de répondre « zéro » ou « aucun » ou ces questions.

> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Je ferme au profit de #1836
