### ISSUE TITLE
J'utilise des panneaux solaires, hors réseau EDF pour générer mon électricité, comment le prendre en compte ?

### ISSUE THREAD

**Issue by Ezilaa** [datagir/nosgestesclimat#1923]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/contribuer) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

## Poser une question 

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by Clemog** [comment]
Merci pour le retour, je ferme au profit de https://github.com/datagir/nosgestesclimat/issues/624 et https://github.com/datagir/nosgestesclimat/issues/1902
