### ISSUE TITLE
Empreinte service public : nouvelle source

### ISSUE THREAD

**Issue by cgeroudet** [datagir/nosgestesclimat#197]
J'ai trouvé une source assez récente pour l'impact des émissions des services publics dans le rapport 2019 sur l'Etat de l'environnement (https://ree.developpement-durable.gouv.fr/themes/defis-environnementaux/changement-climatique/empreinte-carbone/article/l-empreinte-carbone-de-la-france ), qui estime l'impact à **1,11 tCO2e** par habitant.
Jusqu'à maintenant, Micmac utilisait 1,284 tCO2e, issue d'une source assez vieille.

**Comment by laem** [comment]
Nous l'avons mise en ligne :)
