### ISSUE TITLE
Transport

### ISSUE THREAD

**Issue by fjg** [datagir/nosgestesclimat#21]
## Voiture : cas de l'autopartage/covoiturage : pas de voiture en propre.

Donc pas de réponse à 

* "Quelle est l'age de votre voiture ? ℹ️"
* "Quelle est la consommation moyenne de votre voiture ?"

## Avion

Proposer temps ou distance "Combien d'heures passez-vous annuellement dans un avion ? ℹ️"
D'ailleurs pour le train on propose des kms.

:heavy_check_mark:  c'est fait

## Train

Proposer temps ou distance : "Combien de kilomètres parcourez-vous en train par an ? ℹ️"

## divers

Voir les propositions de cette issue : #856

**Comment by laem** [comment]
J'ai mis à jour le modèle pour poser la question du véhicule individuel. 
Par contre, ça divise par 2 l'empreinte de la construction de la voiture, mais c'est complètement au pif, en attente de meilleures données. Cela dit, ça évite de poser la question de l'âge. La question de la consommation moyenne reste nécessaire et les suggestions doivent aider (si ce n'est pas le cas, il faut améliorer la question pour tout le monde).

**Comment by laem** [comment]
Je crois que tout est fait dans cette issue :partying_face:
