### ISSUE TITLE
 Sur-estimation empreinte menu végétalien ?

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#229]
Il semblerait qu'une étude chiffre à 250kgCO2e/an l'alimentation végétalienne, quand nous chiffrons à 500kg les seuls repas midi et soir.
https://www.sciencedirect.com/science/article/pii/S0959378018306101
Voir : https://twitter.com/AEffondrement/status/1303302429031706626

**Comment by lbranaa** [comment]
@laem  @Clemog, est-ce que cela n'a pas été modifié avec la refonte des menus ?
