### ISSUE TITLE
Améliorer présentation des explications 

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat#28]
Ex : cas ou je dit que je possède une tablette vieille de 5 ans

Il est présenté la case "Déclenchement" --> Est ce nécessaire pour l'utilisateur?

Il est aussi présenté la formule 63/durée (5ans) = 12,6/ans --> Il faudrait expliquer ce qu'est 63 et l'unité en kgCO2eq. Il faudrait pour cela que la page renvoi au FE de le Base Carbone. 
Cela résulterait donc en un travail de sourcing

A discuter !

**Comment by laem** [comment]
Voir https://github.com/betagouv/ecolab-climat/issues/6

**Comment by Clemog** [comment]
Je ferme cette issue, un peu vieille semble-t-il ;)
