### ISSUE TITLE
Animaux domestiques 🐩🐈

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#35]
On a reçu déjà plusieurs retours. 

J'imagine que leur impact, venant de leur alimentation carnée dépendante du système agricole industriel, est en général rangé dans le poste national "viandes et poissons". Ça me semble légitime de se poser la question d'inclure une question à ce propos.

### Retours 

https://mobile.twitter.com/AEffondrement/status/1270477285800452106

Retour dans #143 

>aucune mention de l'alimentation des animaux domestiques. Un chien consomme 164 kg de viande par an, soit 2 fois plus que les humains (https://www.lemonde.fr/planete/article/2019/06/03/chiens-et-chats-quatorze-gestes-pour-moins-polluer-en-leur-compagnie_5470590_3244.html). Alors certes l'industrie précise bien que ce sont principalement des morceaux non consommés par les humains comme les abats. Mais 1/ ces morceaux sont consommables (il n'y a pas si longtemps on mangeait les abats), 2/ certaines marques proposent des "beaux" morceaux de viande (ex : https://www.pepette.co/).

**Comment by laem** [comment]
Autre retour : 

> Bonjour,
> Je suis curieux de ne pas voir l'impact des animaux domestiques carnivores, en effet la consommation de viande a un impact fort sur le CO2, or un chien / chat se nourrit en grande partie de viande. Il pourrait être intéressant (et pas forcément complexe en fonction du poids de l'animal) de le prendre en compte.
Merci beaucoup pour le travail réalisé !! C'est très sympa à utiliser et très important !

**Comment by laem** [comment]
Dont une émission à la radio 😁
https://www.franceculture.fr/emissions/la-transition/bilan-carbone-en-dessous-de-la-moyenne

**Comment by laem** [comment]
Voilà mon avis sur le sujet : d'un côté, nos animaux ont bien une empreinte importante. De l'autre cette empreinte est associée à de la vie, qu'on ne peut pas ignorer. Peut-on affirmer qu'un animal sauvage, contrairement à un animal domestique, est en équilibre avec l'environnement du point de vue des GES ? L'histoire semble nous montrer que oui. Pas facile de trancher ce débat cependant. Peut-être que le plus simple est d'intégrer ce point, tout en évoquant les limites du raisonnement.

**Comment by bertrandgorge** [comment]
@laem - je serai d'accord avec vous, dans l'absolu - mais c'est dans l'excès qu'il y a un problème. On est passé de 8M de chats en 1996 à 14 en 2018. Croissance exponentielle. Si on considère que le calcul de @AEffondrement est correct, rien que pour les chats on est à 4.2M de T par an. Ce n'est pas juste négligeable (on peut doubler pour les chiens, le ratio poids/nombre étant équivalent).

J'ajoute que considérant l'impact négatif des chats sur la biodiversité (oiseaux en particulier), il n'est pas illégitime de commencer une certaine pédagogie pour se défaire de l'image "trop mignon" de ces animaux. Chacun est libre de décider en conscience ce qu'il doit faire mais l'absence d'information == ignorance. https://www.smithsonianmag.com/science-nature/moral-cost-of-cats-180960505/

**Comment by J-LeJeune** [comment]
Bonjour,
@laem , je ne saisis pas la logique de dire que les animaux de compagnie forment partie du vivant et qu'ils ne faut donc pas leur imputer d'impact. En poussant ce raisonnement, les être humains échappent également au comptage car il font partie du vivant. Si on revient à l'Accord de Paris, l'objectif est d'équilibrer les émissions anthropiques par les absorptions anthropiques au plus vite. La question est donc de savoir si les émissions liées aux animaux de compagnie sont considérées d'origine anthropique ou non. La réponse est oui, par définition d'un animal domestique.
Sur le point de vue strictement comptable, dans une comptabilité parfaite, la somme des empreintes carbones des individus de la planète serait égale à la somme des émissions nationales. Le sac de croquette de Médor a bien été produit à partir d'un boeuf (dont les émissions entériques sont attribuables au pays qui l'a vu brouter), nourri avec des tourteaux de soja (émissions elles aussi compter dans un inventaire national).
On peut discuter de comment on compte, mais ne pas compter revient à laisser un trou dans le compta.

Pour ce qui est de l'impact des animaux sauvages, la concentration de GES a été stable pendant des millénaires ce qui implique un équilibre entre émissions et absorptions. Quoi qu'il en soit si ce n'est pas le cas et que ce n'est pas compté, ce n'est pas une raison suffisante pour ne pas compter autre chose.

**Comment by laem** [comment]
![Screenshot_20220502-213644_Kiwi Browser](https://user-images.githubusercontent.com/1177762/166313907-66414cc3-6ad9-4533-9759-2b8a6aeeb1ac.jpg)

https://www.linkedin.com/posts/myco2-par-carbone-4_chiens-et-chats-activity-6926774044457353216-2WMk?utm_source=linkedin_share&utm_medium=member_desktop_web&mc_cid=3eb2e7c8ed&mc_eid=9d8ed11fd2

**Comment by laem** [comment]
Ici ça parle d'un aquarium #poisson 
https://github.com/datagir/nosgestesclimat/issues/1580

**Comment by laem** [comment]
Autre commentaire 

```
Puisque l'alimentation a un impact important, ça serait bien de comptabiliser celle de nos animaux domestiques : j'imagine que l'impact sera très différent selon que j'ai seulement une souris blanche, ou 3 gros chiens de 40 kilos.
Voir par exemple cet article : https://www.sudouest.fr/environnement/animaux/environnement-quel-est-l-impact-de-vos-animaux-de-compagnie-sur-la-planete-1756503.php
L'étude citée semble ne s'intéresser qu'à la portion de viande des aliments pour animaux, alors qu'un grande partie de aliments pour chiens est constituée de végétaux (céréales).
```

**Comment by laem** [comment]
On vient d'avoir via BonPote un retour d'une personne sur ce sujet mais pour les chevaux. À creuser, leur alimentation étant bien différente j'imagine.

**Comment by laem** [comment]
Autre source, à voir si on l'a déjà vue passer / si elles est toujours d'actualité. 
https://www.slate.fr/story/12169/les-4x4-sont-plus-ecolos-que-les-chiens

**Comment by laem** [comment]
![IMG_20230227_114304](https://user-images.githubusercontent.com/1177762/221542922-f3fe86d8-6f62-4c38-97cd-c6eaa5818cce.jpg)
