### ISSUE TITLE
Choix d'achats textiles plutôt que somme totale indifférenciée en €

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#44]
La valorisation en euros n'a pas beaucoup de sens (grandes différences de prix pour un vêtement donné!). Pourquoi ne pas compter des nbs de vêtements, ou autres éléments textiles ?
jacques salzer

**Comment by laem** [comment]
Oui, très bonne remarque. C'est le même sujet que pour https://github.com/betagouv/ecolab-data/issues/12 : proposer une grille à choix multiple : 👗👞👔🦙 etc.

**Comment by CaroleDavid** [comment]
La valorisation en euros est d'autant plus problématique que le prix n'est pas représentatif de l'impact du mode de fabrication du vêtement. On ne peut pas comparer un t-shirt H&M à 10€, un t-shirt Loom à 20€ et un t-shirt Zadig & Voltaire à 100€ 😀

Au delà du type de pièces achetées (dans la même logique que les échanges autour de l'électroménager dans d'autres issues), la notion d'unités achetées est peut-être une piste à creuser ? Je ne sais pas comment cela peut jouer sur le calcul mais on pourrait imaginer que le nombre de pièces viennent pondérer la question du budget. L'enjeu prioritaire n'est-il pas justement d'ACHETER mois plutôt que DÉPENSER moins? 🤔

**Comment by laem** [comment]
> L'enjeu prioritaire n'est-il pas justement d'ACHETER mois plutôt que DÉPENSER moins? 🤔

Oui @CaroleDavid , tout à fait juste à mon avis !

Je pense qu'avec une grille d'articles courants, on pourrait couvrir 80% des achats. Un dernier bouton "Autres" permettrait de raisonner par nombre d'articles comme tu le dis, plutôt que par somme. A vérifier.

On peut imaginer un truc comme ça, avec des boutons + et - à côté :)
![image](https://user-images.githubusercontent.com/1177762/86905601-96b15e80-c112-11ea-98be-676e49318879.png)

**Comment by fjg** [comment]
Ca serait top effectivement de proposer une liste de produits en pouvant indiquer la quantité achetée par an

**Comment by Benjamin-Boisserie-ABC** [comment]
J'ai été fouillé dans la base de données Base Impact (liée à l'outil Bilan Produit de l'ADEME - logiciel d'analyse ACV) qui sert à l'expérimentation visant à mettre en place un affichage environnemental des produits (les entreprises pionnières réalisent les ACV de leur produits et les transmettent aux délégataires de l'ADEME qui vérifient l'attribution des notes (et donc des calculs).

Pour l'habillement, je vous joins l'excel des données
[Echelles v0.1.xlsx](https://github.com/datagir/nosgestesclimat/files/6762813/Echelles.v0.1.xlsx)

Plusieurs remarques : 
  - il n'y a pas beaucoup d'entreprises ayant participées (parfois pour une catégorie de produits on considère la moyenne des produits d'une seule marque). Mais bon c'est toujours mieux que pas de données.
  - il n'y a aucun produit "éco-conçus",éco-friendly, etc. --> les retours disant "j'achète des vêtements responsables qui durent et non de la fast-fashion" seront toujours présents.
  
@laem Je vais proposer une PR qui intègre ces données pour qu'on puisse mettre en place une mosaïque à l'instar de l'électroménager

**Comment by laem** [comment]
> @laem Je vais proposer une PR qui intègre ces données pour qu'on puisse mettre en place une mosaïque à l'instar de l'électroménager

Plutôt à l'instar du régime alimentaire d'ailleurs, car il faudra un nombre associé à chaque produit. 4-shirts, 3 pulls, 4 pantalons, etc.

**Comment by martinregner** [comment]
intégré dans #1125
