### ISSUE TITLE
Amélioration petit-déjeuners

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#453]
> Ce problème figure dans le top des retours utilisateurs ! 

## Implé 

On peut partir du principe que le petit dej est une routine, donc qu'un type de petit dej peut être désigné représentatif de l'ensemble. 

Plutôt que de gérer l'énorme diversité ci-dessous, on peut déjà pour une v2 s'assurer que nous avons les petits dej représentatifs : végan, végé, laitages, viande (éventuellement poisson ?).

## Diversité des petits-dej

On nous a dit très souvent que les choix proposés sont bien trop limités. Florilège. 

> Soit à l'anglaise avec oeufs bacon beans, ou alors du fromage ? On ne peut pas le mettre !

> Il faudrait ajouter la boisson (thé, café ou lait) et avoir la possibilité de mettre "tartine" "beurre" "confiture" "nutella" etc...
De plus, selon où on le prend il y a de l'huile de palme...

> Rajouter un petit déjeuner type bacon (qui serait plus impactant donc ?) ou d’œufs comme présent dans beaucoup de pays

> Salut ! Moi je suis sur un petit dèj tartine-confiture, je pense que ça doit être assez répandu...

> je prends un miam aux fruits composée de fruits, d'huile, de graines

> Hello, je pense qu'on est relativement nombreux à prendre un petit dej salé type "continental": pain/fromage/fruit, par exemple, ou oeufs... dommage que l'option n'y soit pas

>  Par exemple, si je mange des oeufs le matin quel est mon impact ?

> Pain beurre yaourt

>  fruits et tisane
> fruits seuls / thé

> Pour le petit déjeuner, il faudrait diversifier un peu plus les choix de réponse (oeufs, fromage blanc, fruits etc...)
Ou bien considérer le petit dej comme les autres repas : votre petit dej est-il végé / vegan / autre ?

> Je mange des oeufs, des fruits et je bois un café.

> 2 oeufs
1 banane
2 carré de chocolat noir
1 poignet d'amandes

> Mon type de petit-déjeuner n'est pas indiqué : je bois du thé et une orange pressée, je mange du pain complet bio avec de la confiture maison.

> Je pense qu'il serais bien d'ajouter dans le test sur l'alimentation au petit déjeuner un petit déjeuner végétale composé de fruits.

> Je n'arrive pas à répondre à la première question sur le petit déjeuner : je bois du thé, un citron, je mange du pain complet Bio, parfois du beurre, de la confiture maison.... Cela n'existe pas ou je ne l'ai pas trouvé....

> un bol de Ricoré (pas top ! je passerai bientôt à plus simple), un jus de pomme local, une pomme bio, du fromage blanc de chèvre - si possible frais de chez ma voisine, des noix de chez moi

> Des fruits des noix des amandes

> mon petit déj n'apparait pas!
pain, fromage, charcuterie
protéiné et gras, c'est le petit déj chrono nutrition, ou l'ont mange différents nutriments en fonction de l'heure de la journée
ça correspond aussi à peut près au petit déj allemand

> Pour ma part je mange un petit-déjeuner à base de fruits et de noix (banane, avec fruits de saisons, huile de lin, amandes, noisettes, noix, sésame, jus de citron), sans laitage et sans gluten qui ne correspond pas du tout au proposition

> Pain au lin, ou au tournesol et beurre (salé!), ricoré au lait et sans sucre !

>  Je mange du jambon et des œufs le matin, ce qui me permet de ne pas trop manger le midi. Mais il n'y a pas cette option :(

> fruits pain fromage blanc café

> Avez-vous pensé que nombreux sont ceux, qui, comme moi, sommes diabétiques et prennent un petit déjeuner plutôt salé.
Le mien se compose en général d'un petit toast avec du fromage ou jambon et café noir.

> Bonjour, pour le petit petit-déjeuner il n'y a pas la traditionnelle baguette. A moins qu'il faille considérer "baguette + vienoiserie"?

> Les propositions du test sont limitatives. Voici mon petit déjeuner, fruits secs et frais, yaourt, pain complet, thé

> 2 tasses de thé 2 biscottes

> Pour le petit dej il n'y a pas d'option vegan.

> en fait au petit déjeuner je mange des oeufs et des muffins.
J'aurais fait une séquence : salé / sucré peut-être.

> Pour mon petit dej je fais des plats chauds avec des restes ou avec des lactofermentations, des soupes, des écrasés de haricots....aucune rubrique en ce sens dans votre calculateur

> De plus en plus de personnes mangent salé le matin au petit déjeuner. Je mange ce qui reste dans le frigo ou je me fais des œufs...

> Je déjeune tous les matins : tartines de pain complet certaines beurrées, d'autres à la purée d'amande. Rien ne correspond pourtant... Je ne bois pas de lait.

> Boisson chaude, aliment salé (oeuf, jambon, sardines, fromage frais, ...), morceau de pain

> Petit-déjeuner : jamais de lait + céréales, très peu de viennoiseries (plutôt en déplacement). Par contre, c'est café, beaucoup de fruits et de fruits secs, parfois des œufs.

> Un thé ou café une tartine de fromage type st moret , 100g de fromage blanc

> je mange des pâtes, du riz, ou des pommes de terre le matin

>café+pain

>un petit-déjeuner type salé : pain beurre, fromage, œufs, jambon ou type healthy

>végétalien

**Comment by DaffyDuke** [comment]
En phase avec çà. J'ajouter que l'impact d'un œuf pondu par les poules au fond du jardin n'a pas le même impact qu'un œuf acheté en supermarché. Et il en est de même pour tous les produits du petit-déj'. Pour ma part mon café provient d'un circuit court. OK la matière première vient nécessaire hors de France mais en terme de transformation, transport et vente je suis certain d'avoir diminué mon impact personnel.

**Comment by Minigerbox** [comment]
Bonjour,
J'ai du mal à comprendre si le sujet est clos ou pas, donc je me permets de rajouter mon grain de sel à un sujet déjà bien développé... :-)
Je pense en effet qu'il faudrait permettre d'avoir deux options supplémentaires de petit-déj : 
- une option "produits animaux" : oeufs, bacon, fromage, etc.
- une option "100% végétal" sucré ou salé : salade de fruits/graines, avocat, houmous, etc.
L'option tartine peut être intéressante aussi, même si elle se rapproche peut-être de l'option céréales/lait végétal en termes d'impact carbone ? si c'est le cas, on pourrait le préciser dans le "titre" : "céréales et lait, ou tartines et confiture". J'ai l'impression que ce qui compte ici, c'est le côté "un peu de blé, mais pas trop de beurre, et peu transformé". Mais je ne suis pas une experte ;-)

Merci pour votre travail en tout cas, c'est  très intéressant et ça donne une perspective.

**Comment by Popolon** [comment]
Au petit déjeuner : gruau de céréales rustiques, courges, fruits, et un peu de lait de soja (tout en bio). La production de lait de vache est surconsommatrice, donc, je ne peux/veux pas rentrer dans cette case.

**Comment by Clemog** [comment]
Plusieurs options :

- Une mosaïque pour designer son petit dej à base de quelques ingrédients avec un champ de recherche connecté à Agribalyse pour les ingrédients qui ne sont pas proposés dans la mosaïque
- Proposer d'autres options de petits dejs pour essayer d'englober tous les régimes si on peut le faire ?
- Ajouter une question boisson chaude ? Lié avec les autres boissons ?

**Comment by Clemog** [comment]
Proposition de 4 petits déjeuners-type pour avancer sur le sujet : https://docs.google.com/spreadsheets/d/1ymAifMnOSYKaOGc2iU49ikyMuA6_6_XT6ZNTR-XV0ZI/edit#gid=0
(provisoirement sur un gsheet)

**Comment by Popolon** [comment]
Autres ingrédients:
* Café
* Cacao (ou boisson à base de cacao)
* viennoiseries
* pain
* jus de fruit
* fruit frais
* confiture
* beurre
* fromage
* miel
* lait de soja
* bouille ou gruau (de riz, avoine, mélange de céréales etc...)
* crudités

**Comment by Clem-mrtn** [comment]
#1419

**Comment by Clemog** [comment]
Retour utilisateur intéressant :
> Atre suggestion, pour le petit déjeuner, nous sommes plusieurs à vouloir cocher plusieurs cases. Comme pour les repas veggie, végétalien, viande... Est ce qu'on ne pourrait pas numéroter les petits déjeuner plutôt fruit, viennoiseries, lait/céréales ? Cela a peut être peu d'impact sur l'empreinte carbone...

**Comment by Clemog** [comment]
Il y a bien une question sur le type de lait consommé ;)

<img width="864" alt="image" src="https://user-images.githubusercontent.com/55186402/191200587-f451a105-f852-4fb9-adf3-229956723e90.png">

**Comment by Popolon** [comment]
Merci ça n'y était pas quand je l'avais utilisé. Je vais retester avec toutes ces améliorations :).
