### ISSUE TITLE
Dépenses

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#537]
Bonjour,
Je pense que dans les dépenses pour l'électricité il faudrait distinguer l'abonnement de la consommation. Pour les petits consommateurs , la part de l'abonnement est supérieure à celle de la consommation.

**Comment by Benjamin-Boisserie-ABC** [comment]
La première possibilité est de renseigner sa consommation en kWh, ce qui permet d'avoir l'impact GES exact de sa consommation. L'approche par la dépense est pour les gens n'ayant aucune idée de leur consommation. En effet, cette dépense comprend une part d'abonnement parfois très significative.Néanmoins, le facteur d'émissions de l'électricité française étant très faible, cela n'influe pas réellement sur l'empreinte carbone associée au poste logement.

**Comment by lbranaa** [comment]
Je ferme, @Benjamin-Boisserie-ABC ayant répondu à l'utilisateur
