### ISSUE TITLE
Régimes plus fins & activités loisir

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#58]
Pour l'alimentaire il faudrait intégrer la viande une fois par semaine et végé le reste du temps.
Pour les loisirs certains nécessitent une consommation d'énergie importante. Par exemple je pratique la plongée sous marine, la fabrication du matériel nécessaire, le gonflage des blocs de plongée et la navigation représente sans doute quelque chose de non négligeable.

**Comment by laem** [comment]
Voir #8 
Super remarque pour les activités sportives :)

**Comment by Benjamin-Boisserie-ABC** [comment]
Je complète de #252 pour les réflexions sur les hobbies ayant potentiellement de très fort impacts GES (motocross, aviation de loisir, chute libre, jet-ski, etc.)

**Comment by laem** [comment]
Discussion récente au sujet des loisirs motorisés très énergivores. 


https://mobile.twitter.com/brunojav/status/1365966559945109505
