### ISSUE TITLE
L'année n'est pas un délai pertinent pour mes achats d'électroménagers

### ISSUE THREAD

**Issue by DavidBruant** [datagir/nosgestesclimat#587]
> Combien dépensez-vous par an en électroménager acheté neuf ?

J'avais envie de répondre 0, parce que j'achète plutôt d'occasion, mais parfois, je peux acheter un truc neuf, mais c'est un objet qui va me durer 5 ans, etc. J'ai trouvé qu'il m'étais difficile de répondre à cette question

Aussi, une liste de ce que vous considérez serait cool, parce que j'ai du prendre un temps un peu long à me demander ce qui rentre dans la liste et ce que j'ai acheté ou pas acheté ces 5-10 dernières années

**Comment by laem** [comment]
Tout à fait :)

**Comment by Clemog** [comment]
Je ferme au profit de #1549 pour ce qui concerne les achats d'occasion !
