### ISSUE TITLE
Croisières touristiques et ferry

### ISSUE THREAD

**Issue by ryanzidago** [datagir/nosgestesclimat#612]
Le calculateur ne prend pas en compte les croisières touristiques.
On demande à l'utilisateur s'il ou elle prend l'avion, le train, le bus, ou la voiture, mais pas les croisières.

**Comment by laem** [comment]
Très bonne remarque ! 
Il n'existe aujourd'hui en France aucune estimation de l'empreinte climat d'une croisière / d'un ferry. 
Celles de la base carbone de l'ADEME ont été archivées.

Pour le ferry, c'est plus compliqué : ce sont des navires dits "RoPax" : fret + passagers. La difficulté est d'attribuer une part du pétrole brûlé au fret, une autre aux voyageurs, et surtout répartir entre les différents types de voyageurs (voiture, cabine, siège, utilisation des restaurants, etc.).

Je bosse personnellement sur une estimation pour un ferry (distance ~200km) mais c'est loin d'être intégrable ici pour l'instant.

**Comment by Clemog** [comment]
Je ferme au profit de #1548
