### ISSUE TITLE
Installation solaire à domicile (🌡 et 🚗)

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#619]
Bonjour!
Je charge ma voiture à l’énergie solaire, et chauffe aussi ma maison en partie par le solaire. J’ai pu passer à côté mais il ne me semble pas que ça fasse partie des propositions. (Bon après les factures de bois d’électricité et de gaz sont très faibles par rapport à la superficie de la maison, donc peut-être que c’est pris en compte par ce biais?)

**Comment by laem** [comment]
Nous n'avons pas encore d'estimation de l'empreinte d'une installation solaire à domicile.
A creuser :)

**Comment by Benjamin-Boisserie-ABC** [comment]
S'il s'agit d'électricité venant d'un fournisseur d'électricité "verte" --> cf. F.A.Q
S'il s'agit bien d'une installation solaire à domicile, nous n'avons en effet pas encore d'estimation car c'est un cas encore minoritaire. En première approximation vous pouvez renseigner 0 dans votre consommation élec mais c'est bien entendu sous estimer l'impact réel qui se devra de prendre l'impact lié à la construction et à l'installation des panneaux PV

**Comment by laem** [comment]
Je ferme au profit de  #624
