### ISSUE TITLE
Empreinte carbone déchets

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#651]
La base de votre calcul pour les déchets est de 734kg et vous citez un article qui donne 193kg.
https://ecolab.ademe.fr/apps/climat/documentation/alimentation/d%C3%A9chets/base

Cette page de l'UE (https://ec.europa.eu/eurostat/web/products-eurostat-news/-/DDN-20200123-1 puis en cliquant sur "The source dataset can be found here") donne une émission de 17,4 million de Tonnes de CO2e pour la gestion des déchets en France en 2018. Soit 260kg de CO2e par habitant. Une partie des déchets étant dûs aux industrie et donc non imputable au particulier, le chiffre de 193kg semble cohérent.

**Comment by Clemog** [comment]
C'est corrigé ici #1415, merci !
