### ISSUE TITLE
Origine électricité + viande bio

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#72]
Vous ne demandez pas d'informations sur l'origine de l'électricité, renouvelable ou non, fournie ou non par un fournisseur ou utilisée en partie en local.
Vous ne dissociez pas l'alimentation en viande de l'alimentation bio : je mange de la viande, mais je mange quasi uniquement en bio, ça compte :)

**Comment by laem** [comment]
> Vous ne demandez pas d'informations sur l'origine de l'électricité, renouvelable ou non, fournie ou non par un fournisseur ou utilisée en partie en local.

Voir #4 

>  Vous ne dissociez pas l'alimentation en viande de l'alimentation bio : je mange de la viande, mais je mange quasi uniquement en bio, ça compte :)

Malheureusement, je ne crois pas qu'il y ait d'étude qui donne un facteur de différence d'empreinte climat entre la production d'un aliment bio vs pas bio. A creuser cependant.

**Comment by lbranaa** [comment]
Je ferme, réponse apportée par @laem.
