### ISSUE TITLE
pas de source pour l'empreinte carbone d'une maison

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#735]
un chiffre de 17kgco2eq/m² est présenté, sans source. la source peut être 
https://www.bilans-ges.ademe.fr/documentation/UPLOAD_DOC_FR/index.htm?batiments.htm

425kgco2eq/m² par m² construit (maison) avec une durée de vie de 50 ans cela fait 8.5kg/m²/an.

**Comment by laem** [comment]
Voici la source présente dans le tableur MicMac v2.6

> Immeubles de logements collectifs (IC) 525 kgCO2e/m² SHON amortis sur 30 ans - Base carbone ADEME consultée le 22/06/19

Le choix a été fait de prendre la valeur "Immeubles de logements collectifs" légèrement plus grande que celle des maisons individuelles, et diviser par 30 ans. 
Il semble pertinent de diviser par 50 ans en effet : 

> ces valeurs tiennent compte de l’entretien et de l’éventuel remplacement des produits et équipements durant la vie du bâtiment fixée à 50 ans.

Pour l'instant, on ne pose pas la question de l'âge de la maison, donc on n'a pas de soucis d'amortissement comme c'est le cas pour la voiture. Cependant, c'est évidemment un manque, vu l'importance des émissions d'une construction !

On note aussi la grande disparité des données, pour les maisons de 300 à 500, il serait donc pertinent de poser des questions sur les matériaux de construction et utiliser les données du paragraphe "Approche plus détaillée, par quantité de matériaux mis en œuvre", mais ça demande un travail pour savoir quelles questions on peut poser (par exemple, tuile ou ardoise, c'est facile).

**Comment by laem** [comment]
Voir #111
