### ISSUE TITLE
Erreur de calcul et navigation confuse pour éditer ses réponses après coup

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#880]
Bonjour,

Merci pour cette application que je trouve très utile et bien conçue.

J'ai remarqué cependant une erreur dans le calcul. Ayant renseigné Home Cinema: "Non", je vois qu'il apparaît à "False" dans le calcul et qu'il est finalement compté comme non-nul dans mon bilan.

Par ailleurs, lorsque l'on édite les réponses de la simulation après coup, la navigation est bizarre: le bouton "Suivant" amène à la toute dernière question du simulateur.

**Comment by Clemog** [comment]
Résolu merci ! :)
