### ISSUE TITLE
Répondre dans la FAQ aux commentaires "2 tonnes c'est impossible" 

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#890]
Qu'en penses-tu @Benjamin-Boisserie-ABC ? 
le retour venant souvent, ça me semble intéressant d'y mettre un paragraphe.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, il y a une simple phrase à ce sujet dans la F.A.Q. après la partie sur les services publics.

Je pense qu'il faut que ça soit une question à part entière à laquelle on répond

**Comment by laem** [comment]
Oui bien vu, ça en fera aussi une page d'introduction au sujet :+1:

**Comment by avenirclimatique** [comment]
J'ai fait une proposition dans ce sens sur la FAQ, en m'inspirant de ce qu'on avait rédigé pour notre atelier Carbone à ras (Mathieu)
