### ISSUE TITLE
Achat d'occasion, notamment pour le numérique

### ISSUE THREAD

**Issue by krichtof** [datagir/nosgestesclimat#90]
Y a t-il une raison pour laquelle le simulateur ne se soucie pas si le téléphone ou l'ordinateur qu'on utilise est neuf ou d'occasion, alors que cette distinction est faite pour l'électroménager ou le textile ?

**Comment by laem** [comment]
Très bonne question. A relier à #12 : par rapport à l'impact, il y a déjà trop de questions sur le numérique. La priorité est de réduire le nombre de questions, puis par exemple une fois que l'utilisateur a dit qu'il possédait 3/10 équipements, demander si occasion ou pas. 

Quoique, je me pose la question pour le fait qu'un équipement soit d'occasion ou pas. La question de la durée de vie pourrait suffir. C'est tout ce qu'il nous faut pour prendre en compte la réduction d'impact d'un achat d'occasion. Si l'utilisateur ne sait pas l'âge de son téléphone acheté d'occasion, on peut imaginer un "forfait" fixe de 2 ans par exemple pour le téléphone :)

**Comment by krichtof** [comment]
La question de l'occasion peut être pertinente à mon avis. Il est possible que des personnes au bout de 2-3 ans achètent un nouveau téléphone, sans vendre leur ancien.

**Comment by robinparisi** [comment]
La question de l'occasion est complexe : pour moi, le facteur d'émission devrait être entièrement imputé à l'acheteur initial. Par exemple, si nous nous arrêtions toutes et tous d'acheter dès maintenant de l'équipement numérique, la part attenante de l'équipement numérique dans les émissions tendrait vers 0 (en ignorant la partie sur l'utilisation du périphérique), mais physiquement, on pourrait dire qu'il n'y aurait plus d'extraction de matières premières, fabrication, transport, etc... (mais il faudrait peut-être prendre en compte les émissions liées à la distribution du matériel d'occasion).

Maintenant, cette vision est effectivement utopique, car il faut forcément du neuf pour que le marché de l'occasion puisse exister, mais ce marché ne devrait pas peser dans le bilan carbone. Ou alors, il faudrait transférer une partie du bilan carbone du vendeur vers l'acheteur (car le bilan doit aussi être fait en fonction de la durée d'utilisation afin que le facteur d'émission soit réparti sur les années d'utilisation). Dans ce cas de figure, l'effet néfaste selon moi serait un effet rebond qui pourrait pousser l'acheteur à consommer plus, car la revente d'occasion lui permettrait d'alléger son bilan (je peux me dire par exemple que je vais changer d'iPhone tous les ans et que ça n'est pas forcément grave si je revends l'ancien, car sa durée de vie sera indirectement augmentée, mais pas par moi. Ça s'apparente un peu à un transfert de responsabilité ce qui peut être dommage, mais effectivement, c'est toujours mieux que conserver l'objet dans un placard d'où le côté complexe.

**Comment by SonephetR2** [comment]
Discussion intéressante. Ce qui est sûr, c'est que le calculateur ne permet pas actuellement de spécifier l'achat et la possession de plusieurs équipements. L'idéal serait sans doute de prévoir une durée d'amortissement et d'imputer les premières années de possession uniquement. En France, les téléphones portables sont renouvelés en moyenne tous les 2 ans : acheter un téléphone d'occasion ayant 1 an d'âge pourrait donc compter pour 50% de l'impact. Quant aux ordinateurs 4–5 ans, le raison pourrait être le même.

**Comment by martinregner** [comment]
retour via boite contact : 
•	vêtements et autres produits de consommation courante (mobilier, équipement): j'achète d'occasion ou je mutualise.

**Comment by Clemog** [comment]
Discussions intéressantes, je ferme au profit de #1549 :)

**Comment by lbranaa** [comment]
Fermé au profit de #1549
