### ISSUE TITLE
Refonte de la section /actions

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#903]
> On a plein d'idées pour mieux mettre en action les utilisateurs après leur test. A venir 

J'ai bien commencé à régler ce sujet, ici : https://github.com/datagir/nosgestesclimat-site/pull/323

**Comment by Benjamin-Boisserie-ABC** [comment]
Afin d'engager l'utilisateur au passage à l'action, 2 approches semblent pertinentes et peuvent exister conjointement dans l'outil :

# Approche 1
**On propose à l’utilisateur des actions pour réduire son empreinte carbone par poste**. Pour chaque poste serait proposé **3 actions** qui s'adapteraient au mieux au profil de l'utilisateur. Ces actions seraient proposées en fonction du **niveau d'effort** qu'elles demandent (pour être mises en œuvre) et en fonction de la réduction des émissions de GES qu'elles permettent. Cette approche descendante vise à créer par poste d'émission des "minis" scénarios de réduction. 
L'objectif de cette approche et de fournir **"rapidement"** et de manière descendante des actions afin qu'après avoir retenu un chiffre (via le calcul de l'empreinte), l'utilisateur retienne des actions clés pour réduire son empreinte carbone.
Pour implémenter cette approche, il faudrait donc introduire le paramètre "niveau d'effort" et chaque action se verrait donc attribuée un niveau d'effort. Ce niveau d'effort serait déterminé par nous mêmes. Il est donc **subjectif par nature** (même entre nous nous ne sommes pas forcément d'accord^^). Néanmoins c'est un bon moyen de mettre en avant certaines "philosophies" importantes pour réduire son empreinte carbone (réduction quantité viande, place de la voiture individuelle, etc.)

Proposition pour les niveaux d'efforts. 3 échelons : 
 - niveau 0 : pas de modification/modification très faible des habitudes
 - niveau 1 : modification modérée des habitudes 
 - niveau 2 : modification conséquente des habitudes

**Avantage** : proposer "instantanément" des actions  
**Inconvénient** : peu interactives et descendantes.

_Variante_ : on propose plusieurs niveaux d'ambition pour ces scénarios (-25 % -50 % -75 % de réduction de l'empreinte), ceci afin de "rendre" quelque peu la main à l'utilisateur
_Variante_ 2 : donner la possibilité "d'activer" le mode "je veux être radical". 3 actions (ou moins) permettant une forte réduction de son empreinte seraient alors proposées (à la place de 3 actions ayant un niveaux d'effort progressif)

# Approche 2 : 
On propose à l'utilisateur de **construire son scénario de transition**. L'utilisateur devra lui même choisir les actions qu'il met en place pour réduire son empreinte carbone. Cette approche permet de **ne pas avoir à utiliser de niveaux d'efforts**. On évite donc certains écueils potentiels de l'approche 1 de type "votre parcours ne me correspond pas". Cette approche peu être rendue **interactive** (barre qui se remplit au fur et à mesure que l'utilisateur choisit des actions et elle se remplit d'autant plus vite que des actions impactantes sont choisies). L'objectif de cette approche est que l'utilisateur "joue" avec les actions proposées pour voir lesquelles lui permettent d'atteindre l'objectif de réduction de son empreinte (c.a.d de remplir la jauge). 

**Avantage** : approche interactive et moins descendante que l'approche 1, ce qui favorisera l'adoption des actions étant donné qu'elles "auront été choisies"
**Inconvénient **: certaines philosophies clés pour réduire l'impact d'un poste peuvent être laissées de côté. A nous de nous assurer que ce ne sera pas le cas (ex : on ne peut pas passer à côté d'une réduction de la quantité de viande consommée si l'on souhaite atteindre une alimentation compatible avec l'objectif 2T).

**Comment by Benjamin-Boisserie-ABC** [comment]
Complément de réflexion pour l'approche 1 : avoir le paramètre niveau d'effort qui s'adapte en fonction du profil de l'utilisateur. Un exemple : si l'on constate beaucoup d'heures de vol on peut en déduire que le niveau d'effort de l'action "se passer de l'avion" peut être de niveau 2 pour cet utilisateur, là ou elle sera de niveau 1 pour un utilisateur n'ayant pas pris l'avion dans l'année et dont l'empreinte carbone du transport est liée à l’utilisation de la voiture individuelle. A l'inverse toute action visant à réduire l'utilisation de la voiture sera de niveaux 1 voir 0 pour un urbain où les offres de transport en commun sont nombreuses mais de niveau 2 pour une personne dont les déplacements s'articulent autour de la voiture.

**Comment by martinregner** [comment]
> Complément de réflexion pour l'approche 1 : réfléchir à ce que le paramètre niveau d'effort s'adapte en fonction du profil de l'utilisateur. 

Il faut sans doute réfléchir à des premières façons simples d'aller vers cette approche sans la construire telle quelle d'emblée car c'est en effet complexe. Par ex. constituer des "packages" d'actions de plus en plus garnis du niveau 0 au niveau 2 ; si l'utilisateur a déjà réalisé ces actions, les paniers se "vident" quand il arrive dessus.

Des idées de "nom" pour les deux options / parcours :
1. Être guidé pour réduire mon bilan
2. Choisir mes actions une par une

**Comment by laem** [comment]
> c'est en effet complexe.

Je confirme. Et ma crainte va plus loin : dans #924, le niveau d'effort calculé... est très corrélé avec le gain de l'action. Si je prends beaucoup l'avion, passer à 0 est compliqué en termes d'effort, en proportion du gain d'empreinte. Idem pour "aller au travail en transport en commun" : plus j'y vais un nombre de jours important par semaine (/5), plus je fais de kilomètres, plus c'est compliqué, mais plus aussi l'empreinte est élevée. 
Ainsi, l'empreinte de l'action sur ces sujets transport est suffisante pour dénoter l'effort nécessaire dans une 1ère approximation. 
Je vous propose donc de laisser ça de côté et de faire varier l'effort dans une v3 si la v2 montre que ces niveaux d'efforts aident l'utilisateur à faire des choix.

**Comment by laem** [comment]
Pour l'implémentation de tout ça, voir https://github.com/betagouv/ecolab-climat/pull/191

**Comment by laem** [comment]
![image](https://user-images.githubusercontent.com/1177762/110326995-a8d4fb00-8019-11eb-9fc4-8b6b5135159b.png)


![image](https://user-images.githubusercontent.com/1177762/110327000-abcfeb80-8019-11eb-8f70-4dd42d3163d5.png)

**Comment by Benjamin-Boisserie-ABC** [comment]
je réouvre la PR car je pense que l'objectif ici n'est pas atteint avec ce mode guidé mais nous sommes en bonne voie.

Le but de ce mode guidé est de prendre l'utilisateur par la main et devrait donc selon moi d'afficher les actions que devrait mettre en place l'utilisateur pour atteindre l'objectif 2t ramené au poste considéré. Ainsi, les actions d'un poste ne seraient pas toutes présentées à l'utilisateur (pour cela il y a le mode autonome) et on essaierait de lui présenter les actions adaptées à son profil et par niveau d'effort (on n'affiche pas tous de suite "deviens végé ou ne prends plus ta voiture"). C'est ce qu'on a appelé les parcours de maturité quand on en parlait en fevrier/mars. 

On est selon moi sur la bonne voie mais il faudrait affiner l'exercice. Ainsi, je pense que dans le mode guidé qu'on devrait : 
  - faire en sorte qu'une action se calcule en prenant comme prérequis le fait que l'actions précédente ait été réalisée (ex : la 1ère action guidée pour le poste alimentation est "Privilégiez la volaille", la seconde qui serait "réduire par deux la viande" considèrerait que la 1ère action ait été faite (et que donc il n'y a plus de plats "viande 2"). La réduction GES affichée sommerait alors les réductions au fur et à mesure. C'est ce que j'explique en 1071 et je vous remets l'exemple via l'excel 
[Parcours maturité alimentation.xlsx](https://github.com/datagir/nosgestesclimat/files/6764322/Parcours.maturite.alimentation.xlsx)
  - conserver ces niveaux d'effort qui selon moi me semble pertinent pour traduire la difficulté croissante des actions qu'on propose
  - compter peut-être plus que 3 actions (4 ? voir éventuellement 5 ?) car pour certain poste c'est plus complexe (le poste transport notamment).
  - afficher au dessus de la 1ère action l'empreinte initiale du poste et en dessous l'empreinte finale du poste (en ayant mis en œuvre les actions proposées par le mode guidé). Un ex :
![mode_guidé_alimentation](https://user-images.githubusercontent.com/66410914/124474946-6e018a80-dda1-11eb-96c7-793e075b8c52.png)

A rediscuter entre nous mais je pense que cela est nécessaire et se couplera bien avec l'affinage des actions proposées en fonction du profil (voir #1045 et #1069)

**Comment by laem** [comment]
Je ferme cette issue, elle a été en grande partie traitée dans la refonte de ce mois d'octobre 2021.
