### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#910]
Bonjour, je visualise les résultats d'un ami et il semble y avoir des bugs 
https://nosgestesclimat.fr/fin?details=lInfinityt1.86s1.11a1.02d0.16n0.07
"NaN t" pour le logement, 1,19t pour le transport normal car avion mais n'apparaissent pas dans le détail etc.
Bon courage, super outil ! :)

**Comment by Clemog** [comment]
Je ferme au profit de https://github.com/datagir/nosgestesclimat-site/pull/556
