### ISSUE TITLE
Consommation vélo = 0 impact ? et vélo électrique

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#914]
Bonjour,

on m'indique que mon empreinte carbone en roulant à vélo est nulle. Mais l'utilisation d'un vélo implique tout de même (plus nous roulons avec, plus c'est vrai d'ailleurs) l'achat de pièces de rechange et l'entretien n'est pas tout à fait neutre : les pneus, chambres à air, les câbles de frein, la chaîne, les patins de frein etc... Autant de matériaux peu recyclés et recyclables, venant de loin potentiellement... Est-ce vraiment si dérisoire que l'on ne devrait pas le compter ?
Par ailleurs, j'utilise un vélo électrique, ce qui, sauf erreur de ma part, n'est pas pris en compte par votre simulateur. Avec les aides financières des régions notamment, son usage est néanmoins en pleine expansion (je peux en attester ici en Ardèche par exemple). Merci pour votre retour ! Barbara

**Comment by laem** [comment]
Merci pour les remarques ! 

> Est-ce vraiment si dérisoire que l'on ne devrait pas le compter ?

Par rapport aux 10 tonnes de moyenne, oui c'est dérisoire, sauf à avoir 5 vélos :). Nous ferons cependant mieux dès que nous aurons corrigés des problèmes bien plus importants :) 

>  j'utilise un vélo électrique

Même réponse pour le vélo électrique, qui pèse 15-20 kg soit 10 fois moins en ordre de grandeur qu'une voiture, sans compter l'infrastructure.

Je garder l'issue ouverte car nous pouvons documenter cela dans la question du vélo pour éviter d'avoir la même issue soulevée.
