### ISSUE TITLE
alimentation:poisson    véhicule hybride

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#915]
bonjour,
comme protéines en plus des laitages,ou des oeufs,je prends souvent du poisson.
Pour aller au travail,j'utilise une voiture hybride(essence et piles rechargeables),je suis intérimaire et depuis deux ans,il m'arrive de rester sept mois sans mission;sinon,j'effectue environ 80 kms(aller -retour)pour aller à mon travail,parfois,je suis en soins à domicile et je conduis plus.

**Comment by Clemog** [comment]
Résolu depuis :)
