### ISSUE TITLE
Suprise de l'empreinte CO2 du logement

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#923]
Bonjour,

1 152,35 kgCO2e / personnes (personne sans "s") ont été calculés pour environ 800kWh de chauffage au gaz par an pour notre logement abritant 2 personnes.
Cela me semble énorme pour 0,2kg CO2e/kWh de gaz... (Je m'attendais donc à un peu moins de 400kg CO2e).

**Comment by laem** [comment]
bonjour, quelle est la surface du logement ? C'est un paramètre important dans le calcul pour l'empreinte de construction.
