### ISSUE TITLE
chauffage urbain collectif biogaz

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#926]
Comment peut être pris en compte le chauffage collectif urbain au biogaz? Je n'ai pas de notion de kW mais seulement le montant de ma facture...

**Comment by laem** [comment]
Nous aimerions carrément intégrer l'empreinte des réseaux de chaleurs avec une question sur la commune et le branchement aux réseaux disponibles et documentés. 

Voir https://github.com/datagir/nosgestesclimat/issues/872
