### ISSUE TITLE
Problème de retour en arrière (bouton "précédent")

### ISSUE THREAD

**Issue by yukulele** [datagir/nosgestesclimat#927]
À la question « *possédez vous un scooter où une moto* » j'ai répondu « *oui* » par erreur (ou pour test ?) il est impossible de changer mon choix pour « *non* »

**Comment by laem** [comment]
Vous pouvez au choix : 
- cliquer sur "Précédent"
- sur "Modifier mes réponses"

Je ferme en attenant plus d'infos pour savoir si c'est un bug

**Comment by yukulele** [comment]
quand je fait précédant je retourne a la question d'avant (*Connaissez-vous la consommation moyenne de la voiture ?*)

**Comment by yukulele** [comment]
en fait les question a choix multiples ne sont parfois plus affichés quand on à trop utiliser les boutons "suivant" / "précédant"

**Comment by laem** [comment]
Merci pour le retour, je vais investiguer :) Quel navigateur / version (même si je pense que c'est indépendant du nav) ?

**Comment by laem** [comment]
Est-ce que vous retrouvez quand même la question de la moto au clic sur "Modifier mes réponses" ?

**Comment by yukulele** [comment]
Finalement toutes les questions sont positionnellement concernées par ce bug, J'ai fait faire le test a une amie, il lui a été impossible de revenir sur le chiffre de sa consommation d’électricité.

**Comment by laem** [comment]
Merci, c'est bien pris en compte, je m'y mets au plus vite :)

**Comment by yukulele** [comment]
Bonjour,
Le problème ne semble pas corrigé chez moi, il m'est même maintenant impossible de revenir sur aucune question ! :confused:

**Comment by laem** [comment]
@yukulele tu ne vois pas le bouton "Mes réponses" ? C'est le menu qui permet d'aller corriger n'importe quelle réponse saisie.
