### ISSUE TITLE
Le calculateur ne s'applique qu'aux français, or ce n'est pas indiqué

### ISSUE THREAD

**Issue by yukulele** [datagir/nosgestesclimat#929]
Je suppose que les calculs prennent en compte le type de production électrique français ?

Cela n'est indiqué nulle part sur l'outil. Une personne non française qui utilisent l'outil pourrait avoir un bilan sur-(ou sous)-évalué selon le type production de son pays.

**Comment by laem** [comment]
Bonne remarque, voir notamment cette issue où l'on envisage de décliner le calcul pour la Belgique. 
https://github.com/betagouv/ecolab-climat/issues/71
