### ISSUE TITLE
Format non compatible sur smartphone et tablette

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#935]
Dommage que votre plateforme ne soit pas utilisable sur smartphone et tablette ! Le format de correspond pas.
Super initiative en tout cas.

**Comment by laem** [comment]
Bonjour, que voulez-vous dire par là ? Nous construisons l'application justement pour qu'elle soit très simple d'utilisation sur mobile. Quels problèmes avez-vous rencontrés, quel navigateur ?

**Comment by laem** [comment]
Je ferme en attendant plus d'infos.
