### ISSUE TITLE
Cohérence entre calculs viande blanche / et deux fois moins de viande 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#936]
Si l'on consommes 2 fois moins de viande, cela réduit de 6 % l'empreinte CO2 pour 688g de CO2 . 
et si l'on consomme uniquement de la viande blanche on réduit d'une tonne de CO2 pour 0 % 
et si l'on ne consomme plus du tout de viande , on réduit de 1,4t pour 0% 

ces calculs ne nous semblent pas cohérents. pourriez vous nous en dire plus svp. Merci

**Comment by laem** [comment]
Bonjour, bien vu ! C'est un problème de calcul de %, un bug tout bête : on basait les pourcentages sur la valeur en tonnes :/ 
C'est corrigé dans l'imminente prochaine version #930
