### ISSUE TITLE
un correctif s'impose pour les viandes

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#941]
Vos calculs : 300 g par repas boeuf ou agneau, 70g repas poulet, porc ou fromage ! cette différence énorme ne se justifie pas si c'est du boeuf en système herbager. Une étude de l'Institut de l'Elevage conclue que la séquestration du carbone dans le sol enherbé compense l'émission de méthane, qui pénalise l'herbivore et plombe son bilan carbone.
De plus, la déforestation importée du fait de l'alimentation soja des porcs, poulets , poules pondeuses et vaches laitières n'est à l'évidence pas prise en compte dans ces 70g.
Donc pour le boeuf à l'herbe , le bilan carbone est sûrement peu différent de porcs, poulets, produits laitiers d'élevages industriels.
Il serait intéressant de creuser cette question et calculer des chiffres précis.

**Comment by laem** [comment]
Il ne sert à rien de spammer notre formulaire de réponse : une réponse suffit ;) 

#943
