### ISSUE TITLE
Le boeuf à l'herbe, c'est plus écolo que le porc ou le poulet en élévage industriel

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#942]
Vous prenez des chiffres proches de ceux de m'ADEME pour les émissions de viande de boeuf 35.8 kg CO2/kg, et 5.16 pour le porc et le poulet; ce sont effectivement des chiffres qui ont été diffusés partout, ce n'est pas pour

**Comment by laem** [comment]
Issue dupliquée.
