### ISSUE TITLE
le boeuf à l'herbe, c'est plus écolo que le porc ou le poulet en élevage industriel

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#943]
Vous prenez des chiffres proches de ceux de l'ADEME pour les émissions de viande de boeuf 35.8 kg CO2/kg, et 5.16 pour le porc et le poulet; ce sont effectivement des chiffres qui ont été diffusés partout, ce n'est pas pour autant qu'ils sont exacts. Les experts d'AVSF (agronomes et vétérinaires sans frontières) donnent 13 pour le boeuf, et 6 à 9 pour le porc et le poulet.
De plus,une étude de l'Institut de l'Elevage Français prouve que les émissions de méthane des bovins à l'herbe sont compensées par la séquestration du carbone dans les sols des prairies.
Les chiffres très faibles pour porc, poulet, lait, oeufs ne tiennent pas compte, très probablement,  des émissions liées à la déforestation importée pour le soja qui les nourrit. Et votre calcul du bilan carbone pourrait conduire à ne pas diminuer tous ces produits mais uniquement boeuf et agneau.
Ce sont les produits de l'élevage industriel qu'il faut réduire. 96% des porcs sont en élevage industriel, 81% des poulets de chair, 76% des poules pondeuses. Le système herbager vertueux concerne 40% des vaches laitières et 62% des bovins viande (WWF Pulse fiction 2019 )

**Comment by laem** [comment]
Bonjour, merci pour votre retour détaillé. Malheureusement, nous ne faisons pas ici de sélection de données entre différentes sources contradictoires. Il faudra voir directement avec les initiatives de l'ADEME, FoodGES et Agribalyse. Les calculs sont pour l'instant pas encore basés sur la nouvelle version d'agribalyse.
