### ISSUE TITLE
Surestimation de l'empreinte de l'éctroménager

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat#948]
En préparant une intervention autour de NGC, je pense que l'empreinte de l'électroménager est surestimée : 
- on prend le FE issu de MIC MAC qui considère 1kgCO2e/€ sur la base d'un congélateur 415 kgCO2e/unité à 400€/u
- ne devrait-on pas utiliser le ratio monétaire **"Service - Machines et équipements" de la Base Carbone 700 kgCO2e/k€**
- 1200 €/an ça parait beaucoup non. Si on considère un four, une machine à laver, un frigo, un lave vaiselle à 500 € chacun, des plaques et un micro-onde à 300 € chacun. Avec une durée de vie de 5 ans (ce qui est peu je pense on a 2600€/5ans --> soit 520€/an). On peut rajouter autres choses comme un aspi, des robots cuisines, etc. mais on atteindra pas 1200€ je pense.

A-t-on des chiffres sur les achats moyens électroménager ?

**Comment by laem** [comment]
> ne devrait-on pas utiliser le ratio monétaire "Service - Machines et équipements" de la Base Carbone 700 kgCO2e/k€

C'est une bonne question, je ne sais pas. Le titre me fait penser quand même à des machines potentiellement industrielles, comme des grosses machines d'usines, mais je n'en sais pas grand chose.

> 1200 €/an ça parait beaucoup non. 

Oui bonne question. Après, même s'il est bien erroné, ce chiffre n'est utilisé que pour le précalcul avant la simulation, donc assez peu impactant et surtout là pour coller aux estimations d'empreinte macro de ~10 tonnes par personne. 

Personnellement ça me parait beaucoup, mais il faudrait en effet reconstituer ça via des enquêtes. Même problème pour le numérique finalement. Je pense que pour l'électroménager ça se trouve assez facilement.

**Comment by laem** [comment]
Fixed by #975
