### ISSUE TITLE
Quid de l'énergie renouvelable

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#954]
J'ai un fournisseur d'énergie renouvelable, ce qui n'est pas pris en compte dans le calcul

Depuis la page : `https://nosgestesclimat.fr/documentation/logement`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, nous vous laissons lire la FAQ qui explique pourquoi ici : https://nosgestesclimat.fr/contribuer

En bref : cela ne change pas l'empreinte de votre consommation d'électricité.

**Comment by SonephetR2** [comment]
Le fait est qu'il y a une garantie d'injection sur le réseau. Autant les foyers ayant recours à des fournisseurs d'énergie renouvelable ne savent pas d'où proviennent les électrons exacts qu'ils utilisent du fait de la mutualisation du réseau, autant on ne peut nier qu'il y a plus d'injections d'énergie renouvelable, donc moins de tranches de centrales conventionnelles qui sont activées. L'empreinte est indéniablement diminuée en conséquence, même si les chiffres fournis restent bien évidemment théoriques.

En France, avec un parc nucléaire qui produit 16 g de CO2eq par kWh contre 12 g pour de l'électricité éolienne par exemple, la différence n'est pas énorme, mais si le calculateur a une visée ne serait-ce qu'européenne (belges, suisses...), une actualisation pourrait faire sens. Les chiffres sont vieux mais le rapport Bilan Carbone 2007 indique page 35 une empreinte carbone de 42 g de CO2eq par kWh pour EDF contre 327 g pour Electrabel par exemple... (http://temis.documentation.equipement.gouv.fr/documents/Temis/0059/Temis-0059657/16878.pdf)

**Comment by laem** [comment]
Oui, c'est un sujet très pertinent pour d'autres pays comme la Belgique, voir datagir/nosgestesclimat-site/issues/71.

> En France, avec un parc nucléaire qui produit 16 g de CO2eq par kWh contre 12 g pour de l'électricité éolienne 

Pour le nucléaire français, n'est-ce pas 6g ? 
https://www.bilans-ges.ademe.fr/documentation/UPLOAD_DOC_FR/index.htm?conventionnel.htm

Je ferme l'issue, nous la rouvrirons pour l'internationalisation du simulateur :)
