### ISSUE TITLE
Problème technique bouton précédent

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#955]
Bonjour,

Quand on clique sur le bouton précédent, on arrive ensuite directement à la dernière page de résultats sans pouvoir passer par toutes les questions qu'il manquait, c'est dommage !

Merci

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour le retour, c'est déjà identifié et ça va être corrigé rapidement :)
