### ISSUE TITLE
chauffage

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#956]
Je ne chauffe pas, ou 1 ou 2 jour par an j'habite marseille et je nai pas non plus de clim, votre calcul nest pas assez precis.
Maintenant sil est fait intentionnellement pour culpabiliser.  Le manque de transparence provoque en général  leffet inverse a celui recherché... 
Si ke objectif ne sont pas atteignables il n'y  a plus d'objectif...

Depuis la page : `https://nosgestesclimat.fr/documentation/logement`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
> Je ne chauffe pas, ou 1 ou 2 jour par an j'habite marseille et je nai pas non plus de clim, votre calcul nest pas assez precis.

Il vous suffit de renseigner vos kWh. Le chauffage d'un logement se mesure en kWh. 

>  Maintenant sil est fait intentionnellement pour culpabiliser. Le manque de transparence provoque en général leffet inverse a celui recherché...

Quel manque de transparence ? Vous avez fait ce retour depuis la page qui explique justement, de façon complètement inédite, le fonctionnement du calculateur.

>  Si ke objectif ne sont pas atteignables il n'y a plus d'objectif...

C'est la dure réalité. Nos gestes climat n'est pas là pour remettre en cause la physique ni les accords internationaux. Par contre nous avons bien pris note de ce genre de retours.
