### ISSUE TITLE
Le retour en arrière ne fonctionne pas correctement

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#958]
Lorsque j'essaie de revenir en arrière pour modifier certaines réponses, l'outil répond automatiquement à certaines questions sans correction possible, ce qui m'envoie alors des questions non pertinents pour ma situations.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour le retour. La correction est prête, elle sera en ligne aujourd'hui si tout se passe bien. 
On va simplement supprimer ce bouton précédent trop compliqué à gérer pour l'instant et moins utile que "voir mes réponses".
