### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#962]
Bonjour, dans la question sur la consommation de protéines animales, le poisson n'apparaît dans aucun menu, sauf erreur de ma part. Cordialement

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, oui c'est un problème connu, voir #185
