### ISSUE TITLE
centrales hydro

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#963]
Près de chez moi subsistent les vestiges de vieilles petites unités de production d'électricité qui a permis à la ville de chateaulin de disposer d'un éclairage public avant toute autre ville;la france est un pays très bien irrigué et installer des nanos,micros et petites centrales de basse chute (2m suffisent)partout sur le territoire ou celà est possible;celà permettrait de fournir de l'énergie quand on en a le plus besoin ,en hiver.Je peux développer cette idée...

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour votre contribution, c'est intéressant, mais l'objetif de nosgestesclimat est de *mesurer* l'empreinte, pas de réfléchir ou financer aux solutions concrètes pour la réduire. Peut-être que vous pouvez contacter l'ADEME directement ? @martinregner

**Comment by martinregner** [comment]
Bonjour,
Ces documents pourront vous donner des premières pistes et vous accompagner dans les différentes étapes à franchir pour de tels projets : https://www.ademe.fr/hydroelectricite-rehabiliter-optimiser-site-montage-juridique-financier
