### ISSUE TITLE
Poisson

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#964]
Le calculateur ne permet pas d'évaluer la consommation de poisson. Est ce que la consommation du poisson augmente ou diminue une empreinte carbone, par rapport à la viande?

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
C'est prévu, dans #185 , merci !
