### ISSUE TITLE
utilisation de la voiture

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#965]
faire campagne ou pression auprès des assurances auto pour que le partage des véhicules soit encouragé plutôt que pénalisé ("si la personne à qui vous prêtez votre véhicule a un dommage, c'est un malus pour vous")

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci pour la suggestion, peut-être à intégrer dans une action plus vaste du genre "prêter sa voiture" qui noterait ce point ? 
C'est noté !!
