### ISSUE TITLE
Chauffage bois : bûches ET granulés en même temps

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#968]
Bonjour
Pas de possibilité de mutualiser les réponses bois et granulés
Valable pour beaucoup d'autres questions,sur d'autres thèmes

Depuis la page : `https://nosgestesclimat.fr/documentation/logement/bois/consommation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour le retour. Vous pouvez nous en dire plus ? 
Vous avez deux installation bois dans une maison ?
