### ISSUE TITLE
Nourriture

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#971]
Je ne mange que deux repas par jour, au petit déjeuner un gros plat (chaud en hiver, froid en été) de légumes et légumineuses bio, parfois un oeuf, et au diner, ou je bois du vin, je mange généralement du "grignotage" : olives, cacahuètes, pain (maison bio), du fromage et parfois des charcuteries, des sardines ou du saumon fumé. 1-2 fruits bio par jour. C'est rare que je mange de la "vraie" viande, 1-2 fois/mois. J'achète tout ce que je peux en vrac (j'ai la chance d'avoir une Biocoop comme commerce de proximité!). Je bois beaucoup de thé bio.

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/déjeuner-et-dîner`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Voir #185
