### ISSUE TITLE
Je ne chauffe pas, ...

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#977]
Je ne chauffe pas, ma vieille maison est bien isolée et quand il fait froid, je m’habille chaudement de laine et je fais de l’exercice physique. 81 ans

Depuis la page : `https://nosgestesclimat.fr/documentation/logement/empreinte-chauffage`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, merci pour votre retour ! C'est remarquable. Vos kWh, saisis dans l'outil, doivent en être révélateurs.
