### ISSUE TITLE
Prise en compte de l'âge du logement

### ISSUE THREAD

**Issue by SonephetR2** [datagir/nosgestesclimat#983]
L'impact est gigantesque, simplifier sur ce paramètre ne fait pas sens.

L'amortissement du bâti se fait actuellement sur 30 ans dans le calculateur, or, en France, 24% du parc de logements date d'avant 1949 et 24% entre 1949 et 1974 par exemple (https://www.insee.fr/fr/statistiques/fichier/2586377/LOGFRA17.pdf). Dans un cas comme le mien – je vis dans une propriété qui fête ses 90 ans d'âge, solidement bâti, n'a jamais eu besoin de travaux structurels et pourrait sans doute résister plusieurs siècles –, le calculateur m'affiche un amortissement du bâti représentant 1,6 t kgCO2e dans mon cas, soit 40% de l'impact affiché dans mon cas !

**Comment by laem** [comment]
Voir  #111, merci pour les informations supplémentaires, il faut en effet qu'on s'en occupe vite :+1:
