### ISSUE TITLE
Refaire une simulation

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#985]
Bonjour, je souhaiterais refaire le test mais à chaque fois que j'ouvre la page, cela vient sur mon résultat... Or des choses ont changé depuis la dernière simulation. Comment faire ? 
Merci.
Mélanie

Depuis la page : `https://nosgestesclimat.fr/documentation/logement/baisse-1-degré`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci pour le retour. Bon, c'est le 4ème en 4 jours. 

- soit il y a une faille d'UX où le bouton "Mes réponses" n'est pas visible
- soit l'indirection pour effacer ses réponses est trop grande

Par contre il faut réfléchir au fait de mettre un nouveau bouton dans la barre des boutons, ça risque de l'encombrer. Peut-être que c'est "terminer", introduit d'abord comme un bouton de développement, qui devrait être remplacé.

**Comment by laem** [comment]
OK, je teste donc une solution dans datagir/nosgestesclimat-site/pull/225
