### ISSUE TITLE
Ajouter un bouton pour RAZ (effacer les cookies)

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#986]
Bonjour,
Super site. Juste ajouter un bouton de RAZ, car une fois le bilan fait, il est conservé, et on ne peut pas en refaire un nouveau.
Merci

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, est-ce que vous voyez le bouton "mes réponses" ? Il vous donne accès à un écran qui vous permet d'effacer votre simulation.
