### ISSUE TITLE
Pas de bilan possible

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#987]
On promet de l'interactivité et il n'y en a pas. Pas assez pointu.

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation/petit-déjeuner/type/français`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, nous avons besoin de plus d'infos sur un problème pour le corriger.
