### ISSUE TITLE
Comment réinitialiser le calcul

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#988]
Une fois le test effectué, on ne peut pas revenir en arrière et modifier des réponses, le bilan final s'affiche toujours.
Comment reprendre la simulation ?!

Depuis la page : `https://nosgestesclimat.fr/documentation/alimentation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, ne voyez-vous pas le bouton "Mes réponses" ? Je ferme en attendant votre retour.
