### ISSUE TITLE
On ne peut pas répondre à certaines questions petit déjeuner  seulement fruits pain  fromage blanc café t

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#989]
Transport tram de temps en temps 
Train depuis peu 600 Km 
Il n’y a pas de cases où on peut ajouter ces cas particuliers

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Pour le petit dej : pris en comtpe dans #453 
Pour le train et le tram, vous devez normalement avoir une question pour ça. Ce n'est pas le cas ?
