### ISSUE TITLE
Pas de partage réseau possible sur Chrome

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#995]
Bonjour, sur Chrome, je n'ai pas accès au lien de partage. Je l'ai sur Firefox

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by martinregner** [comment]
Un autre retour vient d'arriver en ce sens
> Je ne parviens pas à partager les résultats de simulation. Est-ce lié à ma version google chrome?
![image](https://user-images.githubusercontent.com/46482115/114583012-730edc00-9c81-11eb-9efa-36d41991ce45.png)

**Comment by laem** [comment]
Tu as des infos sur le navigateur / l'appareil ? L'écran semble super petit en hauteur, c'est très rare, ça semble être la cause.
Le lien de partage est caché en bas.

**Comment by martinregner** [comment]
Le deuxième je ne sais pas, mais pour le premier c'est une collègue, donc a priori un ordi assez "classique". Et le bouton apparait sur Firefox, mais pas sur Chrome 🤔

**Comment by laem** [comment]
OK, j'ai bien trouvé le problème, la hauteur d'écran faible. On dirait que ça concerne les tablettes.

![Uploading Capture d’écran du 2021-04-19 09-32-57.png…]()

**Comment by laem** [comment]
C'était aussi le cas sur iPhone visiblement... merci pour le retour !

**Comment by laem** [comment]
C'est corrigé normalement, @martinregner je te laisse vérifier avec ta collègue et fermer :) ?

**Comment by laem** [comment]
Je ferme jusqu'à nouvel ordre

**Comment by martinregner** [comment]
Yes, pas eu de nouvelles ...
