### ISSUE TITLE
Nouvelle simulation

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#996]
Bonjour, pourriez-vous intégrer une fonction pour refaire une simulation sans garder en mémoire une simulation précédente ? Il faut quitter son navigateur pour en refaire une actuellement car sinon on revient toujours aux résultats de la première simulation, même en revenant sur la page d'accueil du site.
Cordialement

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, nous avons ajouté un bouton "recommencer". 
N'hésitez pas à nous dire si ce bouton ne convient pas.
