### ISSUE TITLE
Orthographe

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat#997]
Les données par personne, sans "s" à personne.
Remplacer "e" par "environ.
D. Varboom

Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
> Les données par personne, sans "s" à personne.

Oui, notre système d'unités ne gère pas bien les pluralisation encore :/

>  Remplacer "e" par "environ.

Parlez vous du "e" de kgCO2e ? Dans ce cas c'est "équivalent", pas "environ". Il y a plus d'infos dans le lien à côté, "dans cet article".

Merci pour les retours :)
